var topic1_2_01336 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "topic1_2_01336单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 272752,
                "Body": "{\"A\":\"11            \",\"B\":\"12             \",\"C\":\"13              \",\"D\":\"14\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "11,12,13,14任务的优先级分别是1,100,500,1000，则其中不可进行资源调配的任务是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272854,
                "Body": "{\"A\":\" 可以在80小时内完成 \",\"B\":\" 不能再进一步进行逻辑细分了 \",\"C\":\" 可由一个人完成 \",\"D\":\" 可以进行实际估算\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为了有效地管理项目，应该将工作分解为更小的部分，以下各项中，哪一项不能说明任\n务应该分解到什么程度？（ ）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286092,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>系统整合</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>质量评估</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>实施软件配置管理不包括</span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286096,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>活动</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>任务</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>基线</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>要有效地进行配置管理，需要建立一个配置管理库存放软件</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285988,
                "Body": "{\"A\":\"源代码复用\",\"B\":\"目标代码复用\",\"C\":\"设计结果复用\",\"D\":\"分析结果复用\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件资源的复用方式中，最低级别的复用是</span></p>",
                "Answer": "A",
                "Mark": "<p class=\"MsoNormal\"><br></p>",
                "Judge": -2
            },
            {
                "ID": 272759,
                "Body": "{\"A\":\" 估算 \",\"B\":\" 预算 \",\"C\":\" 直接成本 \",\"D\":\" 间接成本\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在成本管理过程中，项目经理确定的每个时间段，各个工作单元的成本是",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272676,
                "Body": "{\"A\":\" 需求设计 \",\"B\":\" 需求获取 \",\"C\":\" 需求分析 \",\"D\":\" 需求变更\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下面哪个不是需求管理的过程（ ）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286098,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>分配</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>描述</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>计划</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在软件项目配置管理中，配置控制委员会负责评审和批准对基线的</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286093,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>基线配置项状</span><span>态</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>项目开发进度</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>过程完成情况</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件功能实现说明</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>配置状态报告应着重反映</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286095,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>甘特</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>资源图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>网络图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>下列进度管理图中能反映任务之间逻辑依赖关系的是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272843,
                "Body": "{\"A\":\" 额外需求的成本 \",\"B\":\" 需求变更的成本 \",\"C\":\" 确保符合需求的成本 \",\"D\":\" 固定成本\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "“质量成本”是一个项目管理概念，它说明了下列哪项成本（ ）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272673,
                "Body": "{\"A\":\"前置任务          \",\"B\":\"工期         \",\"C\":\"开始时间        \",\"D\":\"完成时间\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "“甘特图”视图中，设定任务相关性的域名是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286097,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>参数估算法</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>类比估算法</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>专家估算法</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>功能点估算</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在项目初期，进行竟标合同的时候，一般采用的成本估算方法是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285984,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更识别</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>变更文档</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>变更实现</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更约束</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">需求变更管理过程分为</font>3<font face=\"宋体\">个阶段，分别是变更描述、变更分析和</font></span><span><o:p></o:p></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272848,
                "Body": "{\"A\":\" 质量是对需求的满足程度，而等级是对质量的排序。 \",\"B\":\" 质量是对需求的满足程度，而等级是对货物和服务的排序。 \",\"C\":\" 在项目管理过程中，质量和等级没有明显的区别。 \",\"D\":\" 质量是项目的最终结果，而等级是项目进展过程中对质量的排序。\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量与等级的区别是什么（ ）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272713,
                "Body": "{\"A\":\" 功能需求 \",\"B\":\" 系统需求 \",\"C\":\" 质量特性 \",\"D\":\" 业务需求\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ） 定义了开发人员必须实现的软件功能，使得用户通过使用此软件能完成他们的任\n务，从而满足了业务需求。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272663,
                "Body": "{\"A\":\" 形象 \",\"B\":\" 质量 \",\"C\":\" 利润 \",\"D\":\" 效益\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ）是企业的生命也是信誉。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272671,
                "Body": "{\"A\":\"时间范围和费用           \",\"B\":\"工期质量和资金   \",\"C\":\"时间质量和成本           \",\"D\":\"质量范围和工期\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理中的项目三角形是指",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272815,
                "Body": "{\"A\":\" 强制性依赖关系 \",\"B\":\" 软逻辑关系 \",\"C\":\" 外部依赖关系 \",\"D\":\" 里程碑\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "“软件编码完成之后，我才可以对它进行软件测试”,这句话说明了哪种依赖关系？（ \n）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272762,
                "Body": "{\"A\":\" 功能模块 \",\"B\":\" 质量标准 \",\"C\":\" 资源及数量 \",\"D\":\" 估算成本\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "估算文件不包括以下哪一项",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272845,
                "Body": "{\"A\":\" 对每个工作包增加工作时间 \",\"B\":\" 项目生存期的各个阶段都需要实施的 \",\"C\":\" 只需要做一次 \",\"D\":\" 只有大的项目才需要的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量控制是（ ）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286100,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险识别</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险规划</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险收集</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>风险管理的过程不包括</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272781,
                "Body": "{\"A\":\" 瀑布模型 \",\"B\":\" 原型 \",\"C\":\" 螺旋模型 \",\"D\":\" 模型\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对于风险比较大的项目，最好选择（ ）生存期模型，",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272763,
                "Body": "{\"A\":\" 代码行 \",\"B\":\" 功能点 \",\"C\":\" 类比法 \",\"D\":\" 关键路径法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "常见的成本估算方法不包括哪一项",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272810,
                "Body": "{\"A\":\"AB            \",\"B\":\"ABC\",\"C\":\"ABCD           \",\"D\":\"ABCDE\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Microsoft Project中的一个资源可以设置多重费率，这些费率是",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272736,
                "Body": "{\"A\":\" 开发出初步原型 \",\"B\":\" 提交一份工作陈述 \",\"C\":\" 提交项目章程 \",\"D\":\" 提交一份完整的软件需求规格说明书\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析完成的标志是（ ）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272831,
                "Body": "{\"A\":\" 识别要求    \",\"B\":\" 确定清楚而又能实现的目标 \",\"C\":\" 权衡质量、范围、时间和费用的要求 \",\"D\":\" 制定符合项目经理期望的计划和说明书\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "管理一个项目包括以下内容，除了:",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286099,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>完成得更晚</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>性能更好</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>Brooks<font face=\"宋体\">定律指出：向一个已经拖延的项目追加新的开发人员，可能会使该项目</font></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272844,
                "Body": "{\"A\":\" 质量保证 \",\"B\":\" 质量规划 \",\"C\":\" 质量控制 \",\"D\":\" 质量改进\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "增加有益的活动过程减少没有价值的活动过程是哪类质量活动（ ）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272821,
                "Body": "{\"A\":\" 做什么 \",\"B\":\" 怎么做 \",\"C\":\" 何时做 \",\"D\":\" 为谁做\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析是回答系统必须（　 　）的问题",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 285983,
                "Body": "{\"A\":\"具体性\",\"B\":\"抽象性\",\"C\":\"功能性\",\"D\":\"效率性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件项目产品的特点除了缺陷检测的困难性、高度的复杂性和缺乏统一规则之外，还有</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286094,
                "Body": "{\"A\":\"投资风险\",\"B\":\"控制风险\",\"C\":\"分析风险\",\"D\":\"技术风险\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\">根据内容将风险分为：管理、组织、外部风险和</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286091,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>软件风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件质量评审</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>软件设计监督</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件系统测试</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件项目管理过程中的</font>“过滤器”是指</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285989,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险避免</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险转移</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险缓解</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险接受</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>购买保险是一种风险应对策略，它所属的风险应对策略的类型是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285987,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>支持活动是指软件的维护</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件设计就是编写代码</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>问题定义活动是发现设计中的错误</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>维护活动就是证明程序正确</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件工程活动主要包括</font>8<font face=\"宋体\">个方面，以下说法正确的是</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272836,
                "Body": "{\"A\":\" 组合 \",\"B\":\" 项目群 \",\"C\":\" 投资 \",\"D\":\" 合作\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为相同的功能组合而实施的一系列应用开发项目，作为（ ）的一部分，后者能够得到更\n好的管理。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272820,
                "Body": "{\"A\":\" 时间很紧的 \",\"B\":\" 按时的 \",\"C\":\" 非关键路径 \",\"D\":\" 关键路径\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "资源平衡最好用于（ ）活动",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272724,
                "Body": "{\"A\":\" 展现目前的人力资源质量 \",\"B\":\" 展现项目中人力资源在各个阶段的分布情况 \",\"C\":\" 说明人员分工情况 \",\"D\":\" 说明项目需要的所有资源\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "人力资源分配图是 （ ）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 285986,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>状态审计</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>基线维护</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件配置管理过程分为</font>4<font face=\"宋体\">个步骤，分别是计划配置管理、开发配置管理方案、配置控制和</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285985,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>人力资源配置的表示图</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>各项成本与时间的对照图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>各种任务活动与成本的关系图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>各</span><span>种任务活动与日历的对照图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>甘特图又称横道图，它是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 272823,
                "Body": "{\"A\":\"比较基准     \",\"B\":\"中期计划   \",\"C\":\"完成百分比    \",\"D\":\"工期       \",\"E\":\"资源\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在Microsoft Project的项目跟踪中，需设置",
                "Answer": "A,B,C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272808,
                "Body": "{\"A\":\"水电       \",\"B\":\" 搅拌机         \",\"C\":\"电工      \",\"D\":\" 砼       \",\"E\":\" 项目经理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列资源中属于工时资源的有",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272779,
                "Body": "{\"A\":\"制订计划     \",\"B\":\"跟踪计划   \",\"C\":\"管理项目      \",\"D\":\"报告项目   \",\"E\":\"结束项目\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "成功的项目管理包括的主要阶段有",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 1932363,
                "Body": "{\n  \"A\": \"项目活动清单及其相关的支持细节\",\n  \"B\": \"项目产出物的说明和描述\",\n  \"C\": \"项目活动之间的必然依存关系\",\n  \"D\": \"项目活动之间的人为依存关系\",\n  \"E\": \"责任分配矩阵\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目活动排序的依据包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932205,
                "Body": "{\n  \"A\": \"风险后果的大小\",\n  \"B\": \"风险后果的性质\",\n  \"C\": \"项目风险的影响\",\n  \"D\": \"风险后果的时间性\",\n  \"E\": \"风险的稳定性\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列可以用来衡量对项目风险造成的后果的有",
                "Answer": "A,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932420,
                "Body": "{\n  \"A\": \"功能性\",\n  \"B\": \"简便性\",\n  \"C\": \"可维护性\",\n  \"D\": \"可规范性\",\n  \"E\": \"可移植性\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "国家标准规定了软件质量可用6个特性来评价，以下属于这6个特性的有",
                "Answer": "A,B,C,E",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932364,
                "Body": "{\n  \"A\": \"甘特图可用于W\",\n  \"B\": \"S的任何层次，除了用于进度计划编制外，还可用于进度控制\",\n  \"C\": \"甘特图一般只适用于比较简单的小型项目\",\n  \"D\": \"甘特图不能系统地表达一个项目所包含的各项工作之间的复杂关系\",\n  \"E\": \"甘特图可以进行定量的计算和分析\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面对甘特图的表述中正确的有",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932419,
                "Body": "{\n  \"A\": \"配置构造\",\n  \"B\": \"配置控制\",\n  \"C\": \"状态部署\",\n  \"D\": \"统计  \",\n  \"E\": \"状态审计\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件配置管理过程分为4步，分别是计划配置管理、开发配置管理方案和",
                "Answer": "B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932240,
                "Body": "{\n  \"A\": \"节点表示活动\",\n  \"B\": \"箭线表示活动\",\n  \"C\": \"箭线表示活动(工作)之间的逻辑关系\",\n  \"D\": \"节点是表示活动开始和结束的标志，又称为事项\",\n  \"E\": \"节点表示活动的先后次序\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面对单代号图描述正确的有",
                "Answer": "A,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932239,
                "Body": "{\n  \"A\": \"明确的起止日期\",\n  \"B\": \"预定目标\",\n  \"C\": \"采用相同的开发方法\",\n  \"D\": \"受到资源的限制\",\n  \"E\": \"无穷的资源\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目的共同特点包括",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]