var topic2_1_01336 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "topic2_1_01336单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 285984,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更识别</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>变更文档</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>变更实现</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更约束</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">需求变更管理过程分为</font>3<font face=\"宋体\">个阶段，分别是变更描述、变更分析和</font></span><span><o:p></o:p></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285989,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险避免</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险转移</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险缓解</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险接受</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>购买保险是一种风险应对策略，它所属的风险应对策略的类型是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272701,
                "Body": "{\"A\":\" 参数估算法 \",\"B\":\" 类比估算法 \",\"C\":\" 专家估算法 \",\"D\":\" 功能点估算\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在项目初期，进行竞标合同的时候，一般采用的成本估算方法是",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272821,
                "Body": "{\"A\":\" 做什么 \",\"B\":\" 怎么做 \",\"C\":\" 何时做 \",\"D\":\" 为谁做\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析是回答系统必须（　 　）的问题",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286099,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>完成得更晚</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>性能更好</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>Brooks<font face=\"宋体\">定律指出：向一个已经拖延的项目追加新的开发人员，可能会使该项目</font></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286095,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>甘特</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>资源图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>网络图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>下列进度管理图中能反映任务之间逻辑依赖关系的是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285983,
                "Body": "{\"A\":\"具体性\",\"B\":\"抽象性\",\"C\":\"功能性\",\"D\":\"效率性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件项目产品的特点除了缺陷检测的困难性、高度的复杂性和缺乏统一规则之外，还有</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272854,
                "Body": "{\"A\":\" 可以在80小时内完成 \",\"B\":\" 不能再进一步进行逻辑细分了 \",\"C\":\" 可由一个人完成 \",\"D\":\" 可以进行实际估算\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为了有效地管理项目，应该将工作分解为更小的部分，以下各项中，哪一项不能说明任\n务应该分解到什么程度？（ ）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286094,
                "Body": "{\"A\":\"投资风险\",\"B\":\"控制风险\",\"C\":\"分析风险\",\"D\":\"技术风险\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\">根据内容将风险分为：管理、组织、外部风险和</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272775,
                "Body": "{\"A\":\"摘要任务本身的开始时间和完成时间\",\"B\":\"最晚开始的子任务的开始时间和最早结束的子任务的完成事件\",\"C\":\"最早开始的子任务的开始时间和最晚结束的子任务的完成时间            \",\"D\":\"项目开工的时间和竣工的时间\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "摘要任务的开始时间和完成时间取决于",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272774,
                "Body": "{\"A\":\"平均工期      \",\"B\":\"预期工期       \",\"C\":\"工时            \",\"D\":\"单位\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在用“PERT分析”进行工期的预估时，除要输入乐观工期和悲观工期外，还要输入",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272817,
                "Body": "{\"A\":\" 50% \",\"B\":\" 68.3% \",\"C\":\" 70% \",\"D\":\" 99.7%\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对一个任务进行进度估算时,A是乐观者,估计是6天完成,B是悲观者,估计是24天完成,C是\n有经验者认为最有可能是12天完成，那么这个任务的历时估算是介于10天到16天的概率是（ \n）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272676,
                "Body": "{\"A\":\" 需求设计 \",\"B\":\" 需求获取 \",\"C\":\" 需求分析 \",\"D\":\" 需求变更\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下面哪个不是需求管理的过程（ ）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272845,
                "Body": "{\"A\":\" 对每个工作包增加工作时间 \",\"B\":\" 项目生存期的各个阶段都需要实施的 \",\"C\":\" 只需要做一次 \",\"D\":\" 只有大的项目才需要的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量控制是（ ）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272846,
                "Body": "{\"A\":\" 质量计划是针对单一的产品、项目、服务和合同制定的 \",\"B\":\" 质量管理系统是针对单一的产品、项目、服务和合同制定的 \",\"C\":\" 质量管理系统是由一个单独的组织实体使用 \",\"D\":\" 质量计划不属于项目计划的一部分\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量管理计划与质量体系得区别在于（ ）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272725,
                "Body": "{\"A\":\" 如何获取项目成员 \",\"B\":\" 如何解决冲突 \",\"C\":\" 项目经理的团队建设总结 \",\"D\":\" 项目团队的人员什么时候如何加入到团队中和离开团队\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "人员管理计划描述了（ ）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286097,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>参数估算法</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>类比估算法</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>专家估算法</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>功能点估算</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在项目初期，进行竟标合同的时候，一般采用的成本估算方法是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272849,
                "Body": "{\"A\":\" 质量检查\",\"B\":\" 对等评审\",\"C\":\" 抽样分析 \",\"D\":\" 试验设计\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下面哪项是质量计划的方法（ ）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272833,
                "Body": "{\"A\":\" 独特性 \",\"B\":\" 通过渐进性协助实施的 \",\"C\":\" 拥有主要顾客或项目发起人 \",\"D\":\" 具有很小的确定性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列（ ）不属于项目管理的特征",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286100,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险识别</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险规划</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险收集</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>风险管理的过程不包括</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286091,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>软件风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件质量评审</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>软件设计监督</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件系统测试</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件项目管理过程中的</font>“过滤器”是指</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272831,
                "Body": "{\"A\":\" 识别要求    \",\"B\":\" 确定清楚而又能实现的目标 \",\"C\":\" 权衡质量、范围、时间和费用的要求 \",\"D\":\" 制定符合项目经理期望的计划和说明书\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "管理一个项目包括以下内容，除了:",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272663,
                "Body": "{\"A\":\" 形象 \",\"B\":\" 质量 \",\"C\":\" 利润 \",\"D\":\" 效益\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ）是企业的生命也是信誉。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286096,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>活动</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>任务</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>基线</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>要有效地进行配置管理，需要建立一个配置管理库存放软件</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285988,
                "Body": "{\"A\":\"源代码复用\",\"B\":\"目标代码复用\",\"C\":\"设计结果复用\",\"D\":\"分析结果复用\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件资源的复用方式中，最低级别的复用是</span></p>",
                "Answer": "A",
                "Mark": "<p class=\"MsoNormal\"><br></p>",
                "Judge": -2
            },
            {
                "ID": 272844,
                "Body": "{\"A\":\" 质量保证 \",\"B\":\" 质量规划 \",\"C\":\" 质量控制 \",\"D\":\" 质量改进\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "增加有益的活动过程减少没有价值的活动过程是哪类质量活动（ ）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272730,
                "Body": "{\"A\":\"建筑机械的租金  \",\"B\":\"工人的加班费 \",\"C\":\"运输费   \",\"D\":\"水电费\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Microsoft Project资源费率中的每次使用成本是指",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272733,
                "Body": "{\"A\":\"资源名称   \",\"B\":\"材料标签 \",\"C\":\"组   \",\"D\":\"标准费率\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "设定材料资源单位的域是",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272752,
                "Body": "{\"A\":\"11            \",\"B\":\"12             \",\"C\":\"13              \",\"D\":\"14\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "11,12,13,14任务的优先级分别是1,100,500,1000，则其中不可进行资源调配的任务是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 285987,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>支持活动是指软件的维护</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件设计就是编写代码</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>问题定义活动是发现设计中的错误</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>维护活动就是证明程序正确</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件工程活动主要包括</font>8<font face=\"宋体\">个方面，以下说法正确的是</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272856,
                "Body": "{\"A\":\" 甘特图 \",\"B\":\" 网络图 \",\"C\":\" 里程碑图 \",\"D\":\" 资源图\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "( )可以显示任务的基本信息，使用甘特图能方便地查看任务的工期，开始和结束时间以\n及资源的信息。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286092,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>系统整合</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>质量评估</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>实施软件配置管理不包括</span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285986,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>状态审计</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>基线维护</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件配置管理过程分为</font>4<font face=\"宋体\">个步骤，分别是计划配置管理、开发配置管理方案、配置控制和</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272735,
                "Body": "{\"A\":\" 需求获取 \",\"B\":\" 需求管理 \",\"C\":\" 需求开发 \",\"D\":\" 需求工程\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ） 是对需求进行调查、收集、分析、评价、定义等所有活动。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272784,
                "Body": "{\"A\":\" 采用并行执行任务，加速项目进展 \",\"B\":\" 用一个任务取代另外的任务 \",\"C\":\" 如有可能，减少任务数量 \",\"D\":\" 减轻项目风险\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "快速跟进是指（ ）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272813,
                "Body": "{\"A\":\"智能标签      \",\"B\":\"快捷菜单       \",\"C\":\"项目向导       \",\"D\":\"屏幕提示\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "当进行某些敏感操作时，比如修改一项任务所需的时间或涉及的资源，Microsoft Project通常会自动弹出一个",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286098,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>分配</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>描述</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>计划</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在软件项目配置管理中，配置控制委员会负责评审和批准对基线的</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272671,
                "Body": "{\"A\":\"时间范围和费用           \",\"B\":\"工期质量和资金   \",\"C\":\"时间质量和成本           \",\"D\":\"质量范围和工期\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理中的项目三角形是指",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286093,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>基线配置项状</span><span>态</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>项目开发进度</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>过程完成情况</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件功能实现说明</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>配置状态报告应着重反映</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285985,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>人力资源配置的表示图</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>各项成本与时间的对照图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>各种任务活动与成本的关系图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>各</span><span>种任务活动与日历的对照图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>甘特图又称横道图，它是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 272823,
                "Body": "{\"A\":\"比较基准     \",\"B\":\"中期计划   \",\"C\":\"完成百分比    \",\"D\":\"工期       \",\"E\":\"资源\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在Microsoft Project的项目跟踪中，需设置",
                "Answer": "A,B,C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272808,
                "Body": "{\"A\":\"水电       \",\"B\":\" 搅拌机         \",\"C\":\"电工      \",\"D\":\" 砼       \",\"E\":\" 项目经理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列资源中属于工时资源的有",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272779,
                "Body": "{\"A\":\"制订计划     \",\"B\":\"跟踪计划   \",\"C\":\"管理项目      \",\"D\":\"报告项目   \",\"E\":\"结束项目\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "成功的项目管理包括的主要阶段有",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 1932243,
                "Body": "{\n  \"A\": \"对项目目标的清晰理解\",\n  \"B\": \"每位成员的角色和职责界定明确\",\n  \"C\": \"队员之间不沟通\",\n  \"D\": \"团队士气高涨\",\n  \"E\": \"团队成员的目标不一致\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "高效项目团队的特征包括",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932364,
                "Body": "{\n  \"A\": \"甘特图可用于W\",\n  \"B\": \"S的任何层次，除了用于进度计划编制外，还可用于进度控制\",\n  \"C\": \"甘特图一般只适用于比较简单的小型项目\",\n  \"D\": \"甘特图不能系统地表达一个项目所包含的各项工作之间的复杂关系\",\n  \"E\": \"甘特图可以进行定量的计算和分析\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面对甘特图的表述中正确的有",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932421,
                "Body": "{\n  \"A\": \"垂直方案\",\n  \"B\": \"交叉方案\",\n  \"C\": \"水平方案\",\n  \"D\": \"平行方案\",\n  \"E\": \"矩阵方案\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于软件项目团队组织方案的有",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932203,
                "Body": "{\n  \"A\": \"完善性维护\",\n  \"B\": \"适应性维护\",\n  \"C\": \"纠错性维护\",\n  \"D\": \"一致性维护\",\n  \"E\": \"稳定性维护\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "IT软件项目维护主要包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932202,
                "Body": "{\n  \"A\": \"配置识别\",\n  \"B\": \"变更控制\",\n  \"C\": \"配置状态统计\",\n  \"D\": \"配置审核\",\n  \"E\": \"配置申请D配置审核\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件配置管理的活动包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932362,
                "Body": "{\n  \"A\": \"项目实际比计划低\",\n  \"B\": \"项目成本超支\",\n  \"C\": \"项目进度滞后\",\n  \"D\": \"项目进度比计划提前\",\n  \"E\": \"项目成本节约\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "如果进度偏差与成本偏差是一样的，两者都大于0，那么下列表述错误的有",
                "Answer": "B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932419,
                "Body": "{\n  \"A\": \"配置构造\",\n  \"B\": \"配置控制\",\n  \"C\": \"状态部署\",\n  \"D\": \"统计  \",\n  \"E\": \"状态审计\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件配置管理过程分为4步，分别是计划配置管理、开发配置管理方案和",
                "Answer": "B,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]