var topic2_2_01336 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "topic2_2_01336单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 272752,
                "Body": "{\"A\":\"11            \",\"B\":\"12             \",\"C\":\"13              \",\"D\":\"14\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "11,12,13,14任务的优先级分别是1,100,500,1000，则其中不可进行资源调配的任务是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 285985,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>人力资源配置的表示图</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>各项成本与时间的对照图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>各种任务活动与成本的关系图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>各</span><span>种任务活动与日历的对照图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>甘特图又称横道图，它是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285987,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>支持活动是指软件的维护</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件设计就是编写代码</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>问题定义活动是发现设计中的错误</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>维护活动就是证明程序正确</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件工程活动主要包括</font>8<font face=\"宋体\">个方面，以下说法正确的是</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272775,
                "Body": "{\"A\":\"摘要任务本身的开始时间和完成时间\",\"B\":\"最晚开始的子任务的开始时间和最早结束的子任务的完成事件\",\"C\":\"最早开始的子任务的开始时间和最晚结束的子任务的完成时间            \",\"D\":\"项目开工的时间和竣工的时间\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "摘要任务的开始时间和完成时间取决于",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272737,
                "Body": "{\"A\":\" 需求变更 \",\"B\":\" 暂时性 \",\"C\":\" 阶段性 \",\"D\":\" 约束性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ） 是软件项目的一个突出的特点，也是软件项目最为普遍的一个特点。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272791,
                "Body": "{\"A\":\" 矩阵型 \",\"B\":\" 项目型 \",\"C\":\" 职能型 \",\"D\":\" 都一样\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理中的三种组织结构，哪一种组织结构适用于主要由一个部门完成的项目或技术\n比较成熟的项目（ ）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286094,
                "Body": "{\"A\":\"投资风险\",\"B\":\"控制风险\",\"C\":\"分析风险\",\"D\":\"技术风险\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\">根据内容将风险分为：管理、组织、外部风险和</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272845,
                "Body": "{\"A\":\" 对每个工作包增加工作时间 \",\"B\":\" 项目生存期的各个阶段都需要实施的 \",\"C\":\" 只需要做一次 \",\"D\":\" 只有大的项目才需要的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量控制是（ ）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286095,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>甘特</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>资源图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>网络图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>下列进度管理图中能反映任务之间逻辑依赖关系的是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286097,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>参数估算法</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>类比估算法</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>专家估算法</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>功能点估算</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在项目初期，进行竟标合同的时候，一般采用的成本估算方法是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286099,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>完成得更晚</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>性能更好</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>Brooks<font face=\"宋体\">定律指出：向一个已经拖延的项目追加新的开发人员，可能会使该项目</font></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285988,
                "Body": "{\"A\":\"源代码复用\",\"B\":\"目标代码复用\",\"C\":\"设计结果复用\",\"D\":\"分析结果复用\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件资源的复用方式中，最低级别的复用是</span></p>",
                "Answer": "A",
                "Mark": "<p class=\"MsoNormal\"><br></p>",
                "Judge": -2
            },
            {
                "ID": 285984,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更识别</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>变更文档</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>变更实现</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更约束</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">需求变更管理过程分为</font>3<font face=\"宋体\">个阶段，分别是变更描述、变更分析和</font></span><span><o:p></o:p></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272664,
                "Body": "{\"A\":\" 质量评审 \",\"B\":\" 质量保证 \",\"C\":\" 质量规划 \",\"D\":\" 质量控制\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量管理过程的目的是确保项目满足需要执行的过程。主要过程不包含以下哪一项（）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 285989,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险避免</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险转移</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险缓解</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险接受</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>购买保险是一种风险应对策略，它所属的风险应对策略的类型是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286091,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>软件风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件质量评审</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>软件设计监督</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件系统测试</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件项目管理过程中的</font>“过滤器”是指</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286092,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>系统整合</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>质量评估</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>实施软件配置管理不包括</span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272761,
                "Body": "{\"A\":\" 需求或者WBS\",\"B\":\" 资源需求和消耗率 \",\"C\":\" 进度规划 \",\"D\":\" 质量标准\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "成本估算的输入一般不包括以下哪一项",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272763,
                "Body": "{\"A\":\" 代码行 \",\"B\":\" 功能点 \",\"C\":\" 类比法 \",\"D\":\" 关键路径法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "常见的成本估算方法不包括哪一项",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272687,
                "Body": "{\"A\":\"越晚越好     \",\"B\":\"不得晚于……开始   \",\"C\":\"不得晚于……完成  \",\"D\":\"必须完成于\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在一个以完成日期排定的项目中，对某任务设置了“不得早于……完成”的限制，若要取消限制，只需要将限制类型更改为",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272848,
                "Body": "{\"A\":\" 质量是对需求的满足程度，而等级是对质量的排序。 \",\"B\":\" 质量是对需求的满足程度，而等级是对货物和服务的排序。 \",\"C\":\" 在项目管理过程中，质量和等级没有明显的区别。 \",\"D\":\" 质量是项目的最终结果，而等级是项目进展过程中对质量的排序。\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量与等级的区别是什么（ ）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 285983,
                "Body": "{\"A\":\"具体性\",\"B\":\"抽象性\",\"C\":\"功能性\",\"D\":\"效率性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件项目产品的特点除了缺陷检测的困难性、高度的复杂性和缺乏统一规则之外，还有</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285986,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>状态审计</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>基线维护</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件配置管理过程分为</font>4<font face=\"宋体\">个步骤，分别是计划配置管理、开发配置管理方案、配置控制和</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272784,
                "Body": "{\"A\":\" 采用并行执行任务，加速项目进展 \",\"B\":\" 用一个任务取代另外的任务 \",\"C\":\" 如有可能，减少任务数量 \",\"D\":\" 减轻项目风险\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "快速跟进是指（ ）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272810,
                "Body": "{\"A\":\"AB            \",\"B\":\"ABC\",\"C\":\"ABCD           \",\"D\":\"ABCDE\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Microsoft Project中的一个资源可以设置多重费率，这些费率是",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272835,
                "Body": "{\"A\":\" 项目管理 \",\"B\":\" 项目组管理 \",\"C\":\" 项目组合管理 \",\"D\":\" 需求管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "就是将知识、技能、工具和技术应用到项目活动，以达到组织的要求",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272671,
                "Body": "{\"A\":\"时间范围和费用           \",\"B\":\"工期质量和资金   \",\"C\":\"时间质量和成本           \",\"D\":\"质量范围和工期\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理中的项目三角形是指",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272813,
                "Body": "{\"A\":\"智能标签      \",\"B\":\"快捷菜单       \",\"C\":\"项目向导       \",\"D\":\"屏幕提示\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "当进行某些敏感操作时，比如修改一项任务所需的时间或涉及的资源，Microsoft Project通常会自动弹出一个",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286096,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>活动</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>任务</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>基线</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>要有效地进行配置管理，需要建立一个配置管理库存放软件</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272706,
                "Body": "{\"A\":\"FS            \",\"B\":\"SS             \",\"C\":\"FF             \",\"D\":\"SF\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "若任务15必须在任务17完成之前完成，则任务15和任务17的相关性是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286100,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险识别</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险规划</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险收集</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>风险管理的过程不包括</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272670,
                "Body": "{\"A\":\"1个     \",\"B\":\"2个      \",\"C\":\"3个      \",\"D\":\"4个\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "典型的工程项目生命周期包括几个项目阶段？",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286098,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>分配</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>描述</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>计划</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在软件项目配置管理中，配置控制委员会负责评审和批准对基线的</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272815,
                "Body": "{\"A\":\" 强制性依赖关系 \",\"B\":\" 软逻辑关系 \",\"C\":\" 外部依赖关系 \",\"D\":\" 里程碑\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "“软件编码完成之后，我才可以对它进行软件测试”,这句话说明了哪种依赖关系？（ \n）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272725,
                "Body": "{\"A\":\" 如何获取项目成员 \",\"B\":\" 如何解决冲突 \",\"C\":\" 项目经理的团队建设总结 \",\"D\":\" 项目团队的人员什么时候如何加入到团队中和离开团队\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "人员管理计划描述了（ ）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272833,
                "Body": "{\"A\":\" 独特性 \",\"B\":\" 通过渐进性协助实施的 \",\"C\":\" 拥有主要顾客或项目发起人 \",\"D\":\" 具有很小的确定性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列（ ）不属于项目管理的特征",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272762,
                "Body": "{\"A\":\" 功能模块 \",\"B\":\" 质量标准 \",\"C\":\" 资源及数量 \",\"D\":\" 估算成本\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "估算文件不包括以下哪一项",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286093,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>基线配置项状</span><span>态</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>项目开发进度</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>过程完成情况</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件功能实现说明</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>配置状态报告应着重反映</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272712,
                "Body": "{\"A\":\" 约束和假设 \",\"B\":\" 非功能性需求 \",\"C\":\" 功能需求 \",\"D\":\" 用户需求\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ） 描述了用户通过使用本软件产品必须要完成的任务，一般是用户协助提供。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272856,
                "Body": "{\"A\":\" 甘特图 \",\"B\":\" 网络图 \",\"C\":\" 里程碑图 \",\"D\":\" 资源图\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "( )可以显示任务的基本信息，使用甘特图能方便地查看任务的工期，开始和结束时间以\n及资源的信息。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 272823,
                "Body": "{\"A\":\"比较基准     \",\"B\":\"中期计划   \",\"C\":\"完成百分比    \",\"D\":\"工期       \",\"E\":\"资源\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在Microsoft Project的项目跟踪中，需设置",
                "Answer": "A,B,C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272808,
                "Body": "{\"A\":\"水电       \",\"B\":\" 搅拌机         \",\"C\":\"电工      \",\"D\":\" 砼       \",\"E\":\" 项目经理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列资源中属于工时资源的有",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272779,
                "Body": "{\"A\":\"制订计划     \",\"B\":\"跟踪计划   \",\"C\":\"管理项目      \",\"D\":\"报告项目   \",\"E\":\"结束项目\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "成功的项目管理包括的主要阶段有",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 1932366,
                "Body": "{\n  \"A\": \"项目计划\",\n  \"B\": \"项目标准\",\n  \"C\": \"过程质量\",\n  \"D\": \"系统文档\",\n  \"E\": \"需求规格说明书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于过程文档的有",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932420,
                "Body": "{\n  \"A\": \"功能性\",\n  \"B\": \"简便性\",\n  \"C\": \"可维护性\",\n  \"D\": \"可规范性\",\n  \"E\": \"可移植性\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "国家标准规定了软件质量可用6个特性来评价，以下属于这6个特性的有",
                "Answer": "A,B,C,E",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932364,
                "Body": "{\n  \"A\": \"甘特图可用于W\",\n  \"B\": \"S的任何层次，除了用于进度计划编制外，还可用于进度控制\",\n  \"C\": \"甘特图一般只适用于比较简单的小型项目\",\n  \"D\": \"甘特图不能系统地表达一个项目所包含的各项工作之间的复杂关系\",\n  \"E\": \"甘特图可以进行定量的计算和分析\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面对甘特图的表述中正确的有",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932365,
                "Body": "{\n  \"A\": \"范围\",\n  \"B\": \"时间\",\n  \"C\": \"成本\",\n  \"D\": \"质量\",\n  \"E\": \"风险\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于项目管理成功的因素有",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932202,
                "Body": "{\n  \"A\": \"配置识别\",\n  \"B\": \"变更控制\",\n  \"C\": \"配置状态统计\",\n  \"D\": \"配置审核\",\n  \"E\": \"配置申请D配置审核\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件配置管理的活动包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932240,
                "Body": "{\n  \"A\": \"节点表示活动\",\n  \"B\": \"箭线表示活动\",\n  \"C\": \"箭线表示活动(工作)之间的逻辑关系\",\n  \"D\": \"节点是表示活动开始和结束的标志，又称为事项\",\n  \"E\": \"节点表示活动的先后次序\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面对单代号图描述正确的有",
                "Answer": "A,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932417,
                "Body": "{\n  \"A\": \"时间\",\n  \"B\": \"质量\",\n  \"C\": \"成本\",\n  \"D\": \"风险\",\n  \"E\": \"范围\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目管理的要素有6个，其中3个简称TQC,TQC是指",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]