var topic4_1_01336 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "topic4_1_01336单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 285988,
                "Body": "{\"A\":\"源代码复用\",\"B\":\"目标代码复用\",\"C\":\"设计结果复用\",\"D\":\"分析结果复用\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件资源的复用方式中，最低级别的复用是</span></p>",
                "Answer": "A",
                "Mark": "<p class=\"MsoNormal\"><br></p>",
                "Judge": -2
            },
            {
                "ID": 285989,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险避免</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险转移</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险缓解</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险接受</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>购买保险是一种风险应对策略，它所属的风险应对策略的类型是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285985,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>人力资源配置的表示图</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>各项成本与时间的对照图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>各种任务活动与成本的关系图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>各</span><span>种任务活动与日历的对照图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>甘特图又称横道图，它是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272856,
                "Body": "{\"A\":\" 甘特图 \",\"B\":\" 网络图 \",\"C\":\" 里程碑图 \",\"D\":\" 资源图\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "( )可以显示任务的基本信息，使用甘特图能方便地查看任务的工期，开始和结束时间以\n及资源的信息。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272749,
                "Body": "{\"A\":\"100%          \",\"B\":\"400%          \",\"C\":\"800%           \",\"D\":\"1000%\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "泥工组中有8个泥工，若要使这8个泥工全职参与某项工作。则可在“资源工作表”视图中将泥工组资源的最大单位设置为",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272712,
                "Body": "{\"A\":\" 约束和假设 \",\"B\":\" 非功能性需求 \",\"C\":\" 功能需求 \",\"D\":\" 用户需求\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ） 描述了用户通过使用本软件产品必须要完成的任务，一般是用户协助提供。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272774,
                "Body": "{\"A\":\"平均工期      \",\"B\":\"预期工期       \",\"C\":\"工时            \",\"D\":\"单位\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在用“PERT分析”进行工期的预估时，除要输入乐观工期和悲观工期外，还要输入",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286098,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>分配</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>描述</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>计划</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在软件项目配置管理中，配置控制委员会负责评审和批准对基线的</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286092,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>系统整合</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>质量评估</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>实施软件配置管理不包括</span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286099,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>提前完成</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>完成得更晚</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>性能更好</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>Brooks<font face=\"宋体\">定律指出：向一个已经拖延的项目追加新的开发人员，可能会使该项目</font></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272844,
                "Body": "{\"A\":\" 质量保证 \",\"B\":\" 质量规划 \",\"C\":\" 质量控制 \",\"D\":\" 质量改进\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "增加有益的活动过程减少没有价值的活动过程是哪类质量活动（ ）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272663,
                "Body": "{\"A\":\" 形象 \",\"B\":\" 质量 \",\"C\":\" 利润 \",\"D\":\" 效益\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "（ ）是企业的生命也是信誉。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272810,
                "Body": "{\"A\":\"AB            \",\"B\":\"ABC\",\"C\":\"ABCD           \",\"D\":\"ABCDE\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Microsoft Project中的一个资源可以设置多重费率，这些费率是",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286094,
                "Body": "{\"A\":\"投资风险\",\"B\":\"控制风险\",\"C\":\"分析风险\",\"D\":\"技术风险\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\">根据内容将风险分为：管理、组织、外部风险和</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272762,
                "Body": "{\"A\":\" 功能模块 \",\"B\":\" 质量标准 \",\"C\":\" 资源及数量 \",\"D\":\" 估算成本\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "估算文件不包括以下哪一项",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286091,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>软件风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件质量评审</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>软件设计监督</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件系统测试</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件项目管理过程中的</font>“过滤器”是指</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285987,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>支持活动是指软件的维护</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>软件设计就是编写代码</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>问题定义活动是发现设计中的错误</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>维护活动就是证明程序正确</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件工程活动主要包括</font>8<font face=\"宋体\">个方面，以下说法正确的是</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272849,
                "Body": "{\"A\":\" 质量检查\",\"B\":\" 对等评审\",\"C\":\" 抽样分析 \",\"D\":\" 试验设计\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下面哪项是质量计划的方法（ ）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272791,
                "Body": "{\"A\":\" 矩阵型 \",\"B\":\" 项目型 \",\"C\":\" 职能型 \",\"D\":\" 都一样\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理中的三种组织结构，哪一种组织结构适用于主要由一个部门完成的项目或技术\n比较成熟的项目（ ）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272664,
                "Body": "{\"A\":\" 质量评审 \",\"B\":\" 质量保证 \",\"C\":\" 质量规划 \",\"D\":\" 质量控制\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "质量管理过程的目的是确保项目满足需要执行的过程。主要过程不包含以下哪一项（）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272833,
                "Body": "{\"A\":\" 独特性 \",\"B\":\" 通过渐进性协助实施的 \",\"C\":\" 拥有主要顾客或项目发起人 \",\"D\":\" 具有很小的确定性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列（ ）不属于项目管理的特征",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272681,
                "Body": "{\"A\":\"不得早于…完成     \",\"B\":\"越晚越好     \",\"C\":\"不得晚于…完成   \",\"D\":\"必须完成于…\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列限制类型中时间弹性程度最低的是",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286097,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>参数估算法</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>类比估算法</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>专家估算法</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>功能点估算</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>在项目初期，进行竟标合同的时候，一般采用的成本估算方法是</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285986,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>状态审计</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>版本管理</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>基线维护</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更控制</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">软件配置管理过程分为</font>4<font face=\"宋体\">个步骤，分别是计划配置管理、开发配置管理方案、配置控制和</font></span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 285983,
                "Body": "{\"A\":\"具体性\",\"B\":\"抽象性\",\"C\":\"功能性\",\"D\":\"效率性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>软件项目产品的特点除了缺陷检测的困难性、高度的复杂性和缺乏统一规则之外，还有</span></p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272819,
                "Body": "{\"A\":\" 网络图可用于安排计划 \",\"B\":\" 网络图展示任务之间的逻辑关系 \",\"C\":\" 网络图可用于跟踪项目 \",\"D\":\" 网络图可用于详细的时间管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于网络图，下面哪个是不正确的？（）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272759,
                "Body": "{\"A\":\" 估算 \",\"B\":\" 预算 \",\"C\":\" 直接成本 \",\"D\":\" 间接成本\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在成本管理过程中，项目经理确定的每个时间段，各个工作单元的成本是",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286096,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>活动</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>任务</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>基线</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>要有效地进行配置管理，需要建立一个配置管理库存放软件</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272736,
                "Body": "{\"A\":\" 开发出初步原型 \",\"B\":\" 提交一份工作陈述 \",\"C\":\" 提交项目章程 \",\"D\":\" 提交一份完整的软件需求规格说明书\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析完成的标志是（ ）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272816,
                "Body": "{\"A\":\" 强制性依赖关系 \",\"B\":\" 软逻辑关系 \",\"C\":\" 外部依赖关系 \",\"D\":\" 里程碑\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "如果用户提供的环境设备需要５月１０日到位，所以环境测试安排在５月１０日以后，\n这种活动安排的依赖依据是：（ 　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272784,
                "Body": "{\"A\":\" 采用并行执行任务，加速项目进展 \",\"B\":\" 用一个任务取代另外的任务 \",\"C\":\" 如有可能，减少任务数量 \",\"D\":\" 减轻项目风险\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "快速跟进是指（ ）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272843,
                "Body": "{\"A\":\" 额外需求的成本 \",\"B\":\" 需求变更的成本 \",\"C\":\" 确保符合需求的成本 \",\"D\":\" 固定成本\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "“质量成本”是一个项目管理概念，它说明了下列哪项成本（ ）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 285984,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>变更识别</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>变更文档</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>变更实现</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>变更约束</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span><font face=\"宋体\">需求变更管理过程分为</font>3<font face=\"宋体\">个阶段，分别是变更描述、变更分析和</font></span><span><o:p></o:p></span></p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 286093,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>基线配置项状</span><span>态</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>项目开发进度</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>过程完成情况</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>软件功能实现说明</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>配置状态报告应着重反映</span></p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272781,
                "Body": "{\"A\":\" 瀑布模型 \",\"B\":\" 原型 \",\"C\":\" 螺旋模型 \",\"D\":\" 模型\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对于风险比较大的项目，最好选择（ ）生存期模型，",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272775,
                "Body": "{\"A\":\"摘要任务本身的开始时间和完成时间\",\"B\":\"最晚开始的子任务的开始时间和最早结束的子任务的完成事件\",\"C\":\"最早开始的子任务的开始时间和最晚结束的子任务的完成时间            \",\"D\":\"项目开工的时间和竣工的时间\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "摘要任务的开始时间和完成时间取决于",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272835,
                "Body": "{\"A\":\" 项目管理 \",\"B\":\" 项目组管理 \",\"C\":\" 项目组合管理 \",\"D\":\" 需求管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "就是将知识、技能、工具和技术应用到项目活动，以达到组织的要求",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286100,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>风险评估</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>风险识别</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>风险规划</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>风险收集</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>风险管理的过程不包括</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 272760,
                "Body": "{\"A\":\" 成本估算 \",\"B\":\" 成本预算 \",\"C\":\" 成本控制 \",\"D\":\" 成本核算\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "成本管理就是确保项目在预算范围之内的管理过程，不包括以下哪一项",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 286095,
                "Body": "{\"A\":\"<p class=\\\"MsoNormal\\\"><span>甘特</span></p>\",\"B\":\"<p class=\\\"MsoNormal\\\"><span>资源图</span></p>\",\"C\":\"<p class=\\\"MsoNormal\\\"><span>里程碑图</span></p>\",\"D\":\"<p class=\\\"MsoNormal\\\"><span>网络图</span></p>\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p class=\"MsoNormal\"><span>下列进度管理图中能反映任务之间逻辑依赖关系的是</span></p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 126,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 272779,
                "Body": "{\"A\":\"制订计划     \",\"B\":\"跟踪计划   \",\"C\":\"管理项目      \",\"D\":\"报告项目   \",\"E\":\"结束项目\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "成功的项目管理包括的主要阶段有",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272823,
                "Body": "{\"A\":\"比较基准     \",\"B\":\"中期计划   \",\"C\":\"完成百分比    \",\"D\":\"工期       \",\"E\":\"资源\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在Microsoft Project的项目跟踪中，需设置",
                "Answer": "A,B,C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 272808,
                "Body": "{\"A\":\"水电       \",\"B\":\" 搅拌机         \",\"C\":\"电工      \",\"D\":\" 砼       \",\"E\":\" 项目经理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列资源中属于工时资源的有",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 1932363,
                "Body": "{\n  \"A\": \"项目活动清单及其相关的支持细节\",\n  \"B\": \"项目产出物的说明和描述\",\n  \"C\": \"项目活动之间的必然依存关系\",\n  \"D\": \"项目活动之间的人为依存关系\",\n  \"E\": \"责任分配矩阵\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目活动排序的依据包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932240,
                "Body": "{\n  \"A\": \"节点表示活动\",\n  \"B\": \"箭线表示活动\",\n  \"C\": \"箭线表示活动(工作)之间的逻辑关系\",\n  \"D\": \"节点是表示活动开始和结束的标志，又称为事项\",\n  \"E\": \"节点表示活动的先后次序\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面对单代号图描述正确的有",
                "Answer": "A,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932205,
                "Body": "{\n  \"A\": \"风险后果的大小\",\n  \"B\": \"风险后果的性质\",\n  \"C\": \"项目风险的影响\",\n  \"D\": \"风险后果的时间性\",\n  \"E\": \"风险的稳定性\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列可以用来衡量对项目风险造成的后果的有",
                "Answer": "A,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932242,
                "Body": "{\n  \"A\": \"项目范围说明书\",\n  \"B\": \"项目章程\",\n  \"C\": \"范围管理计划\",\n  \"D\": \"产品描述\",\n  \"E\": \"需求规格说明书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目范围规划的输出结果包括",
                "Answer": "A,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932420,
                "Body": "{\n  \"A\": \"功能性\",\n  \"B\": \"简便性\",\n  \"C\": \"可维护性\",\n  \"D\": \"可规范性\",\n  \"E\": \"可移植性\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "国家标准规定了软件质量可用6个特性来评价，以下属于这6个特性的有",
                "Answer": "A,B,C,E",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932362,
                "Body": "{\n  \"A\": \"项目实际比计划低\",\n  \"B\": \"项目成本超支\",\n  \"C\": \"项目进度滞后\",\n  \"D\": \"项目进度比计划提前\",\n  \"E\": \"项目成本节约\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "如果进度偏差与成本偏差是一样的，两者都大于0，那么下列表述错误的有",
                "Answer": "B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1932418,
                "Body": "{\n  \"A\": \"需求阶段\",\n  \"B\": \"启动阶段\",\n  \"C\": \"计划阶段\",\n  \"D\": \"实施阶段\",\n  \"E\": \"结束阶段\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目的生命周期所包括的阶段分别有",
                "Answer": "A,C,D,E",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]