var topic1_1_07169 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "topic1_1_07169单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 283227,
                "Body": "{\"A\":\"汇编语言 \",\"B\":\"机器语言\",\"C\":\"过程化语言 \",\"D\":\"非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第三代程序设计语言属于（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283186,
                "Body": "{\"A\":\"用户          \",\"B\":\"项目负责人        \",\"C\":\"程序员       \",\"D\":\"计算机\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构化程序设计方法是为(    )服务的。",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283333,
                "Body": "{\"A\":\" 插入功能\",\"B\":\" 修改功能\",\"C\":\" 删除功能(让出空间)\",\"D\":\" 实现定量信息与文字信息的协调一致\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "信息库管理应当具备的功能不包括（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283236,
                "Body": "{\"A\":\"操作系统 \",\"B\":\"数据库管理系统\",\"C\":\"高级语言 \",\"D\":\"软件开发工具\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对应用领域的特点依赖最多的软件是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283234,
                "Body": "{\"A\":\"充分了解用户需求 \",\"B\":\"制定发展规划\",\"C\":\"建立逻辑模型 \",\"D\":\"完成系统总体设计\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "AD/Cycle中的需求分析阶段的任务是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283336,
                "Body": "{\"A\":\" 面向过程的程序设计方法\",\"B\":\" 软件工程方法\",\"C\":\" 面向对象的程序设计方法\",\"D\":\" 即插即用的程序设计方法\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是人们为了克服软件危机而提出的软件开发方法（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283290,
                "Body": "{\"A\":\" 软件的管理\",\"B\":\" 资源的管理\",\"C\":\" 跨生命周期的信息的管理\",\"D\":\" 使用人员的管理\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理和版本管理的核心问题是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283208,
                "Body": "{\"A\":\"时序网络 \",\"B\":\"计算机模拟模型\",\"C\":\"结构图 \",\"D\":\"数学与逻辑模型\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发工具的概念模式中，决策表属于的概念模式是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283327,
                "Body": "{\"A\":\" 数据库查询\",\"B\":\" 生成器\",\"C\":\" 通信服务\",\"D\":\" 数据安全控制\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列属于SAA对外系统的通信接口的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283181,
                "Body": "{\"A\":\"有关系统环境、现状及需求的信息  \",\"B\":\"有关软件功能和物理设计的各种信息  \",\"C\":\"有关软件成果本身、包括程序和文档信息  \",\"D\":\"有关用户对系统的各种变更要求及系统变更记录的信息\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中由分析人员(或设计人员)根据需求分析形成了设计方案、设计方案依据哪一类信息?(    )",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283248,
                "Body": "{\"A\":\" 文件系统\",\"B\":\" 信息库\",\"C\":\" 数据库\",\"D\":\" 数据仓库\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的所有成果，一般应当存入（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283320,
                "Body": "{\"A\":\" 处理需求的描述\",\"B\":\" 处理过程的描述\",\"C\":\" 处理结果的描述\",\"D\":\" 检测方式的描述\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在第三代语言的应用中，人们发现的新的\"瓶颈\"是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283314,
                "Body": "{\"A\":\" 从研究水平看，外国与中国相当，从应用水平看，外国与中国相当\",\"B\":\" 从研究水平看，外国比中国高，从应用水平看，外国比中国低\",\"C\":\" 从研究水平看，外国比中国高，从应用水平看，外国比中国高\",\"D\":\" 从研究水平看，外国与中国相当，从应用水平看，外国比中国高\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "目前中外软件开发工具发展水平为 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283309,
                "Body": "{\"A\":\" 各工作阶段的预期进度、实际进展情况、验收情况\",\"B\":\" 各工作阶段的资源配置情况\",\"C\":\" 各工作阶段的经费使用情况\",\"D\":\" 各工作阶段的人员状况\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目数据库的一项重要内容是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283281,
                "Body": "{\"A\":\" 需求有什么变更\",\"B\":\" 环境有什么变更\",\"C\":\" 程序有什么变更\",\"D\":\" 人员有什么变更\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下各项中，不属于项目管理的内容的是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283297,
                "Body": "{\"A\":\" 数据字典\",\"B\":\" 框图\",\"C\":\" 程序代码\",\"D\":\" 变量说明\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的成果不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283283,
                "Body": "{\"A\":\" 在正确处理好质量、进度、资源配置和费用这四个问题的基础上提出的方法\",\"B\":\" 人们依据项目管理的经验，提出了以数据库为中心进行项目管理的方法\",\"C\":\" 项目数据库实际上是信息库的一个组成部分，它记录的是项目本身进展的各种有关信息\",\"D\":\" 根据严格的规定进行的一种管理方式\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在以下有关项目管理的方法的叙述中，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283252,
                "Body": "{\"A\":\" 运行环境\",\"B\":\" 性能/价格比\",\"C\":\" 用户的编程能力\",\"D\":\" 对应的开发方法\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是选择软件开发工具的要点（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283312,
                "Body": "{\"A\":\" 用户\",\"B\":\" 项目负责人\",\"C\":\" 程序员\",\"D\":\" 硬件\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "应承担验收模块任务的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283258,
                "Body": "{\"A\":\" Rational公司的Rose\",\"B\":\" ORACLE的CASE\",\"C\":\" INFOMAX的New Era\",\"D\":\" IBM的VisualAge\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "侧重于分析方法的、独立于平台的工具有（）",
                "Answer": "A",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283295,
                "Body": "{\"A\":\" 软件维护人员\",\"B\":\" 程序员\",\"C\":\" 软件分析设计人员\",\"D\":\" 软件用户\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中，有关系统环境、现状及需求的信息是由（）提出的。",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283288,
                "Body": "{\"A\":\" 软件的定义\",\"B\":\" 测试的问题\",\"C\":\" 工作进度的控制\",\"D\":\" 文档与代码的协调\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是大型软件开发过程中可能遇到的困难（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283284,
                "Body": "{\"A\":\" 第一代\",\"B\":\" 第二代\",\"C\":\" 第三代\",\"D\":\" 第四代\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具是以第几代语言为基础的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283211,
                "Body": "{\"A\":\"具体工作条件与软件开发工具的开发与选择无关\",\"B\":\"选择软件开发工具与项目特征无关\",\"C\":\"只要确定了某种软件开发工具，就能够进行软件开发工作了\",\"D\":\"自行开发软件开发工具时，应充分考虑其难度\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的开发与选择问题，下列选项中正确的是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283300,
                "Body": "{\"A\":\" 机器语言\",\"B\":\" 汇编语言\",\"C\":\" 高级语言\",\"D\":\" 非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "从概念上说，软件开发工具产生的基础是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283304,
                "Body": "{\"A\":\" 需求分析阶段\",\"B\":\" 设计阶段\",\"C\":\" 编码阶段\",\"D\":\" 维护阶段\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发过程的第一阶段是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283262,
                "Body": "{\"A\":\" 明确目的与要求\",\"B\":\" 明确环境以及制约条件\",\"C\":\" 市场调查，综合比较，测试检验\",\"D\":\" 用户评价\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于选购软件开发工具的方法与步骤的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283212,
                "Body": "{\"A\":\"软件开发工具供应商的规模\",\"B\":\"软件开发工具的管理者\",\"C\":\"软件开发工具的销售量\",\"D\":\"软件开发工具的服务和培训条件\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在对市场上可供使用的软件开发工具进行调查研究时，应包括的内容是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283213,
                "Body": "{\"A\":\"处理需求的描述 \",\"B\":\"处理过程的描述\",\"C\":\"处理结果的描述 \",\"D\":\"检测方式的描述\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在第三代语言的应用中，人们发现了新的“瓶颈”是（　　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283322,
                "Body": "{\"A\":\" 计划工具\",\"B\":\" 分析工具\",\"C\":\" 设计工具\",\"D\":\" 管理工具\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帮助人们绘制数据流程图、系统结构图、ER图的工具属于（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283316,
                "Body": "{\"A\":\" 质量控制\",\"B\":\" 成本管理\",\"C\":\" 资源管理\",\"D\":\" 版本更新\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "与一般工程的项目管理相比，软件开发的项目管理具有（）的问题，而一般工程的项目管\n理一般不具有该问题。",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283267,
                "Body": "{\"A\":\" 一致性\",\"B\":\" 周期性\",\"C\":\" 开放性\",\"D\":\" 准确性\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具在技术上的三个要点是面向使用者、保证信息的准确传递和保证系统的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283279,
                "Body": "{\"A\":\" B公司的D/ycle给出了集成软件开发环境的理论框架\",\"B\":\" 软件开发工具对环境的要求不应当低于它所支持的应用软件的环境要求\",\"C\":\" 集成化的软件开发工具对环境的要求比单项工具的要求高\",\"D\":\" 软件开发工具的环境要求应尽量降低，以利于广泛应用\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发环境的叙述，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283261,
                "Body": "{\"A\":\" 系统状况\",\"B\":\" 设计成果\",\"C\":\" 运行状况\",\"D\":\" 项目版本信息\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析阶段收集的信息是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283325,
                "Body": "{\"A\":\" 计算机的灵魂\",\"B\":\" 用户与开发者之间的桥梁\",\"C\":\" 人类互相联系的纽带\",\"D\":\" 人类在各个领域中积累的知识的结晶\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列对软件的定义不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283256,
                "Body": "{\"A\":\" 创建扩展点\",\"B\":\" 构造模型\",\"C\":\" 创建编辑器扩展点\",\"D\":\" 创建透视图扩展点\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列属于用EMF创建一个应用的步骤的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283330,
                "Body": "{\"A\":\" 帮助人们存储及管理各种信息\",\"B\":\" 工具的描述或表达能力\",\"C\":\" 帮助人们进行项目与版本管理\",\"D\":\" 帮助人们编写文档\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具最重要的性能是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283324,
                "Body": "{\"A\":\" 功能与性能是否先进\",\"B\":\" 功能与性能是否达到设计目标\",\"C\":\" 文档是否齐全\",\"D\":\" 文档与程序是否一致\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件测试的要求不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283293,
                "Body": "{\"A\":\" 程序语句与机器指令一一对应\",\"B\":\" 算术表达式接近于人的书写形式\",\"C\":\" 执行前需要用编译(或解释)程序来翻译\",\"D\":\" 实现了对机器的独立性\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于第三代程序设计语言的特点的说法，错误的是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283177,
                "Body": "{\"A\":\"市场调查                    \",\"B\":\"明确环境与约束条件  \",\"C\":\"明确目的与要求              \",\"D\":\"价格\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "选购软件开发工具首先应考虑的是(    )",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 283223,
                "Body": "{\"A\":\"设计出在计算机系统内外的、合理的信息流程\",\"B\":\"写出软件功能说明书        \",\"C\":\"软件结构设计\",\"D\":\"数据库设计        \",\"E\":\"程序设计\"}",
                "FileList": null,
                "MyAnswer": "C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于总体设计阶段工作的有（　　　　　）",
                "Answer": "C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283238,
                "Body": "{\"A\":\"报表生成器 \",\"B\":\"集成的软件开发环境\",\"C\":\"防病毒软件 \",\"D\":\"数据字典管理系统\",\"E\":\"游戏软件\"}",
                "FileList": null,
                "MyAnswer": "A,B,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下软件属于软件开发工具范围的有（　　　   ）",
                "Answer": "A,B,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283226,
                "Body": "{\"A\":\"顺序机制 \",\"B\":\"处理单元\",\"C\":\"循环机制 \",\"D\":\"二分决策机制\",\"E\":\"多分支机制\"}",
                "FileList": null,
                "MyAnswer": "B,C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "程序结构的基本模块有（　　　　　）",
                "Answer": "B,C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283239,
                "Body": "{\"A\":\"编辑与绘图 \",\"B\":\"指点与卡嗒\",\"C\":\"删剪与粘贴 \",\"D\":\"显示与打印\",\"E\":\"拖拉与扔下\"}",
                "FileList": null,
                "MyAnswer": "B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在可视化程序设计中，运用的技术手段包括（　　　   ）",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283218,
                "Body": "{\"A\":\"人员更变 \",\"B\":\"资金投入\",\"C\":\"进度计划 \",\"D\":\"实施情况       \",\"E\":\"版本信息\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在信息库中，项目管理的有关信息包括（　　　　　）",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283241,
                "Body": "{\"A\":\"键盘操作 \",\"B\":\"鼠标操作\",\"C\":\"数据录入 \",\"D\":\"资源分配\",\"E\":\"帮助系统\"}",
                "FileList": null,
                "MyAnswer": "A,B,E,C",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在SAA的用户界面中，包括的内容有（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283237,
                "Body": "{\"A\":\"明确需求 \",\"B\":\"提高编程效率\",\"C\":\"完善文档 \",\"D\":\"维修硬件\",\"E\":\"加强项目管理\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具能够帮助开发人员（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283244,
                "Body": "{\"A\":\"系统状况 \",\"B\":\"软、硬件资源的特点\",\"C\":\"系统设计成果 \",\"D\":\"运行与测试状况记录\",\"E\":\"项目管理与版本管理信息\"}",
                "FileList": null,
                "MyAnswer": "A,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在信息库（Repository）中应存放的信息有（　　　   ）",
                "Answer": "A,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283189,
                "Body": "{\"A\":\"代码生成                \",\"B\":\"文档生成                \",\"C\":\"功能设计  \",\"D\":\"总体结构                \",\"E\":\"信息库管理\"}",
                "FileList": null,
                "MyAnswer": "C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具的设计中，首先要考虑的问题是(       )",
                "Answer": "C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283222,
                "Body": "{\"A\":\"控制软件的使用 \",\"B\":\"控制软件的修改\",\"C\":\"减少混乱 \",\"D\":\"提高软件使用率        \",\"E\":\"提高软件生产率\"}",
                "FileList": null,
                "MyAnswer": "B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于软件配置管理目的的有（　　　　　）",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": 1
            }
        ]
    }
]