var topic1_2_07169 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "topic1_2_07169单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 283209,
                "Body": "{\"A\":\"需求分析阶段 \",\"B\":\"编码阶段\",\"C\":\"分析设计阶段 \",\"D\":\"测试阶段\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中，建立逻辑模型应在（　　　）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283261,
                "Body": "{\"A\":\" 系统状况\",\"B\":\" 设计成果\",\"C\":\" 运行状况\",\"D\":\" 项目版本信息\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析阶段收集的信息是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283345,
                "Body": "{\"A\":\" 把软件开发工作延伸到项目及版本管理\",\"B\":\" 没有超出一次编程的局限\",\"C\":\" 明确地把需求分析包括在软件工作的范围之内\",\"D\":\" 自动化程度的提高\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下有关软件开发工具新阶段的特点的描述，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283250,
                "Body": "{\"A\":\" 速度快\",\"B\":\" 占内存少\",\"C\":\" 输出界面美观\",\"D\":\" 可靠性高\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对于查询系统，除功能正确、用户界面友好外，考虑的首要因素是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283325,
                "Body": "{\"A\":\" 计算机的灵魂\",\"B\":\" 用户与开发者之间的桥梁\",\"C\":\" 人类互相联系的纽带\",\"D\":\" 人类在各个领域中积累的知识的结晶\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列对软件的定义不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283262,
                "Body": "{\"A\":\" 明确目的与要求\",\"B\":\" 明确环境以及制约条件\",\"C\":\" 市场调查，综合比较，测试检验\",\"D\":\" 用户评价\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于选购软件开发工具的方法与步骤的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283211,
                "Body": "{\"A\":\"具体工作条件与软件开发工具的开发与选择无关\",\"B\":\"选择软件开发工具与项目特征无关\",\"C\":\"只要确定了某种软件开发工具，就能够进行软件开发工作了\",\"D\":\"自行开发软件开发工具时，应充分考虑其难度\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的开发与选择问题，下列选项中正确的是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283283,
                "Body": "{\"A\":\" 在正确处理好质量、进度、资源配置和费用这四个问题的基础上提出的方法\",\"B\":\" 人们依据项目管理的经验，提出了以数据库为中心进行项目管理的方法\",\"C\":\" 项目数据库实际上是信息库的一个组成部分，它记录的是项目本身进展的各种有关信息\",\"D\":\" 根据严格的规定进行的一种管理方式\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在以下有关项目管理的方法的叙述中，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283227,
                "Body": "{\"A\":\"汇编语言 \",\"B\":\"机器语言\",\"C\":\"过程化语言 \",\"D\":\"非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第三代程序设计语言属于（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283186,
                "Body": "{\"A\":\"用户          \",\"B\":\"项目负责人        \",\"C\":\"程序员       \",\"D\":\"计算机\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构化程序设计方法是为(    )服务的。",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283213,
                "Body": "{\"A\":\"处理需求的描述 \",\"B\":\"处理过程的描述\",\"C\":\"处理结果的描述 \",\"D\":\"检测方式的描述\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在第三代语言的应用中，人们发现了新的“瓶颈”是（　　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283265,
                "Body": "{\"A\":\"ORACLE\",\"B\":\"IBM\",\"C\":\"INFOMAX\",\"D\":\"HP\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "VisualAge属于哪个公司（）",
                "Answer": "B",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283290,
                "Body": "{\"A\":\" 软件的管理\",\"B\":\" 资源的管理\",\"C\":\" 跨生命周期的信息的管理\",\"D\":\" 使用人员的管理\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理和版本管理的核心问题是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283214,
                "Body": "{\"A\":\"通常情况下，用通用软件进行软件开发工作要比使用软件开发工具开发软件效率高\",\"B\":\"使用通用软件开发软件能够完成几乎所有的开发工作\",\"C\":\"使用通用软件常常遇到难于保持一致性的困难\",\"D\":\"通用软件能够自动生成非常高质量的程序\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下述对通用软件特点叙述正确的是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283295,
                "Body": "{\"A\":\" 软件维护人员\",\"B\":\" 程序员\",\"C\":\" 软件分析设计人员\",\"D\":\" 软件用户\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中，有关系统环境、现状及需求的信息是由（）提出的。",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283208,
                "Body": "{\"A\":\"时序网络 \",\"B\":\"计算机模拟模型\",\"C\":\"结构图 \",\"D\":\"数学与逻辑模型\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发工具的概念模式中，决策表属于的概念模式是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283275,
                "Body": "{\"A\":\" 运行越快越好\",\"B\":\" 程序越短越好\",\"C\":\" 占用内存越少越好\",\"D\":\" 用户界面友好\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "近年来对质量好的软件的评判标准有 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283282,
                "Body": "{\"A\":\" 编译人员\",\"B\":\" 测试人员\",\"C\":\" 程序员\",\"D\":\" 资料员\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中需要很多人员的共同参与，以下不属于软件开发人员的是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283267,
                "Body": "{\"A\":\" 一致性\",\"B\":\" 周期性\",\"C\":\" 开放性\",\"D\":\" 准确性\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具在技术上的三个要点是面向使用者、保证信息的准确传递和保证系统的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283210,
                "Body": "{\"A\":\"应用程序对象 \",\"B\":\"菜单对象\",\"C\":\"数据窗口对象 \",\"D\":\"用户对象\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在PowerBuilder中，提供以自由表形式显示数据的是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283336,
                "Body": "{\"A\":\" 面向过程的程序设计方法\",\"B\":\" 软件工程方法\",\"C\":\" 面向对象的程序设计方法\",\"D\":\" 即插即用的程序设计方法\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是人们为了克服软件危机而提出的软件开发方法（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283334,
                "Body": "{\"A\":\" 全体成员切实遵守严格的工作规范和文档标准\",\"B\":\" 人员之间有严格的分工\",\"C\":\" 每一个项目完成之后都有完整的资料，并得到妥善保存\",\"D\":\" 没有严格按照事先制定的时间表进行开发工作\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一个好的项目组，应具备的条件中不包括（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283256,
                "Body": "{\"A\":\" 创建扩展点\",\"B\":\" 构造模型\",\"C\":\" 创建编辑器扩展点\",\"D\":\" 创建透视图扩展点\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列属于用EMF创建一个应用的步骤的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283338,
                "Body": "{\"A\":\"CASE\",\"B\":\"VisualAge\",\"C\":\"Rose\",\"D\":\"ADPS\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列软件中哪个是Rational公司的（）",
                "Answer": "C",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283303,
                "Body": "{\"A\":\" 认知科学中关于概念模式的概念与方法\",\"B\":\" 数据库技术的理论和方法\",\"C\":\" 存储技术的有关方法\",\"D\":\" 管理科学中关于项目管理和版本管理的理论和方法\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具用到的理论和方法不包括（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283178,
                "Body": "{\"A\":\"非常适用的                  \",\"B\":\"用途十分明确的  \",\"C\":\"使用方法精巧、复杂的        \",\"D\":\"文档理论性很强的\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一般而言(    )软件开发工具我们更倾向于购置。",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283252,
                "Body": "{\"A\":\" 运行环境\",\"B\":\" 性能/价格比\",\"C\":\" 用户的编程能力\",\"D\":\" 对应的开发方法\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是选择软件开发工具的要点（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283236,
                "Body": "{\"A\":\"操作系统 \",\"B\":\"数据库管理系统\",\"C\":\"高级语言 \",\"D\":\"软件开发工具\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对应用领域的特点依赖最多的软件是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283212,
                "Body": "{\"A\":\"软件开发工具供应商的规模\",\"B\":\"软件开发工具的管理者\",\"C\":\"软件开发工具的销售量\",\"D\":\"软件开发工具的服务和培训条件\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在对市场上可供使用的软件开发工具进行调查研究时，应包括的内容是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283312,
                "Body": "{\"A\":\" 用户\",\"B\":\" 项目负责人\",\"C\":\" 程序员\",\"D\":\" 硬件\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "应承担验收模块任务的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283184,
                "Body": "{\"A\":\"与它所支持的应用软件的环境要求无关  \",\"B\":\"依赖于它所支持的应用软件的环境要求  \",\"C\":\"应当超出它所支持的应用软件的环境要求  \",\"D\":\"不应当超出它所支持的应用软件的环境要求\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一般来说，软件开发工具对环境的要求(    )",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283234,
                "Body": "{\"A\":\"充分了解用户需求 \",\"B\":\"制定发展规划\",\"C\":\"建立逻辑模型 \",\"D\":\"完成系统总体设计\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "AD/Cycle中的需求分析阶段的任务是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283333,
                "Body": "{\"A\":\" 插入功能\",\"B\":\" 修改功能\",\"C\":\" 删除功能(让出空间)\",\"D\":\" 实现定量信息与文字信息的协调一致\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "信息库管理应当具备的功能不包括（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283317,
                "Body": "{\"A\":\" 总控部分与人机界面\",\"B\":\" 信息库及其管理模块\",\"C\":\" 文档生成和代码生成模块\",\"D\":\" 非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具的结构比较广泛，以下各项中不是它的结构的是 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283343,
                "Body": "{\"A\":\" 信息库中关于应用领域与环境的信息是需求分析阶段收集的信息\",\"B\":\" 信息库中关于应用领域与环境的信息是分析设计阶段工作的依据\",\"C\":\" 信息库中关于应用领域与环境的信息不是分析设计阶段所需的原始材料\",\"D\":\" 信息库中关于应用领域与环境的信息包括应用领域对软件的要求\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列说法不正确的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283327,
                "Body": "{\"A\":\" 数据库查询\",\"B\":\" 生成器\",\"C\":\" 通信服务\",\"D\":\" 数据安全控制\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列属于SAA对外系统的通信接口的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283185,
                "Body": "{\"A\":\"软件开发工具中的一类              \",\"B\":\"软件开发工具的全部  \",\"C\":\"不是软件开发工具                  \",\"D\":\"过程语言\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第四代语言可以被看作(    )",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283297,
                "Body": "{\"A\":\" 数据字典\",\"B\":\" 框图\",\"C\":\" 程序代码\",\"D\":\" 变量说明\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的成果不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283228,
                "Body": "{\"A\":\"支持软件开发的通用软件 \",\"B\":\"支持软件开发全过程的集成软件\",\"C\":\"支持某一阶段工作的专用软件 \",\"D\":\"操作系统\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "集成的软件开发环境是指（　　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283324,
                "Body": "{\"A\":\" 功能与性能是否先进\",\"B\":\" 功能与性能是否达到设计目标\",\"C\":\" 文档是否齐全\",\"D\":\" 文档与程序是否一致\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件测试的要求不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 283187,
                "Body": "{\"A\":\"对软件修改进行标识      \",\"B\":\"对软件修改进行控制      \",\"C\":\"协调整个系统过程  \",\"D\":\"控制整个系统过程        \",\"E\":\"只能保持一个版本\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件配置管理能够(       )",
                "Answer": "A,B,C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283224,
                "Body": "{\"A\":\"程序设计自动化程序提高\",\"B\":\"把软件开发工作延伸到项目及版本管理\",\"C\":\"把软件开发工作扩展到了作为一个不断发展的主体生长完善的全过程\",\"D\":\"软件生产的成败更多地依赖于编程技术\",\"E\":\"进一步削弱了用户在软件开发中的作用\"}",
                "FileList": null,
                "MyAnswer": "A,B",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下述体现软件开发工具发展的有（　　　　　）",
                "Answer": "A,B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283193,
                "Body": "{\"A\":\"认识与描述客观系统             \",\"B\":\"存储及管理开发过程中的信息  \",\"C\":\"为挑选管理人员提供必要信息     \",\"D\":\"文档的编制或生成\",\"E\":\"软件项目的管理\"}",
                "FileList": null,
                "MyAnswer": "A,B,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具为如下几方面提供支持(       )",
                "Answer": "A,B,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283188,
                "Body": "{\"A\":\"硬件配置                \",\"B\":\"机房灯光                \",\"C\":\"机房空调  \",\"D\":\"网络通讯                \",\"E\":\"系统软件\"}",
                "FileList": null,
                "MyAnswer": "A,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发的工作环境包括(       )",
                "Answer": "A,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283194,
                "Body": "{\"A\":\"CAE工具                  \",\"B\":\"第四代语言            \",\"C\":\"可视化程序设计  \",\"D\":\"最终用户计算              \",\"E\":\"组件程序设计\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "与软件开发工具有关的概念、术语很多，如(       )",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283238,
                "Body": "{\"A\":\"报表生成器 \",\"B\":\"集成的软件开发环境\",\"C\":\"防病毒软件 \",\"D\":\"数据字典管理系统\",\"E\":\"游戏软件\"}",
                "FileList": null,
                "MyAnswer": "A,B,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下软件属于软件开发工具范围的有（　　　   ）",
                "Answer": "A,B,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283241,
                "Body": "{\"A\":\"键盘操作 \",\"B\":\"鼠标操作\",\"C\":\"数据录入 \",\"D\":\"资源分配\",\"E\":\"帮助系统\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在SAA的用户界面中，包括的内容有（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283222,
                "Body": "{\"A\":\"控制软件的使用 \",\"B\":\"控制软件的修改\",\"C\":\"减少混乱 \",\"D\":\"提高软件使用率        \",\"E\":\"提高软件生产率\"}",
                "FileList": null,
                "MyAnswer": "B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于软件配置管理目的的有（　　　　　）",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283223,
                "Body": "{\"A\":\"设计出在计算机系统内外的、合理的信息流程\",\"B\":\"写出软件功能说明书        \",\"C\":\"软件结构设计\",\"D\":\"数据库设计        \",\"E\":\"程序设计\"}",
                "FileList": null,
                "MyAnswer": "C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于总体设计阶段工作的有（　　　　　）",
                "Answer": "C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283237,
                "Body": "{\"A\":\"明确需求 \",\"B\":\"提高编程效率\",\"C\":\"完善文档 \",\"D\":\"维修硬件\",\"E\":\"加强项目管理\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具能够帮助开发人员（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            }
        ]
    }
]