var topic3_1_07169 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "topic3_1_07169单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 283288,
                "Body": "{\"A\":\" 软件的定义\",\"B\":\" 测试的问题\",\"C\":\" 工作进度的控制\",\"D\":\" 文档与代码的协调\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是大型软件开发过程中可能遇到的困难（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283332,
                "Body": "{\"A\":\" 软件开发工具比所开发的软件简单\",\"B\":\" 软件开发工具的主要输出是信息库\",\"C\":\" 软件开发工具的主要优点是帮助人们节省时间，少做重复性工作\",\"D\":\" 当人们使用某种软件开发工具时，就已经接受了这种工具中所包含的对软件和软件开始工作的基本看法，默认了这种工具所依据的概念模式\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的叙述，正确的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283317,
                "Body": "{\"A\":\" 总控部分与人机界面\",\"B\":\" 信息库及其管理模块\",\"C\":\" 文档生成和代码生成模块\",\"D\":\" 非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具的结构比较广泛，以下各项中不是它的结构的是 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283256,
                "Body": "{\"A\":\" 创建扩展点\",\"B\":\" 构造模型\",\"C\":\" 创建编辑器扩展点\",\"D\":\" 创建透视图扩展点\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列属于用EMF创建一个应用的步骤的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283304,
                "Body": "{\"A\":\" 需求分析阶段\",\"B\":\" 设计阶段\",\"C\":\" 编码阶段\",\"D\":\" 维护阶段\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发过程的第一阶段是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283334,
                "Body": "{\"A\":\" 全体成员切实遵守严格的工作规范和文档标准\",\"B\":\" 人员之间有严格的分工\",\"C\":\" 每一个项目完成之后都有完整的资料，并得到妥善保存\",\"D\":\" 没有严格按照事先制定的时间表进行开发工作\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一个好的项目组，应具备的条件中不包括（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283281,
                "Body": "{\"A\":\" 需求有什么变更\",\"B\":\" 环境有什么变更\",\"C\":\" 程序有什么变更\",\"D\":\" 人员有什么变更\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下各项中，不属于项目管理的内容的是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283331,
                "Body": "{\"A\":\" 总控和人机界面\",\"B\":\" 信息库和信息库的管理\",\"C\":\" 代码生成和文档生成\",\"D\":\" 项目管理和版本管理\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需要进行跨生命周期信息管理的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283210,
                "Body": "{\"A\":\"应用程序对象 \",\"B\":\"菜单对象\",\"C\":\"数据窗口对象 \",\"D\":\"用户对象\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在PowerBuilder中，提供以自由表形式显示数据的是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283248,
                "Body": "{\"A\":\" 文件系统\",\"B\":\" 信息库\",\"C\":\" 数据库\",\"D\":\" 数据仓库\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的所有成果，一般应当存入（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283312,
                "Body": "{\"A\":\" 用户\",\"B\":\" 项目负责人\",\"C\":\" 程序员\",\"D\":\" 硬件\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "应承担验收模块任务的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283279,
                "Body": "{\"A\":\" B公司的D/ycle给出了集成软件开发环境的理论框架\",\"B\":\" 软件开发工具对环境的要求不应当低于它所支持的应用软件的环境要求\",\"C\":\" 集成化的软件开发工具对环境的要求比单项工具的要求高\",\"D\":\" 软件开发工具的环境要求应尽量降低，以利于广泛应用\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发环境的叙述，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283315,
                "Body": "{\"A\":\" 现在，软件的开发已彻底摆脱了手工作业的方式\",\"B\":\" 目前，不少商业软件开发工具已经问世，并在一定范围内得到应用\",\"C\":\" 目前，使用软件开发工具的实际成效还没有充分发挥出来，也有一系列实际问题与理论课题有待于研究解决\",\"D\":\" 只有对于软件开发中涉及的各种信息，以及在开发过程中它们的发生、变化、关系、一致性等有了完整与深刻的理解，才能真正实现软件开发工具的一体化\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的发展现状，叙述不正确的是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283258,
                "Body": "{\"A\":\" Rational公司的Rose\",\"B\":\" ORACLE的CASE\",\"C\":\" INFOMAX的New Era\",\"D\":\" IBM的VisualAge\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "侧重于分析方法的、独立于平台的工具有（）",
                "Answer": "A",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283338,
                "Body": "{\"A\":\"CASE\",\"B\":\"VisualAge\",\"C\":\"Rose\",\"D\":\"ADPS\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列软件中哪个是Rational公司的（）",
                "Answer": "C",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283314,
                "Body": "{\"A\":\" 从研究水平看，外国与中国相当，从应用水平看，外国与中国相当\",\"B\":\" 从研究水平看，外国比中国高，从应用水平看，外国比中国低\",\"C\":\" 从研究水平看，外国比中国高，从应用水平看，外国比中国高\",\"D\":\" 从研究水平看，外国与中国相当，从应用水平看，外国比中国高\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "目前中外软件开发工具发展水平为 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283214,
                "Body": "{\"A\":\"通常情况下，用通用软件进行软件开发工作要比使用软件开发工具开发软件效率高\",\"B\":\"使用通用软件开发软件能够完成几乎所有的开发工作\",\"C\":\"使用通用软件常常遇到难于保持一致性的困难\",\"D\":\"通用软件能够自动生成非常高质量的程序\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下述对通用软件特点叙述正确的是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283227,
                "Body": "{\"A\":\"汇编语言 \",\"B\":\"机器语言\",\"C\":\"过程化语言 \",\"D\":\"非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第三代程序设计语言属于（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283303,
                "Body": "{\"A\":\" 认知科学中关于概念模式的概念与方法\",\"B\":\" 数据库技术的理论和方法\",\"C\":\" 存储技术的有关方法\",\"D\":\" 管理科学中关于项目管理和版本管理的理论和方法\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具用到的理论和方法不包括（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283309,
                "Body": "{\"A\":\" 各工作阶段的预期进度、实际进展情况、验收情况\",\"B\":\" 各工作阶段的资源配置情况\",\"C\":\" 各工作阶段的经费使用情况\",\"D\":\" 各工作阶段的人员状况\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目数据库的一项重要内容是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283184,
                "Body": "{\"A\":\"与它所支持的应用软件的环境要求无关  \",\"B\":\"依赖于它所支持的应用软件的环境要求  \",\"C\":\"应当超出它所支持的应用软件的环境要求  \",\"D\":\"不应当超出它所支持的应用软件的环境要求\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一般来说，软件开发工具对环境的要求(    )",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283320,
                "Body": "{\"A\":\" 处理需求的描述\",\"B\":\" 处理过程的描述\",\"C\":\" 处理结果的描述\",\"D\":\" 检测方式的描述\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在第三代语言的应用中，人们发现的新的\"瓶颈\"是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283228,
                "Body": "{\"A\":\"支持软件开发的通用软件 \",\"B\":\"支持软件开发全过程的集成软件\",\"C\":\"支持某一阶段工作的专用软件 \",\"D\":\"操作系统\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "集成的软件开发环境是指（　　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283316,
                "Body": "{\"A\":\" 质量控制\",\"B\":\" 成本管理\",\"C\":\" 资源管理\",\"D\":\" 版本更新\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "与一般工程的项目管理相比，软件开发的项目管理具有（）的问题，而一般工程的项目管\n理一般不具有该问题。",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283295,
                "Body": "{\"A\":\" 软件维护人员\",\"B\":\" 程序员\",\"C\":\" 软件分析设计人员\",\"D\":\" 软件用户\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中，有关系统环境、现状及需求的信息是由（）提出的。",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283327,
                "Body": "{\"A\":\" 数据库查询\",\"B\":\" 生成器\",\"C\":\" 通信服务\",\"D\":\" 数据安全控制\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列属于SAA对外系统的通信接口的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283290,
                "Body": "{\"A\":\" 软件的管理\",\"B\":\" 资源的管理\",\"C\":\" 跨生命周期的信息的管理\",\"D\":\" 使用人员的管理\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理和版本管理的核心问题是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283345,
                "Body": "{\"A\":\" 把软件开发工作延伸到项目及版本管理\",\"B\":\" 没有超出一次编程的局限\",\"C\":\" 明确地把需求分析包括在软件工作的范围之内\",\"D\":\" 自动化程度的提高\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下有关软件开发工具新阶段的特点的描述，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283284,
                "Body": "{\"A\":\" 第一代\",\"B\":\" 第二代\",\"C\":\" 第三代\",\"D\":\" 第四代\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具是以第几代语言为基础的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283336,
                "Body": "{\"A\":\" 面向过程的程序设计方法\",\"B\":\" 软件工程方法\",\"C\":\" 面向对象的程序设计方法\",\"D\":\" 即插即用的程序设计方法\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是人们为了克服软件危机而提出的软件开发方法（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283333,
                "Body": "{\"A\":\" 插入功能\",\"B\":\" 修改功能\",\"C\":\" 删除功能(让出空间)\",\"D\":\" 实现定量信息与文字信息的协调一致\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "信息库管理应当具备的功能不包括（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283179,
                "Body": "{\"A\":\"逻辑模型      \",\"B\":\"数据结构设计      \",\"C\":\"总体设计     \",\"D\":\"处理过程设计\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "分析阶段的基本任务是完成系统的(    )",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283297,
                "Body": "{\"A\":\" 数据字典\",\"B\":\" 框图\",\"C\":\" 程序代码\",\"D\":\" 变量说明\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的成果不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283213,
                "Body": "{\"A\":\"处理需求的描述 \",\"B\":\"处理过程的描述\",\"C\":\"处理结果的描述 \",\"D\":\"检测方式的描述\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在第三代语言的应用中，人们发现了新的“瓶颈”是（　　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283211,
                "Body": "{\"A\":\"具体工作条件与软件开发工具的开发与选择无关\",\"B\":\"选择软件开发工具与项目特征无关\",\"C\":\"只要确定了某种软件开发工具，就能够进行软件开发工作了\",\"D\":\"自行开发软件开发工具时，应充分考虑其难度\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的开发与选择问题，下列选项中正确的是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283325,
                "Body": "{\"A\":\" 计算机的灵魂\",\"B\":\" 用户与开发者之间的桥梁\",\"C\":\" 人类互相联系的纽带\",\"D\":\" 人类在各个领域中积累的知识的结晶\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列对软件的定义不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283186,
                "Body": "{\"A\":\"用户          \",\"B\":\"项目负责人        \",\"C\":\"程序员       \",\"D\":\"计算机\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构化程序设计方法是为(    )服务的。",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283236,
                "Body": "{\"A\":\"操作系统 \",\"B\":\"数据库管理系统\",\"C\":\"高级语言 \",\"D\":\"软件开发工具\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对应用领域的特点依赖最多的软件是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283181,
                "Body": "{\"A\":\"有关系统环境、现状及需求的信息  \",\"B\":\"有关软件功能和物理设计的各种信息  \",\"C\":\"有关软件成果本身、包括程序和文档信息  \",\"D\":\"有关用户对系统的各种变更要求及系统变更记录的信息\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中由分析人员(或设计人员)根据需求分析形成了设计方案、设计方案依据哪一类信息?(    )",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283185,
                "Body": "{\"A\":\"软件开发工具中的一类              \",\"B\":\"软件开发工具的全部  \",\"C\":\"不是软件开发工具                  \",\"D\":\"过程语言\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第四代语言可以被看作(    )",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 283241,
                "Body": "{\"A\":\"键盘操作 \",\"B\":\"鼠标操作\",\"C\":\"数据录入 \",\"D\":\"资源分配\",\"E\":\"帮助系统\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在SAA的用户界面中，包括的内容有（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283237,
                "Body": "{\"A\":\"明确需求 \",\"B\":\"提高编程效率\",\"C\":\"完善文档 \",\"D\":\"维修硬件\",\"E\":\"加强项目管理\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具能够帮助开发人员（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283219,
                "Body": "{\"A\":\"窗口对象 \",\"B\":\"菜单对象\",\"C\":\"用户对象 \",\"D\":\"工程对象        \",\"E\":\"库\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "属于PowerBuilder中应用程序对象的有（　　　　　）",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283218,
                "Body": "{\"A\":\"人员更变 \",\"B\":\"资金投入\",\"C\":\"进度计划 \",\"D\":\"实施情况       \",\"E\":\"版本信息\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在信息库中，项目管理的有关信息包括（　　　　　）",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283222,
                "Body": "{\"A\":\"控制软件的使用 \",\"B\":\"控制软件的修改\",\"C\":\"减少混乱 \",\"D\":\"提高软件使用率        \",\"E\":\"提高软件生产率\"}",
                "FileList": null,
                "MyAnswer": "B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于软件配置管理目的的有（　　　　　）",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283187,
                "Body": "{\"A\":\"对软件修改进行标识      \",\"B\":\"对软件修改进行控制      \",\"C\":\"协调整个系统过程  \",\"D\":\"控制整个系统过程        \",\"E\":\"只能保持一个版本\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件配置管理能够(       )",
                "Answer": "A,B,C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283239,
                "Body": "{\"A\":\"编辑与绘图 \",\"B\":\"指点与卡嗒\",\"C\":\"删剪与粘贴 \",\"D\":\"显示与打印\",\"E\":\"拖拉与扔下\"}",
                "FileList": null,
                "MyAnswer": "B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在可视化程序设计中，运用的技术手段包括（　　　   ）",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283225,
                "Body": "{\"A\":\"一致性保持十分困难 \",\"B\":\"测试的困难很大\",\"C\":\"工作进程难于控制 \",\"D\":\"文档与代码的协调困难\",\"E\":\"版本更新困难\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "大型软件开发中的困难表现在（　　　　　）",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283193,
                "Body": "{\"A\":\"认识与描述客观系统             \",\"B\":\"存储及管理开发过程中的信息  \",\"C\":\"为挑选管理人员提供必要信息     \",\"D\":\"文档的编制或生成\",\"E\":\"软件项目的管理\"}",
                "FileList": null,
                "MyAnswer": "A,B,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具为如下几方面提供支持(       )",
                "Answer": "A,B,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283194,
                "Body": "{\"A\":\"CAE工具                  \",\"B\":\"第四代语言            \",\"C\":\"可视化程序设计  \",\"D\":\"最终用户计算              \",\"E\":\"组件程序设计\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "与软件开发工具有关的概念、术语很多，如(       )",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            }
        ]
    }
]