var topic3_2_07169 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "topic3_2_07169单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 283178,
                "Body": "{\"A\":\"非常适用的                  \",\"B\":\"用途十分明确的  \",\"C\":\"使用方法精巧、复杂的        \",\"D\":\"文档理论性很强的\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一般而言(    )软件开发工具我们更倾向于购置。",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283309,
                "Body": "{\"A\":\" 各工作阶段的预期进度、实际进展情况、验收情况\",\"B\":\" 各工作阶段的资源配置情况\",\"C\":\" 各工作阶段的经费使用情况\",\"D\":\" 各工作阶段的人员状况\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目数据库的一项重要内容是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283209,
                "Body": "{\"A\":\"需求分析阶段 \",\"B\":\"编码阶段\",\"C\":\"分析设计阶段 \",\"D\":\"测试阶段\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中，建立逻辑模型应在（　　　）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283228,
                "Body": "{\"A\":\"支持软件开发的通用软件 \",\"B\":\"支持软件开发全过程的集成软件\",\"C\":\"支持某一阶段工作的专用软件 \",\"D\":\"操作系统\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "集成的软件开发环境是指（　　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283341,
                "Body": "{\"A\":\" 程序的执行逻辑\",\"B\":\" 系统的模块结构\",\"C\":\" 系统的信息流程\",\"D\":\" 系统的静态数据结构\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构图描述的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283186,
                "Body": "{\"A\":\"用户          \",\"B\":\"项目负责人        \",\"C\":\"程序员       \",\"D\":\"计算机\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构化程序设计方法是为(    )服务的。",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283330,
                "Body": "{\"A\":\" 帮助人们存储及管理各种信息\",\"B\":\" 工具的描述或表达能力\",\"C\":\" 帮助人们进行项目与版本管理\",\"D\":\" 帮助人们编写文档\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具最重要的性能是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283320,
                "Body": "{\"A\":\" 处理需求的描述\",\"B\":\" 处理过程的描述\",\"C\":\" 处理结果的描述\",\"D\":\" 检测方式的描述\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在第三代语言的应用中，人们发现的新的\"瓶颈\"是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283325,
                "Body": "{\"A\":\" 计算机的灵魂\",\"B\":\" 用户与开发者之间的桥梁\",\"C\":\" 人类互相联系的纽带\",\"D\":\" 人类在各个领域中积累的知识的结晶\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列对软件的定义不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283210,
                "Body": "{\"A\":\"应用程序对象 \",\"B\":\"菜单对象\",\"C\":\"数据窗口对象 \",\"D\":\"用户对象\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在PowerBuilder中，提供以自由表形式显示数据的是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283227,
                "Body": "{\"A\":\"汇编语言 \",\"B\":\"机器语言\",\"C\":\"过程化语言 \",\"D\":\"非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第三代程序设计语言属于（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283262,
                "Body": "{\"A\":\" 明确目的与要求\",\"B\":\" 明确环境以及制约条件\",\"C\":\" 市场调查，综合比较，测试检验\",\"D\":\" 用户评价\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于选购软件开发工具的方法与步骤的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283343,
                "Body": "{\"A\":\" 信息库中关于应用领域与环境的信息是需求分析阶段收集的信息\",\"B\":\" 信息库中关于应用领域与环境的信息是分析设计阶段工作的依据\",\"C\":\" 信息库中关于应用领域与环境的信息不是分析设计阶段所需的原始材料\",\"D\":\" 信息库中关于应用领域与环境的信息包括应用领域对软件的要求\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列说法不正确的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283265,
                "Body": "{\"A\":\"ORACLE\",\"B\":\"IBM\",\"C\":\"INFOMAX\",\"D\":\"HP\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "VisualAge属于哪个公司（）",
                "Answer": "B",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283261,
                "Body": "{\"A\":\" 系统状况\",\"B\":\" 设计成果\",\"C\":\" 运行状况\",\"D\":\" 项目版本信息\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析阶段收集的信息是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283279,
                "Body": "{\"A\":\" B公司的D/ycle给出了集成软件开发环境的理论框架\",\"B\":\" 软件开发工具对环境的要求不应当低于它所支持的应用软件的环境要求\",\"C\":\" 集成化的软件开发工具对环境的要求比单项工具的要求高\",\"D\":\" 软件开发工具的环境要求应尽量降低，以利于广泛应用\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发环境的叙述，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283314,
                "Body": "{\"A\":\" 从研究水平看，外国与中国相当，从应用水平看，外国与中国相当\",\"B\":\" 从研究水平看，外国比中国高，从应用水平看，外国比中国低\",\"C\":\" 从研究水平看，外国比中国高，从应用水平看，外国比中国高\",\"D\":\" 从研究水平看，外国与中国相当，从应用水平看，外国比中国高\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "目前中外软件开发工具发展水平为 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283267,
                "Body": "{\"A\":\" 一致性\",\"B\":\" 周期性\",\"C\":\" 开放性\",\"D\":\" 准确性\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具在技术上的三个要点是面向使用者、保证信息的准确传递和保证系统的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283184,
                "Body": "{\"A\":\"与它所支持的应用软件的环境要求无关  \",\"B\":\"依赖于它所支持的应用软件的环境要求  \",\"C\":\"应当超出它所支持的应用软件的环境要求  \",\"D\":\"不应当超出它所支持的应用软件的环境要求\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一般来说，软件开发工具对环境的要求(    )",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283304,
                "Body": "{\"A\":\" 需求分析阶段\",\"B\":\" 设计阶段\",\"C\":\" 编码阶段\",\"D\":\" 维护阶段\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发过程的第一阶段是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283177,
                "Body": "{\"A\":\"市场调查                    \",\"B\":\"明确环境与约束条件  \",\"C\":\"明确目的与要求              \",\"D\":\"价格\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "选购软件开发工具首先应考虑的是(    )",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283181,
                "Body": "{\"A\":\"有关系统环境、现状及需求的信息  \",\"B\":\"有关软件功能和物理设计的各种信息  \",\"C\":\"有关软件成果本身、包括程序和文档信息  \",\"D\":\"有关用户对系统的各种变更要求及系统变更记录的信息\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中由分析人员(或设计人员)根据需求分析形成了设计方案、设计方案依据哪一类信息?(    )",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283336,
                "Body": "{\"A\":\" 面向过程的程序设计方法\",\"B\":\" 软件工程方法\",\"C\":\" 面向对象的程序设计方法\",\"D\":\" 即插即用的程序设计方法\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是人们为了克服软件危机而提出的软件开发方法（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283212,
                "Body": "{\"A\":\"软件开发工具供应商的规模\",\"B\":\"软件开发工具的管理者\",\"C\":\"软件开发工具的销售量\",\"D\":\"软件开发工具的服务和培训条件\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在对市场上可供使用的软件开发工具进行调查研究时，应包括的内容是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283332,
                "Body": "{\"A\":\" 软件开发工具比所开发的软件简单\",\"B\":\" 软件开发工具的主要输出是信息库\",\"C\":\" 软件开发工具的主要优点是帮助人们节省时间，少做重复性工作\",\"D\":\" 当人们使用某种软件开发工具时，就已经接受了这种工具中所包含的对软件和软件开始工作的基本看法，默认了这种工具所依据的概念模式\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的叙述，正确的是（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283345,
                "Body": "{\"A\":\" 把软件开发工作延伸到项目及版本管理\",\"B\":\" 没有超出一次编程的局限\",\"C\":\" 明确地把需求分析包括在软件工作的范围之内\",\"D\":\" 自动化程度的提高\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下有关软件开发工具新阶段的特点的描述，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283281,
                "Body": "{\"A\":\" 需求有什么变更\",\"B\":\" 环境有什么变更\",\"C\":\" 程序有什么变更\",\"D\":\" 人员有什么变更\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下各项中，不属于项目管理的内容的是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283328,
                "Body": "{\"A\":\" 选定硬件平台方面\",\"B\":\" 分析方面\",\"C\":\" 设计方面\",\"D\":\" 测试方面\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项软件开发工具不能为软件开发者所能提供帮助（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283236,
                "Body": "{\"A\":\"操作系统 \",\"B\":\"数据库管理系统\",\"C\":\"高级语言 \",\"D\":\"软件开发工具\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对应用领域的特点依赖最多的软件是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283284,
                "Body": "{\"A\":\" 第一代\",\"B\":\" 第二代\",\"C\":\" 第三代\",\"D\":\" 第四代\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具是以第几代语言为基础的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283292,
                "Body": "{\"A\":\" 限制OO语句的使用\",\"B\":\" 子程序只有一个入口和两个出口\",\"C\":\" 程序风格明确、清晰\",\"D\":\" 书写格式体现层次结构\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列不属于结构化程序设计在实施过程中强调的要点的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283288,
                "Body": "{\"A\":\" 软件的定义\",\"B\":\" 测试的问题\",\"C\":\" 工作进度的控制\",\"D\":\" 文档与代码的协调\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是大型软件开发过程中可能遇到的困难（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283297,
                "Body": "{\"A\":\" 数据字典\",\"B\":\" 框图\",\"C\":\" 程序代码\",\"D\":\" 变量说明\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的成果不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283322,
                "Body": "{\"A\":\" 计划工具\",\"B\":\" 分析工具\",\"C\":\" 设计工具\",\"D\":\" 管理工具\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帮助人们绘制数据流程图、系统结构图、ER图的工具属于（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283317,
                "Body": "{\"A\":\" 总控部分与人机界面\",\"B\":\" 信息库及其管理模块\",\"C\":\" 文档生成和代码生成模块\",\"D\":\" 非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具的结构比较广泛，以下各项中不是它的结构的是 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283334,
                "Body": "{\"A\":\" 全体成员切实遵守严格的工作规范和文档标准\",\"B\":\" 人员之间有严格的分工\",\"C\":\" 每一个项目完成之后都有完整的资料，并得到妥善保存\",\"D\":\" 没有严格按照事先制定的时间表进行开发工作\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一个好的项目组，应具备的条件中不包括（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283295,
                "Body": "{\"A\":\" 软件维护人员\",\"B\":\" 程序员\",\"C\":\" 软件分析设计人员\",\"D\":\" 软件用户\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中，有关系统环境、现状及需求的信息是由（）提出的。",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283266,
                "Body": "{\"A\":\" 减少了程序工作量\",\"B\":\" 增加了编程的麻烦\",\"C\":\" 降低了程序运行的效率\",\"D\":\" 提高了程序的可读性、可靠性、正确性\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构化程序设计的特点不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283338,
                "Body": "{\"A\":\"CASE\",\"B\":\"VisualAge\",\"C\":\"Rose\",\"D\":\"ADPS\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列软件中哪个是Rational公司的（）",
                "Answer": "C",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283333,
                "Body": "{\"A\":\" 插入功能\",\"B\":\" 修改功能\",\"C\":\" 删除功能(让出空间)\",\"D\":\" 实现定量信息与文字信息的协调一致\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "信息库管理应当具备的功能不包括（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 283191,
                "Body": "{\"A\":\"子任务多，关系复杂  \",\"B\":\"任务可以重复，形势稳定基本不变  \",\"C\":\"协调组织的任务十分突出，资源浪费闲置的风险与合理地优化组合、提高效益的机会并存  \",\"D\":\"信息集中，容易收集  \",\"E\":\"信息处理工作的作用和意义更为突出\"}",
                "FileList": null,
                "MyAnswer": "A,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目管理与日常生产管理相比，有许多突出的特点，如下列出的条目中，哪些是项目管理的特点?(       )",
                "Answer": "A,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283194,
                "Body": "{\"A\":\"CAE工具                  \",\"B\":\"第四代语言            \",\"C\":\"可视化程序设计  \",\"D\":\"最终用户计算              \",\"E\":\"组件程序设计\"}",
                "FileList": null,
                "MyAnswer": "A,C,B,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "与软件开发工具有关的概念、术语很多，如(       )",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283241,
                "Body": "{\"A\":\"键盘操作 \",\"B\":\"鼠标操作\",\"C\":\"数据录入 \",\"D\":\"资源分配\",\"E\":\"帮助系统\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在SAA的用户界面中，包括的内容有（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283196,
                "Body": "{\"A\":\" ++                      \",\"B\":\" IUA               \",\"C\":\" MLTL  \",\"D\":\" OB                  \",\"E\":\" O101\"}",
                "FileList": null,
                "MyAnswer": "D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "目前已有的软件组件标准有(       )",
                "Answer": "D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283239,
                "Body": "{\"A\":\"编辑与绘图 \",\"B\":\"指点与卡嗒\",\"C\":\"删剪与粘贴 \",\"D\":\"显示与打印\",\"E\":\"拖拉与扔下\"}",
                "FileList": null,
                "MyAnswer": "B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在可视化程序设计中，运用的技术手段包括（　　　   ）",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283244,
                "Body": "{\"A\":\"系统状况 \",\"B\":\"软、硬件资源的特点\",\"C\":\"系统设计成果 \",\"D\":\"运行与测试状况记录\",\"E\":\"项目管理与版本管理信息\"}",
                "FileList": null,
                "MyAnswer": "A,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在信息库（Repository）中应存放的信息有（　　　   ）",
                "Answer": "A,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283219,
                "Body": "{\"A\":\"窗口对象 \",\"B\":\"菜单对象\",\"C\":\"用户对象 \",\"D\":\"工程对象        \",\"E\":\"库\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "属于PowerBuilder中应用程序对象的有（　　　　　）",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283190,
                "Body": "{\"A\":\"信息入口                \",\"B\":\"信息出口                \",\"C\":\"信息管理  \",\"D\":\"调度中心                \",\"E\":\"程序代码产生点\"}",
                "FileList": null,
                "MyAnswer": "A,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "人机界面和总控模块是软件开发工具的(       )",
                "Answer": "A,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283242,
                "Body": "{\"A\":\"尽量提高产品的数量 \",\"B\":\"有效地控制产品的质量\",\"C\":\"保证安全，提高保密程度 \",\"D\":\"保证整个系统按预定的进度完成\",\"E\":\"合理利用各种资源，尽量减少资料浪费和闲置\"}",
                "FileList": null,
                "MyAnswer": "B,E,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "项目管理的基本目标有（　　　   ）",
                "Answer": "B,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283237,
                "Body": "{\"A\":\"明确需求 \",\"B\":\"提高编程效率\",\"C\":\"完善文档 \",\"D\":\"维修硬件\",\"E\":\"加强项目管理\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具能够帮助开发人员（　　　   ）",
                "Answer": "A,B,C,E",
                "Mark": "",
                "Judge": 1
            }
        ]
    }
]