var topic4_2_07169 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "topic4_2_07169单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 283293,
                "Body": "{\"A\":\" 程序语句与机器指令一一对应\",\"B\":\" 算术表达式接近于人的书写形式\",\"C\":\" 执行前需要用编译(或解释)程序来翻译\",\"D\":\" 实现了对机器的独立性\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于第三代程序设计语言的特点的说法，错误的是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283325,
                "Body": "{\"A\":\" 计算机的灵魂\",\"B\":\" 用户与开发者之间的桥梁\",\"C\":\" 人类互相联系的纽带\",\"D\":\" 人类在各个领域中积累的知识的结晶\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列对软件的定义不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283312,
                "Body": "{\"A\":\" 用户\",\"B\":\" 项目负责人\",\"C\":\" 程序员\",\"D\":\" 硬件\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "应承担验收模块任务的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283247,
                "Body": "{\"A\":\" 加快进度\",\"B\":\" 保证质量\",\"C\":\" 降低费用\",\"D\":\" 充分利用资源\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对于软件开发来说，项目管理的核心是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283324,
                "Body": "{\"A\":\" 功能与性能是否先进\",\"B\":\" 功能与性能是否达到设计目标\",\"C\":\" 文档是否齐全\",\"D\":\" 文档与程序是否一致\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件测试的要求不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283341,
                "Body": "{\"A\":\" 程序的执行逻辑\",\"B\":\" 系统的模块结构\",\"C\":\" 系统的信息流程\",\"D\":\" 系统的静态数据结构\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构图描述的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283227,
                "Body": "{\"A\":\"汇编语言 \",\"B\":\"机器语言\",\"C\":\"过程化语言 \",\"D\":\"非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第三代程序设计语言属于（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283252,
                "Body": "{\"A\":\" 运行环境\",\"B\":\" 性能/价格比\",\"C\":\" 用户的编程能力\",\"D\":\" 对应的开发方法\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪项不是选择软件开发工具的要点（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283178,
                "Body": "{\"A\":\"非常适用的                  \",\"B\":\"用途十分明确的  \",\"C\":\"使用方法精巧、复杂的        \",\"D\":\"文档理论性很强的\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一般而言(    )软件开发工具我们更倾向于购置。",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283265,
                "Body": "{\"A\":\"ORACLE\",\"B\":\"IBM\",\"C\":\"INFOMAX\",\"D\":\"HP\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "VisualAge属于哪个公司（）",
                "Answer": "B",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283258,
                "Body": "{\"A\":\" Rational公司的Rose\",\"B\":\" ORACLE的CASE\",\"C\":\" INFOMAX的New Era\",\"D\":\" IBM的VisualAge\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "侧重于分析方法的、独立于平台的工具有（）",
                "Answer": "A",
                "Mark": null,
                "Judge": 1
            },
            {
                "ID": 283292,
                "Body": "{\"A\":\" 限制OO语句的使用\",\"B\":\" 子程序只有一个入口和两个出口\",\"C\":\" 程序风格明确、清晰\",\"D\":\" 书写格式体现层次结构\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列不属于结构化程序设计在实施过程中强调的要点的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283186,
                "Body": "{\"A\":\"用户          \",\"B\":\"项目负责人        \",\"C\":\"程序员       \",\"D\":\"计算机\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构化程序设计方法是为(    )服务的。",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283279,
                "Body": "{\"A\":\" B公司的D/ycle给出了集成软件开发环境的理论框架\",\"B\":\" 软件开发工具对环境的要求不应当低于它所支持的应用软件的环境要求\",\"C\":\" 集成化的软件开发工具对环境的要求比单项工具的要求高\",\"D\":\" 软件开发工具的环境要求应尽量降低，以利于广泛应用\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发环境的叙述，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283212,
                "Body": "{\"A\":\"软件开发工具供应商的规模\",\"B\":\"软件开发工具的管理者\",\"C\":\"软件开发工具的销售量\",\"D\":\"软件开发工具的服务和培训条件\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在对市场上可供使用的软件开发工具进行调查研究时，应包括的内容是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283233,
                "Body": "{\"A\":\"全部改变 \",\"B\":\"少部分改变\",\"C\":\"大部分改变 \",\"D\":\"不发生改变\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "各个分散的软件工具在集成为一个一体化的工具时，它们的内部（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283185,
                "Body": "{\"A\":\"软件开发工具中的一类              \",\"B\":\"软件开发工具的全部  \",\"C\":\"不是软件开发工具                  \",\"D\":\"过程语言\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "第四代语言可以被看作(    )",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283300,
                "Body": "{\"A\":\" 机器语言\",\"B\":\" 汇编语言\",\"C\":\" 高级语言\",\"D\":\" 非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "从概念上说，软件开发工具产生的基础是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283248,
                "Body": "{\"A\":\" 文件系统\",\"B\":\" 信息库\",\"C\":\" 数据库\",\"D\":\" 数据仓库\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的所有成果，一般应当存入（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283297,
                "Body": "{\"A\":\" 数据字典\",\"B\":\" 框图\",\"C\":\" 程序代码\",\"D\":\" 变量说明\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "编程阶段的成果不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283261,
                "Body": "{\"A\":\" 系统状况\",\"B\":\" 设计成果\",\"C\":\" 运行状况\",\"D\":\" 项目版本信息\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "需求分析阶段收集的信息是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283317,
                "Body": "{\"A\":\" 总控部分与人机界面\",\"B\":\" 信息库及其管理模块\",\"C\":\" 文档生成和代码生成模块\",\"D\":\" 非过程化语言\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具的结构比较广泛，以下各项中不是它的结构的是 （）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283266,
                "Body": "{\"A\":\" 减少了程序工作量\",\"B\":\" 增加了编程的麻烦\",\"C\":\" 降低了程序运行的效率\",\"D\":\" 提高了程序的可读性、可靠性、正确性\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "结构化程序设计的特点不包括（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283177,
                "Body": "{\"A\":\"市场调查                    \",\"B\":\"明确环境与约束条件  \",\"C\":\"明确目的与要求              \",\"D\":\"价格\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "选购软件开发工具首先应考虑的是(    )",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283228,
                "Body": "{\"A\":\"支持软件开发的通用软件 \",\"B\":\"支持软件开发全过程的集成软件\",\"C\":\"支持某一阶段工作的专用软件 \",\"D\":\"操作系统\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "集成的软件开发环境是指（　　　）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283214,
                "Body": "{\"A\":\"通常情况下，用通用软件进行软件开发工作要比使用软件开发工具开发软件效率高\",\"B\":\"使用通用软件开发软件能够完成几乎所有的开发工作\",\"C\":\"使用通用软件常常遇到难于保持一致性的困难\",\"D\":\"通用软件能够自动生成非常高质量的程序\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下述对通用软件特点叙述正确的是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283320,
                "Body": "{\"A\":\" 处理需求的描述\",\"B\":\" 处理过程的描述\",\"C\":\" 处理结果的描述\",\"D\":\" 检测方式的描述\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在第三代语言的应用中，人们发现的新的\"瓶颈\"是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283256,
                "Body": "{\"A\":\" 创建扩展点\",\"B\":\" 构造模型\",\"C\":\" 创建编辑器扩展点\",\"D\":\" 创建透视图扩展点\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列属于用EMF创建一个应用的步骤的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283283,
                "Body": "{\"A\":\" 在正确处理好质量、进度、资源配置和费用这四个问题的基础上提出的方法\",\"B\":\" 人们依据项目管理的经验，提出了以数据库为中心进行项目管理的方法\",\"C\":\" 项目数据库实际上是信息库的一个组成部分，它记录的是项目本身进展的各种有关信息\",\"D\":\" 根据严格的规定进行的一种管理方式\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在以下有关项目管理的方法的叙述中，不正确的是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283343,
                "Body": "{\"A\":\" 信息库中关于应用领域与环境的信息是需求分析阶段收集的信息\",\"B\":\" 信息库中关于应用领域与环境的信息是分析设计阶段工作的依据\",\"C\":\" 信息库中关于应用领域与环境的信息不是分析设计阶段所需的原始材料\",\"D\":\" 信息库中关于应用领域与环境的信息包括应用领域对软件的要求\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列说法不正确的（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283333,
                "Body": "{\"A\":\" 插入功能\",\"B\":\" 修改功能\",\"C\":\" 删除功能(让出空间)\",\"D\":\" 实现定量信息与文字信息的协调一致\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "信息库管理应当具备的功能不包括（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283184,
                "Body": "{\"A\":\"与它所支持的应用软件的环境要求无关  \",\"B\":\"依赖于它所支持的应用软件的环境要求  \",\"C\":\"应当超出它所支持的应用软件的环境要求  \",\"D\":\"不应当超出它所支持的应用软件的环境要求\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "一般来说，软件开发工具对环境的要求(    )",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283290,
                "Body": "{\"A\":\" 软件的管理\",\"B\":\" 资源的管理\",\"C\":\" 跨生命周期的信息的管理\",\"D\":\" 使用人员的管理\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "项目管理和版本管理的核心问题是（）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283322,
                "Body": "{\"A\":\" 计划工具\",\"B\":\" 分析工具\",\"C\":\" 设计工具\",\"D\":\" 管理工具\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帮助人们绘制数据流程图、系统结构图、ER图的工具属于（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283210,
                "Body": "{\"A\":\"应用程序对象 \",\"B\":\"菜单对象\",\"C\":\"数据窗口对象 \",\"D\":\"用户对象\"}",
                "FileList": null,
                "MyAnswer": "C",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在PowerBuilder中，提供以自由表形式显示数据的是（　　　）",
                "Answer": "C",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283315,
                "Body": "{\"A\":\" 现在，软件的开发已彻底摆脱了手工作业的方式\",\"B\":\" 目前，不少商业软件开发工具已经问世，并在一定范围内得到应用\",\"C\":\" 目前，使用软件开发工具的实际成效还没有充分发挥出来，也有一系列实际问题与理论课题有待于研究解决\",\"D\":\" 只有对于软件开发中涉及的各种信息，以及在开发过程中它们的发生、变化、关系、一致性等有了完整与深刻的理解，才能真正实现软件开发工具的一体化\"}",
                "FileList": null,
                "MyAnswer": "A",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的发展现状，叙述不正确的是（）",
                "Answer": "A",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283295,
                "Body": "{\"A\":\" 软件维护人员\",\"B\":\" 程序员\",\"C\":\" 软件分析设计人员\",\"D\":\" 软件用户\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在软件开发过程中，有关系统环境、现状及需求的信息是由（）提出的。",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283211,
                "Body": "{\"A\":\"具体工作条件与软件开发工具的开发与选择无关\",\"B\":\"选择软件开发工具与项目特征无关\",\"C\":\"只要确定了某种软件开发工具，就能够进行软件开发工作了\",\"D\":\"自行开发软件开发工具时，应充分考虑其难度\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "关于软件开发工具的开发与选择问题，下列选项中正确的是（　　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283330,
                "Body": "{\"A\":\" 帮助人们存储及管理各种信息\",\"B\":\" 工具的描述或表达能力\",\"C\":\" 帮助人们进行项目与版本管理\",\"D\":\" 帮助人们编写文档\"}",
                "FileList": null,
                "MyAnswer": "B",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具最重要的性能是（）",
                "Answer": "B",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283318,
                "Body": "{\"A\":\" 设计工具、分析工具、计划工具\",\"B\":\" 专用工具和集成工具\",\"C\":\" 与软、硬件有关的和与软、硬件无关的工具\",\"D\":\" 以上全对\"}",
                "FileList": null,
                "MyAnswer": "D",
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "软件开发工具分为（）",
                "Answer": "D",
                "Mark": "",
                "Judge": 1
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5226,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 283223,
                "Body": "{\"A\":\"设计出在计算机系统内外的、合理的信息流程\",\"B\":\"写出软件功能说明书        \",\"C\":\"软件结构设计\",\"D\":\"数据库设计        \",\"E\":\"程序设计\"}",
                "FileList": null,
                "MyAnswer": "C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于总体设计阶段工作的有（　　　　　）",
                "Answer": "C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283222,
                "Body": "{\"A\":\"控制软件的使用 \",\"B\":\"控制软件的修改\",\"C\":\"减少混乱 \",\"D\":\"提高软件使用率        \",\"E\":\"提高软件生产率\"}",
                "FileList": null,
                "MyAnswer": "B,C,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下列属于软件配置管理目的的有（　　　　　）",
                "Answer": "B,C,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283225,
                "Body": "{\"A\":\"一致性保持十分困难 \",\"B\":\"测试的困难很大\",\"C\":\"工作进程难于控制 \",\"D\":\"文档与代码的协调困难\",\"E\":\"版本更新困难\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "大型软件开发中的困难表现在（　　　　　）",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283238,
                "Body": "{\"A\":\"报表生成器 \",\"B\":\"集成的软件开发环境\",\"C\":\"防病毒软件 \",\"D\":\"数据字典管理系统\",\"E\":\"游戏软件\"}",
                "FileList": null,
                "MyAnswer": "A,B,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下软件属于软件开发工具范围的有（　　　   ）",
                "Answer": "A,B,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283218,
                "Body": "{\"A\":\"人员更变 \",\"B\":\"资金投入\",\"C\":\"进度计划 \",\"D\":\"实施情况       \",\"E\":\"版本信息\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,E,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在信息库中，项目管理的有关信息包括（　　　　　）",
                "Answer": "A,B,C,D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283196,
                "Body": "{\"A\":\" ++                      \",\"B\":\" IUA               \",\"C\":\" MLTL  \",\"D\":\" OB                  \",\"E\":\" O101\"}",
                "FileList": null,
                "MyAnswer": "D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "目前已有的软件组件标准有(       )",
                "Answer": "D,E",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283189,
                "Body": "{\"A\":\"代码生成                \",\"B\":\"文档生成                \",\"C\":\"功能设计  \",\"D\":\"总体结构                \",\"E\":\"信息库管理\"}",
                "FileList": null,
                "MyAnswer": "C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件开发工具的设计中，首先要考虑的问题是(       )",
                "Answer": "C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283187,
                "Body": "{\"A\":\"对软件修改进行标识      \",\"B\":\"对软件修改进行控制      \",\"C\":\"协调整个系统过程  \",\"D\":\"控制整个系统过程        \",\"E\":\"只能保持一个版本\"}",
                "FileList": null,
                "MyAnswer": "A,B,C,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "软件配置管理能够(       )",
                "Answer": "A,B,C,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283190,
                "Body": "{\"A\":\"信息入口                \",\"B\":\"信息出口                \",\"C\":\"信息管理  \",\"D\":\"调度中心                \",\"E\":\"程序代码产生点\"}",
                "FileList": null,
                "MyAnswer": "A,D",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "人机界面和总控模块是软件开发工具的(       )",
                "Answer": "A,D",
                "Mark": "",
                "Judge": 1
            },
            {
                "ID": 283244,
                "Body": "{\"A\":\"系统状况 \",\"B\":\"软、硬件资源的特点\",\"C\":\"系统设计成果 \",\"D\":\"运行与测试状况记录\",\"E\":\"项目管理与版本管理信息\"}",
                "FileList": null,
                "MyAnswer": "A,C,D,E",
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在信息库（Repository）中应存放的信息有（　　　   ）",
                "Answer": "A,C,D,E",
                "Mark": "",
                "Judge": 1
            }
        ]
    }
]