var topic1_1_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic1_1_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 274804,
                "Body": "{\"A\":\"转发器\",\"B\":\"集线器\",\"C\":\"路由器\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "如果要将一个以太网与一个令牌环网相连，必须使用的网络设备是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274766,
                "Body": "{\"A\":\"从512bit/s到1bit/s\",\"B\":\"从144bit/s到8bit/s\",\"C\":\"从128bit/s到2bit/s\",\"D\":\"从64bit/s到52bit/s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率，其速度范围是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275410,
                "Body": "{\"A\":\"流量控制是数据链路层特有的功能(不是)\",\"B\":\"链路管理功能主要用于面向连接的服务  \",\"C\":\"差错控制是数据链路层的功能之一    \",\"D\":\"链路管理包括连接的建立、维持和释放\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于数据链路层功能的叙述中错误的",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275415,
                "Body": "{\"A\":\"\\t物理层\",\"B\":\"\\t数据链接层\",\"C\":\"\\t网络层\",\"D\":\"\\t传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继是继X.25之后发展起来的数据通信方式，但帧中继与X.25不同，其复用和转接发生在（）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275310,
                "Body": "{\"A\":\"路由划分    \",\"B\":\"按交换端口号划分    \",\"C\":\"按MAC地址划分    \",\"D\":\"按第三层协议划分\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列所述划分虚拟局域网的常用方法中错误的",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274466,
                "Body": "{\"A\":\"IP，ICMP，ARP，UDP\",\"B\":\"TCP，ICMP，UDP，ARP\",\"C\":\"IP，ICMP，ARP，RARP\",\"D\":\"UDP，IP，ICMP，RARP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP／IP的互连层含有四个重要的协议，分别为（　）",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275298,
                "Body": "{\"A\":\"字节计数法                    \",\"B\":\"比特填充的首尾标志法  \",\"C\":\"违法编码法                    \",\"D\":\"字符填充的首尾定界符法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网IEEE802标准中采用的帧同步方法是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275239,
                "Body": "{\"A\":\"\\t“存储——转发”式\",\"B\":\"\\t广播式\",\"C\":\"\\t电路交换式\",\"D\":\"\\t分散控制\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网LAN所采用的传输方式为",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274837,
                "Body": "{\"A\":\"30%\",\"B\":\"70%\",\"C\":\"80%\",\"D\":\"20%\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用异步传输方式，若数据位为7位，1位校验位，1位停止位，则其通信效率为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274885,
                "Body": "{\"A\":\"广播方式\",\"B\":\"多点访问方式\",\"C\":\"点到点方式\",\"D\":\"集中控制方式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网内的节点之间常采用的通信方式为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275281,
                "Body": "{\"A\":\"模拟传输\",\"B\":\"数字传输\",\"C\":\"模拟—数字混合传输\",\"D\":\"以上均不对\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在局域网中，由于距离近以及数字电路器件价格的下降，所以更具优越性的传输技术是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274717,
                "Body": "{\"A\":\"一种计算机网络的实现\",\"B\":\"执行计算机数据处理的软件模块\",\"C\":\"由S定义的一个标准\",\"D\":\"计算机网络各层次结构模型及其协议的集合\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络体系结构可以定义为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274881,
                "Body": "{\"A\":\"LAA\",\"B\":\"LAB\",\"C\":\"LAC\",\"D\":\"LAD\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继采用的链路接人规程为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274720,
                "Body": "{\"A\":\"L=l\",\"B\":\"L=2\",\"C\":\"L=4\",\"D\":\"L=8\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA/CD的二进制指数退避算法的规则之一是，对每个数据帧，当第一次发生冲突时，需要设置的一个参数量为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274763,
                "Body": "{\"A\":\"1层\",\"B\":\"1-2层\",\"C\":\"1-3层\",\"D\":\"1-4层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网技术主要对应OSI参考模型底层的（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275380,
                "Body": "{\"A\":\"CMIS\",\"B\":\"SNMP       \",\"C\":\"CMIP           \",\"D\":\"SMTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "基于TCP／IP协议簇的网络管理标准协议是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274477,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于光纤用户网的特点是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275407,
                "Body": "{\"A\":\"机械特性    \",\"B\":\"电器特性    \",\"C\":\"功能特性    \",\"D\":\"规程特性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "规定了接口信号的来源、作用以及与其它信号之间关系的物理层特性是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274733,
                "Body": "{\"A\":\"在Web服务器进行\",\"B\":\"在代理服务器上进行\",\"C\":\"在浏览器上进行\",\"D\":\"在ISP上进行\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>点击浏览器上的网页地址，该网页的HTML文件的解释执行（　）。</p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274559,
                "Body": "{\"A\":\"储存-转发\",\"B\":\"广播\",\"C\":\"点-点\",\"D\":\"异步传输\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网中信息从发送方传送到接收方采用的传输方式是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275158,
                "Body": "{\"A\":\"SLIP协议\",\"B\":\"PPP协议\",\"C\":\"SMTP协议\",\"D\":\"HTTP协议\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>浏览器访问Web服务器时的信息传输遵循（）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274730,
                "Body": "{\"A\":\"邮件服务器地址\",\"B\":\"字符形式的网页地址\",\"C\":\"字符形式的P地址\",\"D\":\"Web服务器地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet上的域名是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275302,
                "Body": "{\"A\":\"ARP\",\"B\":\"RARP\",\"C\":\"ICMP\",\"D\":\"FTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在TCP/IP环境下，网络层有一组协议将IP地址转换为相应物理网络地址，这组协议即是",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274615,
                "Body": "{\"A\":\"64字节\",\"B\":\"128字节\",\"C\":\"256字节\",\"D\":\"512字节\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "100Base—T快速以太网，为了能成功地进行冲突检测，其最短帧长应为（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274616,
                "Body": "{\"A\":\"IEE802.11\",\"B\":\"IEE802.11a\",\"C\":\"IEE802.11b\",\"D\":\"IEE802.11b+\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "若要求组建一个带宽能达到54Mbps的无线局域网时，选用的无线设备应支持的无线局域网标准是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274609,
                "Body": "{\"A\":\"1200bps\",\"B\":\"2400bps\",\"C\":\"3600bps\",\"D\":\"4800bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用一个码元取8种离散状态的移相键控PSK方法，若码元速率为1200波特，则可获得的数据传输速率为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274711,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"IP地址\",\"C\":\"域名地址\",\"D\":\"统一资源定位器（R）\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "WWW上的每一个网页包括主页都有一个独立的地址，这些地址由32位二进制表示则称为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274611,
                "Body": "{\"A\":\"分配IP地址\",\"B\":\"提供端到端的面向连接的可靠数据传输\",\"C\":\"确定数据传输路径\",\"D\":\"提高传输速度\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP协议的主要功能是（　）",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274620,
                "Body": "{\"A\":\"ADSL\",\"B\":\"RADSL\",\"C\":\"NDSL\",\"D\":\"VDSL\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>以下几项中不属于数字用户环路技术的是（　）</p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274578,
                "Body": "{\"A\":\"无线接入\",\"B\":\"租用高速通信线路\",\"C\":\"ADL拨号\",\"D\":\"传统电话拨号\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网服务供应商ISP接入因特网大多是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274571,
                "Body": "{\"A\":\"从512bit／s到1bit／s\",\"B\":\"从144bit／s到8bit／s\",\"C\":\"从128bit／s到2bit／s\",\"D\":\"从64bit／s到52bit／s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率。其范围是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274700,
                "Body": "{\"A\":\"经典以太网\",\"B\":\"百兆以太网\",\"C\":\"千兆以太网\",\"D\":\"万兆以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "不再支持半双工数据传输，所有传输都以全双工方式进行的以太网技术是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274714,
                "Body": "{\"A\":\"储存——转发\",\"B\":\"广播\",\"C\":\"一点——多点\",\"D\":\"异步传输\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网中信息从发送方传送到接收方采用的传输方式是（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274614,
                "Body": "{\"A\":\"信号传播时延\",\"B\":\"数据传输时延\",\"C\":\"冲突检测时间\",\"D\":\"数据接收时延\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据帧从一个站点开始发送，到该数据帧发送完毕所需的时间称为（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274627,
                "Body": "{\"A\":\"在整个因特网上是唯一的\",\"B\":\"在一个国家是唯一的\",\"C\":\"在用户所在邮件服务器中是唯一的\",\"D\":\"在同一网络标识的网上是唯一的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "用户E-mail地址中的用户名（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274618,
                "Body": "{\"A\":\"网络终端Tl\",\"B\":\"网络终端T2\",\"C\":\"网络终端Tl+T2\",\"D\":\"调制解调器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对于家庭和小型机构在用户设备和ISDN交换设备之间需要安装的设备是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274572,
                "Body": "{\"A\":\"上行数据流的传输速率大于下行数据流的传输速率\",\"B\":\"下行数据流的传输速率大于上行数据流的传输速率\",\"C\":\"传送上行数据的同时不可以打电话而传送下行数据时则可以\",\"D\":\"传送下行数据的同时不可以打电话而传送上行数据时则可以\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ADSL中的不对称指的是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274694,
                "Body": "{\"A\":\"3层\",\"B\":\"4层\",\"C\":\"5层\",\"D\":\"7层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "国际标准化组织ISO制定的开放系统互连基本参考模型共有（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274710,
                "Body": "{\"A\":\"为全0\",\"B\":\"为全1\",\"C\":\"相同\",\"D\":\"不同\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "若两台主机在同一子网中，则两台主机的IP地址分别与它们的子网掩码相“与”的结果一定（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]