var topic1_2_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic1_2_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 275298,
                "Body": "{\"A\":\"字节计数法                    \",\"B\":\"比特填充的首尾标志法  \",\"C\":\"违法编码法                    \",\"D\":\"字符填充的首尾定界符法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网IEEE802标准中采用的帧同步方法是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275384,
                "Body": "{\"A\":\"IEF    \",\"B\":\"IEE    \",\"C\":\"ECA    \",\"D\":\"ANI\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "负责管理与发布Internet RFC技术文件的组织是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275292,
                "Body": "{\"A\":\"\\tSN方式\",\"B\":\"\\t仿真终端方式\",\"C\":\"\\t局域网连接方式\",\"D\":\"\\t广域网连接方式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在Internet中，ISP的接入方式有帧中继方式、专线（DDN）方式及",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274804,
                "Body": "{\"A\":\"转发器\",\"B\":\"集线器\",\"C\":\"路由器\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "如果要将一个以太网与一个令牌环网相连，必须使用的网络设备是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274722,
                "Body": "{\"A\":\"集线器\",\"B\":\"网桥\",\"C\":\"交换机\",\"D\":\"路由器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "构建一个交换型100Base-T以太网，应选用的网络连接设备是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275380,
                "Body": "{\"A\":\"CMIS\",\"B\":\"SNMP       \",\"C\":\"CMIP           \",\"D\":\"SMTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "基于TCP／IP协议簇的网络管理标准协议是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274766,
                "Body": "{\"A\":\"从512bit/s到1bit/s\",\"B\":\"从144bit/s到8bit/s\",\"C\":\"从128bit/s到2bit/s\",\"D\":\"从64bit/s到52bit/s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率，其速度范围是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274730,
                "Body": "{\"A\":\"邮件服务器地址\",\"B\":\"字符形式的网页地址\",\"C\":\"字符形式的P地址\",\"D\":\"Web服务器地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet上的域名是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274718,
                "Body": "{\"A\":\"帧\",\"B\":\"位\",\"C\":\"分组\",\"D\":\"报文\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据链路层的协议数据单元称作（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274837,
                "Body": "{\"A\":\"30%\",\"B\":\"70%\",\"C\":\"80%\",\"D\":\"20%\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用异步传输方式，若数据位为7位，1位校验位，1位停止位，则其通信效率为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275143,
                "Body": "{\"A\":\"环形拓扑\",\"B\":\"树型结构\",\"C\":\"网形拓扑\",\"D\":\"总线拓扑\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在广域网得到了广泛应用、节点之间有许多条路径相连，这样的网络拓扑结构是<br><br>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274466,
                "Body": "{\"A\":\"IP，ICMP，ARP，UDP\",\"B\":\"TCP，ICMP，UDP，ARP\",\"C\":\"IP，ICMP，ARP，RARP\",\"D\":\"UDP，IP，ICMP，RARP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP／IP的互连层含有四个重要的协议，分别为（　）",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275239,
                "Body": "{\"A\":\"\\t“存储——转发”式\",\"B\":\"\\t广播式\",\"C\":\"\\t电路交换式\",\"D\":\"\\t分散控制\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网LAN所采用的传输方式为",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275379,
                "Body": "{\"A\":\"AT信元中信息段长度固定为53字节  \",\"B\":\"AT网络在信元交换前需建立虚拟连接  \",\"C\":\"AT网络不参与任何数据链路层的功能  \",\"D\":\"AT物理链路逻辑上分虚路径和虚通道\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于异步传输模式ATM的表述中错误的是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274857,
                "Body": "{\"A\":\"电路交换\",\"B\":\"报文交换\",\"C\":\"分组交换\",\"D\":\"信元交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在三种常用的数据交换技术中，线路利用率最低的是（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274719,
                "Body": "{\"A\":\"IP\",\"B\":\"TCP\",\"C\":\"FTP\",\"D\":\"UDP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP/IP协议簇中属于应用层协议的是（　）。",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274805,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用CSMA/CD协议，数据帧的传输时延至少要等于信号传播时延的（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275168,
                "Body": "{\"A\":\"计费管理\",\"B\":\"QOS管理\",\"C\":\"故障管理\",\"D\":\"性能管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>属于VPN管理内容的项是（）</p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274825,
                "Body": "{\"A\":\"链路层和网络层\",\"B\":\"物理层和网络层\",\"C\":\"网络层和传输层\",\"D\":\"物理层和链路层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术使用链路层实现复用和转接，所以帧中继网络的中间结点中只有（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274885,
                "Body": "{\"A\":\"广播方式\",\"B\":\"多点访问方式\",\"C\":\"点到点方式\",\"D\":\"集中控制方式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网内的节点之间常采用的通信方式为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274472,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274717,
                "Body": "{\"A\":\"一种计算机网络的实现\",\"B\":\"执行计算机数据处理的软件模块\",\"C\":\"由S定义的一个标准\",\"D\":\"计算机网络各层次结构模型及其协议的集合\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络体系结构可以定义为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275317,
                "Body": "{\"A\":\"4倍\",\"B\":\".3倍\",\"C\":\"2.5倍\",\"D\":\"2倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为了确保发送站点在传输时能检测到可能存在的冲突，CSMA／CD数据帧的传输时延至少要等于信号传输时延的()",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274559,
                "Body": "{\"A\":\"储存-转发\",\"B\":\"广播\",\"C\":\"点-点\",\"D\":\"异步传输\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网中信息从发送方传送到接收方采用的传输方式是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275407,
                "Body": "{\"A\":\"机械特性    \",\"B\":\"电器特性    \",\"C\":\"功能特性    \",\"D\":\"规程特性\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "规定了接口信号的来源、作用以及与其它信号之间关系的物理层特性是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274698,
                "Body": "{\"A\":\"分组丢弃法\",\"B\":\"缓冲区预分配法\",\"C\":\"定额控制法\",\"D\":\"存储转发法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在阻塞控制方法中，直接对通信子网中分组的数量进行严格、精确的限制，以防止阻塞现象发生的方法为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274609,
                "Body": "{\"A\":\"1200bps\",\"B\":\"2400bps\",\"C\":\"3600bps\",\"D\":\"4800bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用一个码元取8种离散状态的移相键控PSK方法，若码元速率为1200波特，则可获得的数据传输速率为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274701,
                "Body": "{\"A\":\"曼彻斯特编码\",\"B\":\"4B/5B\",\"C\":\"8B/10B\",\"D\":\"64B/66B\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>10GBase-R万兆以太网采用的编码方式是（　）。</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274695,
                "Body": "{\"A\":\"COE中的编码器\",\"B\":\"COE中的解码器\",\"C\":\"MOE中的调制器\",\"D\":\"MOE中的解调器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "模拟数据也可以用数字信号来表示。对于声音数据来说，完成将模拟数据转换为数字信号的设施为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274696,
                "Body": "{\"A\":\"IP，ICMP，ARP，UDP\",\"B\":\"TCP，ICMP，UDP，ARP\",\"C\":\"IP，ICMP，ARP，RARP\",\"D\":\"UDP，IP，ICMP，RARP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>TCP／IP的互连层含有四个重要的协议，分别为（　）。</p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274614,
                "Body": "{\"A\":\"信号传播时延\",\"B\":\"数据传输时延\",\"C\":\"冲突检测时间\",\"D\":\"数据接收时延\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据帧从一个站点开始发送，到该数据帧发送完毕所需的时间称为（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274626,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"网页地址\",\"C\":\"IP地址\",\"D\":\"物理地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列地址中与“域名”有一一对应关系的是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274573,
                "Body": "{\"A\":\"FTC\",\"B\":\"FTZ\",\"C\":\"FTO\",\"D\":\"FTF\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "光纤到办公室的用户网光纤化方案是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274577,
                "Body": "{\"A\":\"邮件服务器\",\"B\":\"域名系统(N)\",\"C\":\"统一资源定位器(R)\",\"D\":\"代理服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "E-mail地址格式为：用户名@主机域名，传送邮件时必须将主机域名转换成IP地址，实现该项转换工作的是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274624,
                "Body": "{\"A\":\"A类地址\",\"B\":\"B类地址\",\"C\":\"C类地址\",\"D\":\"广播地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址112.1.4.13属于（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274708,
                "Body": "{\"A\":\"被管代理\",\"B\":\"网络管理器\",\"C\":\"网络管理协议\",\"D\":\"管理信息库\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络管理系统中驻留在被管对象上配合网络管理的处理实体称为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274621,
                "Body": "{\"A\":\"拨号MODEM\",\"B\":\"ISDN(2B+D)\",\"C\":\"ADSL\",\"D\":\"光纤以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>在下列个人用户接入广域网技术中，传输速率最高的是（　）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274705,
                "Body": "{\"A\":\"中继器\",\"B\":\"滤波器\",\"C\":\"路由器\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ADSL使用的信号分离器又称为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274561,
                "Body": "{\"A\":\"每一层实现一种相对独立的功能\",\"B\":\"每一层都知道下面一层是如何实现的\",\"C\":\"每一层的功能相对简单且易于实现和维护\",\"D\":\"每一层不必知道下面一层是如何实现的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪一项错误地描述了网络体系结构中分层的特点（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597645,
                "Body": "{\n  \"A\": \"证券交易系统\",\n  \"B\": \"信息处理系统\",\n  \"C\": \"远程医疗\",\n  \"D\": \"电子图书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面()属于网络应用。",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]