var topic2_1_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic2_1_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 274531,
                "Body": "{\"A\":\"故障管理\",\"B\":\"客户管理\",\"C\":\"应用管理\",\"D\":\"运营管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISO建议网络管理的基本功能应包括计费管理、配置管理、性能管理、安全管理和（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274477,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于光纤用户网的特点是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275281,
                "Body": "{\"A\":\"模拟传输\",\"B\":\"数字传输\",\"C\":\"模拟—数字混合传输\",\"D\":\"以上均不对\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在局域网中，由于距离近以及数字电路器件价格的下降，所以更具优越性的传输技术是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275148,
                "Body": "{\"A\":\"数据链路层\",\"B\":\"网络层\",\"C\":\"传输层\",\"D\":\"应用层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "路由器是一种重要的网络互连设备，它所实现的网络互连层次属于<br><br>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275330,
                "Body": "{\"A\":\"802.6城域网技术\",\"B\":\"802.7广域网技术\",\"C\":\"802.8光纤技术\",\"D\":\"红外端口技术\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "目前，常用的无线接入技术主要有802.11无线局域网技术、蓝牙技术和 （　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274526,
                "Body": "{\"A\":\"LAA\",\"B\":\"LAC\",\"C\":\"LAD\",\"D\":\"LAE\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继中不采用HDLC的平衡链路接入规程LAPB，所采用的链路接入规程是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274875,
                "Body": "{\"A\":\"级别1\",\"B\":\"级别2\",\"C\":\"级别3\",\"D\":\"级别4\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "传输层的功能按级别划分，OSl定义了五种协议级别，其中能够提供差错检测，恢复即多路复用功能的级别是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275158,
                "Body": "{\"A\":\"SLIP协议\",\"B\":\"PPP协议\",\"C\":\"SMTP协议\",\"D\":\"HTTP协议\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>浏览器访问Web服务器时的信息传输遵循（）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275250,
                "Body": "{\"A\":\"局域式\",\"B\":\"集中型\",\"C\":\"发散型\",\"D\":\"分布式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "1974年最早推出的SNA主要适用于（　　）的面向终端的计算机网络",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274472,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274837,
                "Body": "{\"A\":\"30%\",\"B\":\"70%\",\"C\":\"80%\",\"D\":\"20%\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用异步传输方式，若数据位为7位，1位校验位，1位停止位，则其通信效率为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274718,
                "Body": "{\"A\":\"帧\",\"B\":\"位\",\"C\":\"分组\",\"D\":\"报文\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据链路层的协议数据单元称作（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274805,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用CSMA/CD协议，数据帧的传输时延至少要等于信号传播时延的（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275317,
                "Body": "{\"A\":\"4倍\",\"B\":\".3倍\",\"C\":\"2.5倍\",\"D\":\"2倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为了确保发送站点在传输时能检测到可能存在的冲突，CSMA／CD数据帧的传输时延至少要等于信号传输时延的()",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275255,
                "Body": "{\"A\":\"电话\",\"B\":\"卫星\",\"C\":\"光缆线\",\"D\":\"网络连接器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列不属于通信链路介质的是 （　　）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275302,
                "Body": "{\"A\":\"ARP\",\"B\":\"RARP\",\"C\":\"ICMP\",\"D\":\"FTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在TCP/IP环境下，网络层有一组协议将IP地址转换为相应物理网络地址，这组协议即是",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274885,
                "Body": "{\"A\":\"广播方式\",\"B\":\"多点访问方式\",\"C\":\"点到点方式\",\"D\":\"集中控制方式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网内的节点之间常采用的通信方式为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274857,
                "Body": "{\"A\":\"电路交换\",\"B\":\"报文交换\",\"C\":\"分组交换\",\"D\":\"信元交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在三种常用的数据交换技术中，线路利用率最低的是（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274522,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA／CD的代价是用于检测冲突所花费的时间。对于基带总线而言，最坏情况下用于检测一个冲突的时间等于任意两个站之间最大传播时延的（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275208,
                "Body": "{\"A\":\"IEEE802.3\",\"B\":\"IEEE802.4\",\"C\":\"IEEE802.5\",\"D\":\"JEEE802.11\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列IEEE标准中，属于无线局域网标准的是<br><br>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275170,
                "Body": "{\"A\":\"中继器\",\"B\":\"交换机\",\"C\":\"防火墙\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为增强Intranet的安全性，在被保护的Intranet与Internet之间竖起一道安全屏障称为（）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274722,
                "Body": "{\"A\":\"集线器\",\"B\":\"网桥\",\"C\":\"交换机\",\"D\":\"路由器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "构建一个交换型100Base-T以太网，应选用的网络连接设备是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274567,
                "Body": "{\"A\":\"65米\",\"B\":\"300米\",\"C\":\"1公里\",\"D\":\"40公里\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "万兆以太网物理层的1310纳米WWDM LAN接口支持的传输距离是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274698,
                "Body": "{\"A\":\"分组丢弃法\",\"B\":\"缓冲区预分配法\",\"C\":\"定额控制法\",\"D\":\"存储转发法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在阻塞控制方法中，直接对通信子网中分组的数量进行严格、精确的限制，以防止阻塞现象发生的方法为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274560,
                "Body": "{\"A\":\"48 bps\",\"B\":\"24 bps\",\"C\":\"18 bps\",\"D\":\"12 bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "无噪声信道的带宽为3KHz，每个信号码元的离散状态数为4个，则信道的最大数据传输速率可达（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274562,
                "Body": "{\"A\":\"将P地址解析为物理地址\",\"B\":\"将物理地址解析为P地址\",\"C\":\"将主机域名解析为P地址\",\"D\":\"将P地址解析为主机域名\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ARP协议的主要功能是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274575,
                "Body": "{\"A\":\"每一个网络的唯一标识\",\"B\":\"每一个子网的唯一标识\",\"C\":\"每一台主机的唯一标识\",\"D\":\"每一个用户的唯一标识\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址是Internet网上（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274609,
                "Body": "{\"A\":\"1200bps\",\"B\":\"2400bps\",\"C\":\"3600bps\",\"D\":\"4800bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用一个码元取8种离散状态的移相键控PSK方法，若码元速率为1200波特，则可获得的数据传输速率为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274624,
                "Body": "{\"A\":\"A类地址\",\"B\":\"B类地址\",\"C\":\"C类地址\",\"D\":\"广播地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址112.1.4.13属于（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274615,
                "Body": "{\"A\":\"64字节\",\"B\":\"128字节\",\"C\":\"256字节\",\"D\":\"512字节\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "100Base—T快速以太网，为了能成功地进行冲突检测，其最短帧长应为（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274707,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下说法中，不属于光纤用户网的特点是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274713,
                "Body": "{\"A\":\"图形图像压缩文件\",\"B\":\"二进制文件\",\"C\":\"文本文件\",\"D\":\"HTL文本文件\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "点击浏览器上的网页地址，从Web服务器下传的是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274620,
                "Body": "{\"A\":\"ADSL\",\"B\":\"RADSL\",\"C\":\"NDSL\",\"D\":\"VDSL\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>以下几项中不属于数字用户环路技术的是（　）</p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274578,
                "Body": "{\"A\":\"无线接入\",\"B\":\"租用高速通信线路\",\"C\":\"ADL拨号\",\"D\":\"传统电话拨号\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网服务供应商ISP接入因特网大多是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274696,
                "Body": "{\"A\":\"IP，ICMP，ARP，UDP\",\"B\":\"TCP，ICMP，UDP，ARP\",\"C\":\"IP，ICMP，ARP，RARP\",\"D\":\"UDP，IP，ICMP，RARP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>TCP／IP的互连层含有四个重要的协议，分别为（　）。</p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274705,
                "Body": "{\"A\":\"中继器\",\"B\":\"滤波器\",\"C\":\"路由器\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ADSL使用的信号分离器又称为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274614,
                "Body": "{\"A\":\"信号传播时延\",\"B\":\"数据传输时延\",\"C\":\"冲突检测时间\",\"D\":\"数据接收时延\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据帧从一个站点开始发送，到该数据帧发送完毕所需的时间称为（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274617,
                "Body": "{\"A\":\"包\",\"B\":\"信元\",\"C\":\"分组\",\"D\":\"帧\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网的链路上无差错的传输比特流称为（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274568,
                "Body": "{\"A\":\"1层\",\"B\":\"1-2层\",\"C\":\"1-3层\",\"D\":\"1-4层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网技术主要对应OSI参考模型底层的（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597645,
                "Body": "{\n  \"A\": \"证券交易系统\",\n  \"B\": \"信息处理系统\",\n  \"C\": \"远程医疗\",\n  \"D\": \"电子图书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面()属于网络应用。",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]