var topic2_2_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic2_2_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 275168,
                "Body": "{\"A\":\"计费管理\",\"B\":\"QOS管理\",\"C\":\"故障管理\",\"D\":\"性能管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>属于VPN管理内容的项是（）</p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274531,
                "Body": "{\"A\":\"故障管理\",\"B\":\"客户管理\",\"C\":\"应用管理\",\"D\":\"运营管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISO建议网络管理的基本功能应包括计费管理、配置管理、性能管理、安全管理和（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274719,
                "Body": "{\"A\":\"IP\",\"B\":\"TCP\",\"C\":\"FTP\",\"D\":\"UDP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP/IP协议簇中属于应用层协议的是（　）。",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274805,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用CSMA/CD协议，数据帧的传输时延至少要等于信号传播时延的（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275158,
                "Body": "{\"A\":\"SLIP协议\",\"B\":\"PPP协议\",\"C\":\"SMTP协议\",\"D\":\"HTTP协议\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>浏览器访问Web服务器时的信息传输遵循（）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275239,
                "Body": "{\"A\":\"\\t“存储——转发”式\",\"B\":\"\\t广播式\",\"C\":\"\\t电路交换式\",\"D\":\"\\t分散控制\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网LAN所采用的传输方式为",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274718,
                "Body": "{\"A\":\"帧\",\"B\":\"位\",\"C\":\"分组\",\"D\":\"报文\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据链路层的协议数据单元称作（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275167,
                "Body": "{\"A\":\"PPTP\",\"B\":\"VTP\",\"C\":\"PPP\",\"D\":\"IPsec\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>VPN中属于第二层遂道协议的是（）</p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274483,
                "Body": "{\"A\":\"图形图像压缩文件\",\"B\":\"二进制文件\",\"C\":\"文本文件\",\"D\":\"HTL文本文件\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "点击浏览器上的网页地址，从Web服务器下传的是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275384,
                "Body": "{\"A\":\"IEF    \",\"B\":\"IEE    \",\"C\":\"ECA    \",\"D\":\"ANI\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "负责管理与发布Internet RFC技术文件的组织是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274472,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275397,
                "Body": "{\"A\":\"VDL技术\",\"B\":\"SDL技术\",\"C\":\"HDL技术\",\"D\":\"ADL技术\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "利用现有的一对电话铜线，为用户提供上、下行非对称的传输速率，在原有普通电话线上实现一种新的高速宽带技术，这种技术称为 （　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274526,
                "Body": "{\"A\":\"LAA\",\"B\":\"LAC\",\"C\":\"LAD\",\"D\":\"LAE\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继中不采用HDLC的平衡链路接入规程LAPB，所采用的链路接入规程是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274559,
                "Body": "{\"A\":\"储存-转发\",\"B\":\"广播\",\"C\":\"点-点\",\"D\":\"异步传输\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网中信息从发送方传送到接收方采用的传输方式是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275408,
                "Body": "{\"A\":\"频分多址DA    \",\"B\":\"时分多址DA    \",\"C\":\"码分多址DA    \",\"D\":\"波分多址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在蜂窝移动通信系统中，主要采用的接入方法不包括",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274724,
                "Body": "{\"A\":\"电路交换+分组交换\",\"B\":\"分组交换\",\"C\":\"报文交换\",\"D\":\"电路交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "综合业务数字网（N-ISDN）采用的交换技术是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274875,
                "Body": "{\"A\":\"级别1\",\"B\":\"级别2\",\"C\":\"级别3\",\"D\":\"级别4\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "传输层的功能按级别划分，OSl定义了五种协议级别，其中能够提供差错检测，恢复即多路复用功能的级别是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274747,
                "Body": "{\"A\":\"拨号MODEM\",\"B\":\"ISDN（2B+D）\",\"C\":\"ADSL\",\"D\":\"光纤以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在下列个人用户接入广域网技术中，传输速率最高的是（　）。",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275298,
                "Body": "{\"A\":\"字节计数法                    \",\"B\":\"比特填充的首尾标志法  \",\"C\":\"违法编码法                    \",\"D\":\"字符填充的首尾定界符法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网IEEE802标准中采用的帧同步方法是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274766,
                "Body": "{\"A\":\"从512bit/s到1bit/s\",\"B\":\"从144bit/s到8bit/s\",\"C\":\"从128bit/s到2bit/s\",\"D\":\"从64bit/s到52bit/s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率，其速度范围是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274704,
                "Body": "{\"A\":\"128bps\",\"B\":\"144bps\",\"C\":\"256bps\",\"D\":\"512bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISDN提供的是2B+D的数据通道，其速率最高可达到（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274617,
                "Body": "{\"A\":\"包\",\"B\":\"信元\",\"C\":\"分组\",\"D\":\"帧\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网的链路上无差错的传输比特流称为（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274565,
                "Body": "{\"A\":\"冲突检测时间\",\"B\":\"数据传输时延\",\"C\":\"信号传播时延\",\"D\":\"数据接收时延\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "从一个站点开始发送数据到另一个站点开始接收数据所需的时间，称为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274576,
                "Body": "{\"A\":\"用户-mail地址在整个因特网是唯一的\",\"B\":\"用户-mail地址在用户所在邮件服务器中是唯一的\",\"C\":\"用户-mail地址在一个国家是唯一的\",\"D\":\"用户-mail地址可以不唯一\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下关于用户E-mail地址唯一性的叙述正确的是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274563,
                "Body": "{\"A\":\"传送原始比特流\",\"B\":\"建立数据链路连接\",\"C\":\"实现路由选择\",\"D\":\"提供端到端的服务\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "OSI参考模型中物理层的主要作用是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274700,
                "Body": "{\"A\":\"经典以太网\",\"B\":\"百兆以太网\",\"C\":\"千兆以太网\",\"D\":\"万兆以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "不再支持半双工数据传输，所有传输都以全双工方式进行的以太网技术是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274710,
                "Body": "{\"A\":\"为全0\",\"B\":\"为全1\",\"C\":\"相同\",\"D\":\"不同\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "若两台主机在同一子网中，则两台主机的IP地址分别与它们的子网掩码相“与”的结果一定（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274705,
                "Body": "{\"A\":\"中继器\",\"B\":\"滤波器\",\"C\":\"路由器\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ADSL使用的信号分离器又称为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274611,
                "Body": "{\"A\":\"分配IP地址\",\"B\":\"提供端到端的面向连接的可靠数据传输\",\"C\":\"确定数据传输路径\",\"D\":\"提高传输速度\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP协议的主要功能是（　）",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274561,
                "Body": "{\"A\":\"每一层实现一种相对独立的功能\",\"B\":\"每一层都知道下面一层是如何实现的\",\"C\":\"每一层的功能相对简单且易于实现和维护\",\"D\":\"每一层不必知道下面一层是如何实现的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪一项错误地描述了网络体系结构中分层的特点（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274578,
                "Body": "{\"A\":\"无线接入\",\"B\":\"租用高速通信线路\",\"C\":\"ADL拨号\",\"D\":\"传统电话拨号\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网服务供应商ISP接入因特网大多是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274614,
                "Body": "{\"A\":\"信号传播时延\",\"B\":\"数据传输时延\",\"C\":\"冲突检测时间\",\"D\":\"数据接收时延\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据帧从一个站点开始发送，到该数据帧发送完毕所需的时间称为（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274577,
                "Body": "{\"A\":\"邮件服务器\",\"B\":\"域名系统(N)\",\"C\":\"统一资源定位器(R)\",\"D\":\"代理服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "E-mail地址格式为：用户名@主机域名，传送邮件时必须将主机域名转换成IP地址，实现该项转换工作的是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274698,
                "Body": "{\"A\":\"分组丢弃法\",\"B\":\"缓冲区预分配法\",\"C\":\"定额控制法\",\"D\":\"存储转发法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在阻塞控制方法中，直接对通信子网中分组的数量进行严格、精确的限制，以防止阻塞现象发生的方法为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274702,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274626,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"网页地址\",\"C\":\"IP地址\",\"D\":\"物理地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列地址中与“域名”有一一对应关系的是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274709,
                "Body": "{\"A\":\"255、255、255、0\",\"B\":\"255、255、255、192\",\"C\":\"255、255、255、240\",\"D\":\"255、255、255、255\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "某部门申请了一个C类IP地址，若要分成16个规模相同的子网，其掩码应为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274695,
                "Body": "{\"A\":\"COE中的编码器\",\"B\":\"COE中的解码器\",\"C\":\"MOE中的调制器\",\"D\":\"MOE中的解调器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "模拟数据也可以用数字信号来表示。对于声音数据来说，完成将模拟数据转换为数字信号的设施为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274624,
                "Body": "{\"A\":\"A类地址\",\"B\":\"B类地址\",\"C\":\"C类地址\",\"D\":\"广播地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址112.1.4.13属于（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597645,
                "Body": "{\n  \"A\": \"证券交易系统\",\n  \"B\": \"信息处理系统\",\n  \"C\": \"远程医疗\",\n  \"D\": \"电子图书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面()属于网络应用。",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]