var topic3_1_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic3_1_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 275302,
                "Body": "{\"A\":\"ARP\",\"B\":\"RARP\",\"C\":\"ICMP\",\"D\":\"FTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在TCP/IP环境下，网络层有一组协议将IP地址转换为相应物理网络地址，这组协议即是",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274825,
                "Body": "{\"A\":\"链路层和网络层\",\"B\":\"物理层和网络层\",\"C\":\"网络层和传输层\",\"D\":\"物理层和链路层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术使用链路层实现复用和转接，所以帧中继网络的中间结点中只有（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275208,
                "Body": "{\"A\":\"IEEE802.3\",\"B\":\"IEEE802.4\",\"C\":\"IEEE802.5\",\"D\":\"JEEE802.11\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列IEEE标准中，属于无线局域网标准的是<br><br>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275312,
                "Body": "{\"A\":\"主机 \",\"B\":\"键盘\",\"C\":\"TC/P \",\"D\":\"OSI\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在网络管理中,必须实现代理模块的设备是",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275281,
                "Body": "{\"A\":\"模拟传输\",\"B\":\"数字传输\",\"C\":\"模拟—数字混合传输\",\"D\":\"以上均不对\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在局域网中，由于距离近以及数字电路器件价格的下降，所以更具优越性的传输技术是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274870,
                "Body": "{\"A\":\"远程通信网络\",\"B\":\"消息通信网络\",\"C\":\"事务管理网络\",\"D\":\"开放式标准化网络\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "计算机网络的发展和演变，可总体概括为四个阶段，它们是面向终端的计算机网络、计算机——计算机网络、因特网的广泛应用与高速网络技术的发展、（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275380,
                "Body": "{\"A\":\"CMIS\",\"B\":\"SNMP       \",\"C\":\"CMIP           \",\"D\":\"SMTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "基于TCP／IP协议簇的网络管理标准协议是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274472,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275379,
                "Body": "{\"A\":\"AT信元中信息段长度固定为53字节  \",\"B\":\"AT网络在信元交换前需建立虚拟连接  \",\"C\":\"AT网络不参与任何数据链路层的功能  \",\"D\":\"AT物理链路逻辑上分虚路径和虚通道\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于异步传输模式ATM的表述中错误的是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274860,
                "Body": "{\"A\":\"转发器\",\"B\":\"路由器\",\"C\":\"网关\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对传输层和传输层以上的协议进行转换的设备称为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274857,
                "Body": "{\"A\":\"电路交换\",\"B\":\"报文交换\",\"C\":\"分组交换\",\"D\":\"信元交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在三种常用的数据交换技术中，线路利用率最低的是（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275240,
                "Body": "{\"A\":\"\\tRAE       \",\"B\":\"\\tEnet       \",\"C\":\"\\tSNT      \",\"D\":\"\\tthernet\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网（Internet）的起源可追溯到它的前身",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275349,
                "Body": "{\"A\":\"\\tT    \",\"B\":\"\\tLP     \",\"C\":\"\\tP      \",\"D\":\"\\telnet\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet实现远程登录服务的协议",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274522,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA／CD的代价是用于检测冲突所花费的时间。对于基带总线而言，最坏情况下用于检测一个冲突的时间等于任意两个站之间最大传播时延的（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274517,
                "Body": "{\"A\":\"链路层服务\",\"B\":\"网络层服务\",\"C\":\"传输层服务\",\"D\":\"应用层服务\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP／IP体系结构中的TCP协议所提供的服务是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275158,
                "Body": "{\"A\":\"SLIP协议\",\"B\":\"PPP协议\",\"C\":\"SMTP协议\",\"D\":\"HTTP协议\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>浏览器访问Web服务器时的信息传输遵循（）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275408,
                "Body": "{\"A\":\"频分多址DA    \",\"B\":\"时分多址DA    \",\"C\":\"码分多址DA    \",\"D\":\"波分多址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在蜂窝移动通信系统中，主要采用的接入方法不包括",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275170,
                "Body": "{\"A\":\"中继器\",\"B\":\"交换机\",\"C\":\"防火墙\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为增强Intranet的安全性，在被保护的Intranet与Internet之间竖起一道安全屏障称为（）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274477,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于光纤用户网的特点是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274766,
                "Body": "{\"A\":\"从512bit/s到1bit/s\",\"B\":\"从144bit/s到8bit/s\",\"C\":\"从128bit/s到2bit/s\",\"D\":\"从64bit/s到52bit/s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率，其速度范围是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274730,
                "Body": "{\"A\":\"邮件服务器地址\",\"B\":\"字符形式的网页地址\",\"C\":\"字符形式的P地址\",\"D\":\"Web服务器地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet上的域名是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275292,
                "Body": "{\"A\":\"\\tSN方式\",\"B\":\"\\t仿真终端方式\",\"C\":\"\\t局域网连接方式\",\"D\":\"\\t广域网连接方式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在Internet中，ISP的接入方式有帧中继方式、专线（DDN）方式及",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275317,
                "Body": "{\"A\":\"4倍\",\"B\":\".3倍\",\"C\":\"2.5倍\",\"D\":\"2倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为了确保发送站点在传输时能检测到可能存在的冲突，CSMA／CD数据帧的传输时延至少要等于信号传输时延的()",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274761,
                "Body": "{\"A\":\"1000Base-T\",\"B\":\"1000Base-LX\",\"C\":\"1000Base-CX\",\"D\":\"1000ase-SX\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "只支持多模光纤的千兆以太网物理层协议是（　）。",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274719,
                "Body": "{\"A\":\"IP\",\"B\":\"TCP\",\"C\":\"FTP\",\"D\":\"UDP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP/IP协议簇中属于应用层协议的是（　）。",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274622,
                "Body": "{\"A\":\"1bps\",\"B\":\"1.544bps\",\"C\":\"2.048bps\",\"D\":\"10bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "E1载波的数据传输率为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274712,
                "Body": "{\"A\":\"第2层\",\"B\":\"第3层\",\"C\":\"第4层\",\"D\":\"第5-7层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "FTP文件传输协议对应于OSI的（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274571,
                "Body": "{\"A\":\"从512bit／s到1bit／s\",\"B\":\"从144bit／s到8bit／s\",\"C\":\"从128bit／s到2bit／s\",\"D\":\"从64bit／s到52bit／s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率。其范围是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274576,
                "Body": "{\"A\":\"用户-mail地址在整个因特网是唯一的\",\"B\":\"用户-mail地址在用户所在邮件服务器中是唯一的\",\"C\":\"用户-mail地址在一个国家是唯一的\",\"D\":\"用户-mail地址可以不唯一\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下关于用户E-mail地址唯一性的叙述正确的是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274624,
                "Body": "{\"A\":\"A类地址\",\"B\":\"B类地址\",\"C\":\"C类地址\",\"D\":\"广播地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址112.1.4.13属于（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274695,
                "Body": "{\"A\":\"COE中的编码器\",\"B\":\"COE中的解码器\",\"C\":\"MOE中的调制器\",\"D\":\"MOE中的解调器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "模拟数据也可以用数字信号来表示。对于声音数据来说，完成将模拟数据转换为数字信号的设施为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274570,
                "Body": "{\"A\":\"按需分配\",\"B\":\"平均分配\",\"C\":\"根据业务种类按比例分配\",\"D\":\"一种业务对应一个固定的时间片\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ATM网络的各种业务在信道上时间片的分配原则是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274709,
                "Body": "{\"A\":\"255、255、255、0\",\"B\":\"255、255、255、192\",\"C\":\"255、255、255、240\",\"D\":\"255、255、255、255\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "某部门申请了一个C类IP地址，若要分成16个规模相同的子网，其掩码应为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274618,
                "Body": "{\"A\":\"网络终端Tl\",\"B\":\"网络终端T2\",\"C\":\"网络终端Tl+T2\",\"D\":\"调制解调器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对于家庭和小型机构在用户设备和ISDN交换设备之间需要安装的设备是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274567,
                "Body": "{\"A\":\"65米\",\"B\":\"300米\",\"C\":\"1公里\",\"D\":\"40公里\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "万兆以太网物理层的1310纳米WWDM LAN接口支持的传输距离是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274713,
                "Body": "{\"A\":\"图形图像压缩文件\",\"B\":\"二进制文件\",\"C\":\"文本文件\",\"D\":\"HTL文本文件\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "点击浏览器上的网页地址，从Web服务器下传的是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274574,
                "Body": "{\"A\":\"IS主机\",\"B\":\"通信网络的交换节点\",\"C\":\"ICD、W服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP拨号方式是通过电话拨号将自己的计算机连接到（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274707,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下说法中，不属于光纤用户网的特点是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274710,
                "Body": "{\"A\":\"为全0\",\"B\":\"为全1\",\"C\":\"相同\",\"D\":\"不同\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "若两台主机在同一子网中，则两台主机的IP地址分别与它们的子网掩码相“与”的结果一定（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274613,
                "Body": "{\"A\":\"字节计数法\",\"B\":\"使用字符填充的首尾定界符法\",\"C\":\"使用比特填充的首尾标志法\",\"D\":\"违法编码法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "HDLC规程采用的帧同步方法为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597645,
                "Body": "{\n  \"A\": \"证券交易系统\",\n  \"B\": \"信息处理系统\",\n  \"C\": \"远程医疗\",\n  \"D\": \"电子图书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面()属于网络应用。",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]