var topic3_2_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic3_2_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 275410,
                "Body": "{\"A\":\"流量控制是数据链路层特有的功能(不是)\",\"B\":\"链路管理功能主要用于面向连接的服务  \",\"C\":\"差错控制是数据链路层的功能之一    \",\"D\":\"链路管理包括连接的建立、维持和释放\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于数据链路层功能的叙述中错误的",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275317,
                "Body": "{\"A\":\"4倍\",\"B\":\".3倍\",\"C\":\"2.5倍\",\"D\":\"2倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为了确保发送站点在传输时能检测到可能存在的冲突，CSMA／CD数据帧的传输时延至少要等于信号传输时延的()",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274717,
                "Body": "{\"A\":\"一种计算机网络的实现\",\"B\":\"执行计算机数据处理的软件模块\",\"C\":\"由S定义的一个标准\",\"D\":\"计算机网络各层次结构模型及其协议的集合\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络体系结构可以定义为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274531,
                "Body": "{\"A\":\"故障管理\",\"B\":\"客户管理\",\"C\":\"应用管理\",\"D\":\"运营管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISO建议网络管理的基本功能应包括计费管理、配置管理、性能管理、安全管理和（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274881,
                "Body": "{\"A\":\"LAA\",\"B\":\"LAB\",\"C\":\"LAC\",\"D\":\"LAD\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继采用的链路接人规程为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274730,
                "Body": "{\"A\":\"邮件服务器地址\",\"B\":\"字符形式的网页地址\",\"C\":\"字符形式的P地址\",\"D\":\"Web服务器地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet上的域名是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274723,
                "Body": "{\"A\":\"1层\",\"B\":\"1—2层\",\"C\":\"1—3层\",\"D\":\"1—4层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网技术主要对应OSI参考模型底层的（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275298,
                "Body": "{\"A\":\"字节计数法                    \",\"B\":\"比特填充的首尾标志法  \",\"C\":\"违法编码法                    \",\"D\":\"字符填充的首尾定界符法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网IEEE802标准中采用的帧同步方法是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275143,
                "Body": "{\"A\":\"环形拓扑\",\"B\":\"树型结构\",\"C\":\"网形拓扑\",\"D\":\"总线拓扑\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在广域网得到了广泛应用、节点之间有许多条路径相连，这样的网络拓扑结构是<br><br>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275167,
                "Body": "{\"A\":\"PPTP\",\"B\":\"VTP\",\"C\":\"PPP\",\"D\":\"IPsec\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>VPN中属于第二层遂道协议的是（）</p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274857,
                "Body": "{\"A\":\"电路交换\",\"B\":\"报文交换\",\"C\":\"分组交换\",\"D\":\"信元交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在三种常用的数据交换技术中，线路利用率最低的是（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274483,
                "Body": "{\"A\":\"图形图像压缩文件\",\"B\":\"二进制文件\",\"C\":\"文本文件\",\"D\":\"HTL文本文件\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "点击浏览器上的网页地址，从Web服务器下传的是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274522,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA／CD的代价是用于检测冲突所花费的时间。对于基带总线而言，最坏情况下用于检测一个冲突的时间等于任意两个站之间最大传播时延的（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275170,
                "Body": "{\"A\":\"中继器\",\"B\":\"交换机\",\"C\":\"防火墙\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为增强Intranet的安全性，在被保护的Intranet与Internet之间竖起一道安全屏障称为（）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274478,
                "Body": "{\"A\":\"被管代理\",\"B\":\"网络管理器\",\"C\":\"网络管理协议\",\"D\":\"管理信息库\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络管理系统中驻留在被管对象上配合网络管理的处理实体称为（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274477,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于光纤用户网的特点是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274719,
                "Body": "{\"A\":\"IP\",\"B\":\"TCP\",\"C\":\"FTP\",\"D\":\"UDP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP/IP协议簇中属于应用层协议的是（　）。",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274559,
                "Body": "{\"A\":\"储存-转发\",\"B\":\"广播\",\"C\":\"点-点\",\"D\":\"异步传输\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网中信息从发送方传送到接收方采用的传输方式是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275310,
                "Body": "{\"A\":\"路由划分    \",\"B\":\"按交换端口号划分    \",\"C\":\"按MAC地址划分    \",\"D\":\"按第三层协议划分\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列所述划分虚拟局域网的常用方法中错误的",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274517,
                "Body": "{\"A\":\"链路层服务\",\"B\":\"网络层服务\",\"C\":\"传输层服务\",\"D\":\"应用层服务\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP／IP体系结构中的TCP协议所提供的服务是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274763,
                "Body": "{\"A\":\"1层\",\"B\":\"1-2层\",\"C\":\"1-3层\",\"D\":\"1-4层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网技术主要对应OSI参考模型底层的（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274825,
                "Body": "{\"A\":\"链路层和网络层\",\"B\":\"物理层和网络层\",\"C\":\"网络层和传输层\",\"D\":\"物理层和链路层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术使用链路层实现复用和转接，所以帧中继网络的中间结点中只有（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275168,
                "Body": "{\"A\":\"计费管理\",\"B\":\"QOS管理\",\"C\":\"故障管理\",\"D\":\"性能管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>属于VPN管理内容的项是（）</p>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274766,
                "Body": "{\"A\":\"从512bit/s到1bit/s\",\"B\":\"从144bit/s到8bit/s\",\"C\":\"从128bit/s到2bit/s\",\"D\":\"从64bit/s到52bit/s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率，其速度范围是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275379,
                "Body": "{\"A\":\"AT信元中信息段长度固定为53字节  \",\"B\":\"AT网络在信元交换前需建立虚拟连接  \",\"C\":\"AT网络不参与任何数据链路层的功能  \",\"D\":\"AT物理链路逻辑上分虚路径和虚通道\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于异步传输模式ATM的表述中错误的是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275302,
                "Body": "{\"A\":\"ARP\",\"B\":\"RARP\",\"C\":\"ICMP\",\"D\":\"FTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在TCP/IP环境下，网络层有一组协议将IP地址转换为相应物理网络地址，这组协议即是",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274612,
                "Body": "{\"A\":\"IP\",\"B\":\"ARP\",\"C\":\"TCP\",\"D\":\"DNS\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>下列协议中运行在应用层的协议是（　）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274567,
                "Body": "{\"A\":\"65米\",\"B\":\"300米\",\"C\":\"1公里\",\"D\":\"40公里\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "万兆以太网物理层的1310纳米WWDM LAN接口支持的传输距离是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274571,
                "Body": "{\"A\":\"从512bit／s到1bit／s\",\"B\":\"从144bit／s到8bit／s\",\"C\":\"从128bit／s到2bit／s\",\"D\":\"从64bit／s到52bit／s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率。其范围是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274574,
                "Body": "{\"A\":\"IS主机\",\"B\":\"通信网络的交换节点\",\"C\":\"ICD、W服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP拨号方式是通过电话拨号将自己的计算机连接到（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274610,
                "Body": "{\"A\":\"包\",\"B\":\"比特\",\"C\":\"帧\",\"D\":\"数据块\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "物理层传输的数据单位是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274704,
                "Body": "{\"A\":\"128bps\",\"B\":\"144bps\",\"C\":\"256bps\",\"D\":\"512bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISDN提供的是2B+D的数据通道，其速率最高可达到（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274617,
                "Body": "{\"A\":\"包\",\"B\":\"信元\",\"C\":\"分组\",\"D\":\"帧\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网的链路上无差错的传输比特流称为（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274575,
                "Body": "{\"A\":\"每一个网络的唯一标识\",\"B\":\"每一个子网的唯一标识\",\"C\":\"每一台主机的唯一标识\",\"D\":\"每一个用户的唯一标识\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址是Internet网上（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274627,
                "Body": "{\"A\":\"在整个因特网上是唯一的\",\"B\":\"在一个国家是唯一的\",\"C\":\"在用户所在邮件服务器中是唯一的\",\"D\":\"在同一网络标识的网上是唯一的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "用户E-mail地址中的用户名（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274561,
                "Body": "{\"A\":\"每一层实现一种相对独立的功能\",\"B\":\"每一层都知道下面一层是如何实现的\",\"C\":\"每一层的功能相对简单且易于实现和维护\",\"D\":\"每一层不必知道下面一层是如何实现的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪一项错误地描述了网络体系结构中分层的特点（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274560,
                "Body": "{\"A\":\"48 bps\",\"B\":\"24 bps\",\"C\":\"18 bps\",\"D\":\"12 bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "无噪声信道的带宽为3KHz，每个信号码元的离散状态数为4个，则信道的最大数据传输速率可达（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274609,
                "Body": "{\"A\":\"1200bps\",\"B\":\"2400bps\",\"C\":\"3600bps\",\"D\":\"4800bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用一个码元取8种离散状态的移相键控PSK方法，若码元速率为1200波特，则可获得的数据传输速率为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274625,
                "Body": "{\"A\":\"255.255.255.0\",\"B\":\"255.255.255.192\",\"C\":\"255.255.255.248\",\"D\":\"255.255.255.240\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "某部门申请了一个C类IP地址，若要分成32个子网，其掩码应为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597645,
                "Body": "{\n  \"A\": \"证券交易系统\",\n  \"B\": \"信息处理系统\",\n  \"C\": \"远程医疗\",\n  \"D\": \"电子图书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面()属于网络应用。",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]