var topic4_1_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic4_1_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 275400,
                "Body": "{\"A\":\"分担负荷\",\"B\":\"硬件资源共享\",\"C\":\"软件资源共享\",\"D\":\"用户间信息交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "通过计算机网络发布新闻消息活动，属于 （　　）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275239,
                "Body": "{\"A\":\"\\t“存储——转发”式\",\"B\":\"\\t广播式\",\"C\":\"\\t电路交换式\",\"D\":\"\\t分散控制\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网LAN所采用的传输方式为",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275415,
                "Body": "{\"A\":\"\\t物理层\",\"B\":\"\\t数据链接层\",\"C\":\"\\t网络层\",\"D\":\"\\t传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继是继X.25之后发展起来的数据通信方式，但帧中继与X.25不同，其复用和转接发生在（）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274522,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA／CD的代价是用于检测冲突所花费的时间。对于基带总线而言，最坏情况下用于检测一个冲突的时间等于任意两个站之间最大传播时延的（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274860,
                "Body": "{\"A\":\"转发器\",\"B\":\"路由器\",\"C\":\"网关\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对传输层和传输层以上的协议进行转换的设备称为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274870,
                "Body": "{\"A\":\"远程通信网络\",\"B\":\"消息通信网络\",\"C\":\"事务管理网络\",\"D\":\"开放式标准化网络\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "计算机网络的发展和演变，可总体概括为四个阶段，它们是面向终端的计算机网络、计算机——计算机网络、因特网的广泛应用与高速网络技术的发展、（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274478,
                "Body": "{\"A\":\"被管代理\",\"B\":\"网络管理器\",\"C\":\"网络管理协议\",\"D\":\"管理信息库\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络管理系统中驻留在被管对象上配合网络管理的处理实体称为（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274719,
                "Body": "{\"A\":\"IP\",\"B\":\"TCP\",\"C\":\"FTP\",\"D\":\"UDP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP/IP协议簇中属于应用层协议的是（　）。",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275158,
                "Body": "{\"A\":\"SLIP协议\",\"B\":\"PPP协议\",\"C\":\"SMTP协议\",\"D\":\"HTTP协议\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>浏览器访问Web服务器时的信息传输遵循（）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274517,
                "Body": "{\"A\":\"链路层服务\",\"B\":\"网络层服务\",\"C\":\"传输层服务\",\"D\":\"应用层服务\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP／IP体系结构中的TCP协议所提供的服务是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275397,
                "Body": "{\"A\":\"VDL技术\",\"B\":\"SDL技术\",\"C\":\"HDL技术\",\"D\":\"ADL技术\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "利用现有的一对电话铜线，为用户提供上、下行非对称的传输速率，在原有普通电话线上实现一种新的高速宽带技术，这种技术称为 （　　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275394,
                "Body": "{\"A\":\"消息泄漏 \",\"B\":\"假冒\",\"C\":\"拒绝服务 \",\"D\":\"修改报文流\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "SNMPv3中哪种威胁是安全体系结构不必防护的?",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274733,
                "Body": "{\"A\":\"在Web服务器进行\",\"B\":\"在代理服务器上进行\",\"C\":\"在浏览器上进行\",\"D\":\"在ISP上进行\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>点击浏览器上的网页地址，该网页的HTML文件的解释执行（　）。</p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275379,
                "Body": "{\"A\":\"AT信元中信息段长度固定为53字节  \",\"B\":\"AT网络在信元交换前需建立虚拟连接  \",\"C\":\"AT网络不参与任何数据链路层的功能  \",\"D\":\"AT物理链路逻辑上分虚路径和虚通道\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于异步传输模式ATM的表述中错误的是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275244,
                "Body": "{\"A\":\"奇偶校验码    \",\"B\":\"海明编码    \",\"C\":\"循环冗余码    \",\"D\":\"PC编码\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "计算机网络和数据通信中使用最广泛的检错码是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275250,
                "Body": "{\"A\":\"局域式\",\"B\":\"集中型\",\"C\":\"发散型\",\"D\":\"分布式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "1974年最早推出的SNA主要适用于（　　）的面向终端的计算机网络",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275317,
                "Body": "{\"A\":\"4倍\",\"B\":\".3倍\",\"C\":\"2.5倍\",\"D\":\"2倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为了确保发送站点在传输时能检测到可能存在的冲突，CSMA／CD数据帧的传输时延至少要等于信号传输时延的()",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275255,
                "Body": "{\"A\":\"电话\",\"B\":\"卫星\",\"C\":\"光缆线\",\"D\":\"网络连接器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列不属于通信链路介质的是 （　　）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275380,
                "Body": "{\"A\":\"CMIS\",\"B\":\"SNMP       \",\"C\":\"CMIP           \",\"D\":\"SMTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "基于TCP／IP协议簇的网络管理标准协议是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275292,
                "Body": "{\"A\":\"\\tSN方式\",\"B\":\"\\t仿真终端方式\",\"C\":\"\\t局域网连接方式\",\"D\":\"\\t广域网连接方式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在Internet中，ISP的接入方式有帧中继方式、专线（DDN）方式及",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274718,
                "Body": "{\"A\":\"帧\",\"B\":\"位\",\"C\":\"分组\",\"D\":\"报文\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据链路层的协议数据单元称作（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275240,
                "Body": "{\"A\":\"\\tRAE       \",\"B\":\"\\tEnet       \",\"C\":\"\\tSNT      \",\"D\":\"\\tthernet\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网（Internet）的起源可追溯到它的前身",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274573,
                "Body": "{\"A\":\"FTC\",\"B\":\"FTZ\",\"C\":\"FTO\",\"D\":\"FTF\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "光纤到办公室的用户网光纤化方案是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274563,
                "Body": "{\"A\":\"传送原始比特流\",\"B\":\"建立数据链路连接\",\"C\":\"实现路由选择\",\"D\":\"提供端到端的服务\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "OSI参考模型中物理层的主要作用是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274565,
                "Body": "{\"A\":\"冲突检测时间\",\"B\":\"数据传输时延\",\"C\":\"信号传播时延\",\"D\":\"数据接收时延\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "从一个站点开始发送数据到另一个站点开始接收数据所需的时间，称为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274571,
                "Body": "{\"A\":\"从512bit／s到1bit／s\",\"B\":\"从144bit／s到8bit／s\",\"C\":\"从128bit／s到2bit／s\",\"D\":\"从64bit／s到52bit／s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率。其范围是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274623,
                "Body": "{\"A\":\"SLP协议\",\"B\":\"PP协议\",\"C\":\"XO／OF规程\",\"D\":\"HDC规程\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "用户通过电话线拨号上网时，想要分配到动态IP地址链路层应采用（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274706,
                "Body": "{\"A\":\"272bps或1、088bps\",\"B\":\"1bps或10bps\",\"C\":\"1、5bps或2、3bps\",\"D\":\"13bps或52bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "HomePNA技术为对称式数据传输，其双向传输带宽均为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274624,
                "Body": "{\"A\":\"A类地址\",\"B\":\"B类地址\",\"C\":\"C类地址\",\"D\":\"广播地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址112.1.4.13属于（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274626,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"网页地址\",\"C\":\"IP地址\",\"D\":\"物理地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列地址中与“域名”有一一对应关系的是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274711,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"IP地址\",\"C\":\"域名地址\",\"D\":\"统一资源定位器（R）\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "WWW上的每一个网页包括主页都有一个独立的地址，这些地址由32位二进制表示则称为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274567,
                "Body": "{\"A\":\"65米\",\"B\":\"300米\",\"C\":\"1公里\",\"D\":\"40公里\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "万兆以太网物理层的1310纳米WWDM LAN接口支持的传输距离是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274625,
                "Body": "{\"A\":\"255.255.255.0\",\"B\":\"255.255.255.192\",\"C\":\"255.255.255.248\",\"D\":\"255.255.255.240\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "某部门申请了一个C类IP地址，若要分成32个子网，其掩码应为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274621,
                "Body": "{\"A\":\"拨号MODEM\",\"B\":\"ISDN(2B+D)\",\"C\":\"ADSL\",\"D\":\"光纤以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>在下列个人用户接入广域网技术中，传输速率最高的是（　）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274622,
                "Body": "{\"A\":\"1bps\",\"B\":\"1.544bps\",\"C\":\"2.048bps\",\"D\":\"10bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "E1载波的数据传输率为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274708,
                "Body": "{\"A\":\"被管代理\",\"B\":\"网络管理器\",\"C\":\"网络管理协议\",\"D\":\"管理信息库\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络管理系统中驻留在被管对象上配合网络管理的处理实体称为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274613,
                "Body": "{\"A\":\"字节计数法\",\"B\":\"使用字符填充的首尾定界符法\",\"C\":\"使用比特填充的首尾标志法\",\"D\":\"违法编码法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "HDLC规程采用的帧同步方法为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274709,
                "Body": "{\"A\":\"255、255、255、0\",\"B\":\"255、255、255、192\",\"C\":\"255、255、255、240\",\"D\":\"255、255、255、255\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "某部门申请了一个C类IP地址，若要分成16个规模相同的子网，其掩码应为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274620,
                "Body": "{\"A\":\"ADSL\",\"B\":\"RADSL\",\"C\":\"NDSL\",\"D\":\"VDSL\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>以下几项中不属于数字用户环路技术的是（　）</p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597645,
                "Body": "{\n  \"A\": \"证券交易系统\",\n  \"B\": \"信息处理系统\",\n  \"C\": \"远程医疗\",\n  \"D\": \"电子图书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面()属于网络应用。",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]