var topic4_2_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic4_2_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 274825,
                "Body": "{\"A\":\"链路层和网络层\",\"B\":\"物理层和网络层\",\"C\":\"网络层和传输层\",\"D\":\"物理层和链路层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术使用链路层实现复用和转接，所以帧中继网络的中间结点中只有（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274881,
                "Body": "{\"A\":\"LAA\",\"B\":\"LAB\",\"C\":\"LAC\",\"D\":\"LAD\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继采用的链路接人规程为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275384,
                "Body": "{\"A\":\"IEF    \",\"B\":\"IEE    \",\"C\":\"ECA    \",\"D\":\"ANI\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "负责管理与发布Internet RFC技术文件的组织是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275208,
                "Body": "{\"A\":\"IEEE802.3\",\"B\":\"IEEE802.4\",\"C\":\"IEEE802.5\",\"D\":\"JEEE802.11\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列IEEE标准中，属于无线局域网标准的是<br><br>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275143,
                "Body": "{\"A\":\"环形拓扑\",\"B\":\"树型结构\",\"C\":\"网形拓扑\",\"D\":\"总线拓扑\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在广域网得到了广泛应用、节点之间有许多条路径相连，这样的网络拓扑结构是<br><br>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275244,
                "Body": "{\"A\":\"奇偶校验码    \",\"B\":\"海明编码    \",\"C\":\"循环冗余码    \",\"D\":\"PC编码\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "计算机网络和数据通信中使用最广泛的检错码是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274720,
                "Body": "{\"A\":\"L=l\",\"B\":\"L=2\",\"C\":\"L=4\",\"D\":\"L=8\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA/CD的二进制指数退避算法的规则之一是，对每个数据帧，当第一次发生冲突时，需要设置的一个参数量为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275349,
                "Body": "{\"A\":\"\\tT    \",\"B\":\"\\tLP     \",\"C\":\"\\tP      \",\"D\":\"\\telnet\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet实现远程登录服务的协议",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275379,
                "Body": "{\"A\":\"AT信元中信息段长度固定为53字节  \",\"B\":\"AT网络在信元交换前需建立虚拟连接  \",\"C\":\"AT网络不参与任何数据链路层的功能  \",\"D\":\"AT物理链路逻辑上分虚路径和虚通道\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于异步传输模式ATM的表述中错误的是",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274522,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA／CD的代价是用于检测冲突所花费的时间。对于基带总线而言，最坏情况下用于检测一个冲突的时间等于任意两个站之间最大传播时延的（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274559,
                "Body": "{\"A\":\"储存-转发\",\"B\":\"广播\",\"C\":\"点-点\",\"D\":\"异步传输\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网中信息从发送方传送到接收方采用的传输方式是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275158,
                "Body": "{\"A\":\"SLIP协议\",\"B\":\"PPP协议\",\"C\":\"SMTP协议\",\"D\":\"HTTP协议\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>浏览器访问Web服务器时的信息传输遵循（）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274730,
                "Body": "{\"A\":\"邮件服务器地址\",\"B\":\"字符形式的网页地址\",\"C\":\"字符形式的P地址\",\"D\":\"Web服务器地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet上的域名是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275382,
                "Body": "{\"A\":\"控制简单    \",\"B\":\"站点分布处理能力高    \",\"C\":\"方便服务    \",\"D\":\"故障诊断和隔离容易\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列关于星形拓扑结构优点的表述中错误的是",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275240,
                "Body": "{\"A\":\"\\tRAE       \",\"B\":\"\\tEnet       \",\"C\":\"\\tSNT      \",\"D\":\"\\tthernet\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网（Internet）的起源可追溯到它的前身",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275250,
                "Body": "{\"A\":\"局域式\",\"B\":\"集中型\",\"C\":\"发散型\",\"D\":\"分布式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "1974年最早推出的SNA主要适用于（　　）的面向终端的计算机网络",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275310,
                "Body": "{\"A\":\"路由划分    \",\"B\":\"按交换端口号划分    \",\"C\":\"按MAC地址划分    \",\"D\":\"按第三层协议划分\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列所述划分虚拟局域网的常用方法中错误的",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274617,
                "Body": "{\"A\":\"包\",\"B\":\"信元\",\"C\":\"分组\",\"D\":\"帧\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网的链路上无差错的传输比特流称为（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274708,
                "Body": "{\"A\":\"被管代理\",\"B\":\"网络管理器\",\"C\":\"网络管理协议\",\"D\":\"管理信息库\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络管理系统中驻留在被管对象上配合网络管理的处理实体称为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274615,
                "Body": "{\"A\":\"64字节\",\"B\":\"128字节\",\"C\":\"256字节\",\"D\":\"512字节\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "100Base—T快速以太网，为了能成功地进行冲突检测，其最短帧长应为（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274700,
                "Body": "{\"A\":\"经典以太网\",\"B\":\"百兆以太网\",\"C\":\"千兆以太网\",\"D\":\"万兆以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "不再支持半双工数据传输，所有传输都以全双工方式进行的以太网技术是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274626,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"网页地址\",\"C\":\"IP地址\",\"D\":\"物理地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列地址中与“域名”有一一对应关系的是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274623,
                "Body": "{\"A\":\"SLP协议\",\"B\":\"PP协议\",\"C\":\"XO／OF规程\",\"D\":\"HDC规程\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "用户通过电话线拨号上网时，想要分配到动态IP地址链路层应采用（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274575,
                "Body": "{\"A\":\"每一个网络的唯一标识\",\"B\":\"每一个子网的唯一标识\",\"C\":\"每一台主机的唯一标识\",\"D\":\"每一个用户的唯一标识\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址是Internet网上（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274576,
                "Body": "{\"A\":\"用户-mail地址在整个因特网是唯一的\",\"B\":\"用户-mail地址在用户所在邮件服务器中是唯一的\",\"C\":\"用户-mail地址在一个国家是唯一的\",\"D\":\"用户-mail地址可以不唯一\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下关于用户E-mail地址唯一性的叙述正确的是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274705,
                "Body": "{\"A\":\"中继器\",\"B\":\"滤波器\",\"C\":\"路由器\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ADSL使用的信号分离器又称为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274711,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"IP地址\",\"C\":\"域名地址\",\"D\":\"统一资源定位器（R）\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "WWW上的每一个网页包括主页都有一个独立的地址，这些地址由32位二进制表示则称为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274698,
                "Body": "{\"A\":\"分组丢弃法\",\"B\":\"缓冲区预分配法\",\"C\":\"定额控制法\",\"D\":\"存储转发法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在阻塞控制方法中，直接对通信子网中分组的数量进行严格、精确的限制，以防止阻塞现象发生的方法为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274577,
                "Body": "{\"A\":\"邮件服务器\",\"B\":\"域名系统(N)\",\"C\":\"统一资源定位器(R)\",\"D\":\"代理服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "E-mail地址格式为：用户名@主机域名，传送邮件时必须将主机域名转换成IP地址，实现该项转换工作的是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274704,
                "Body": "{\"A\":\"128bps\",\"B\":\"144bps\",\"C\":\"256bps\",\"D\":\"512bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISDN提供的是2B+D的数据通道，其速率最高可达到（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274613,
                "Body": "{\"A\":\"字节计数法\",\"B\":\"使用字符填充的首尾定界符法\",\"C\":\"使用比特填充的首尾标志法\",\"D\":\"违法编码法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "HDLC规程采用的帧同步方法为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274624,
                "Body": "{\"A\":\"A类地址\",\"B\":\"B类地址\",\"C\":\"C类地址\",\"D\":\"广播地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址112.1.4.13属于（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274695,
                "Body": "{\"A\":\"COE中的编码器\",\"B\":\"COE中的解码器\",\"C\":\"MOE中的调制器\",\"D\":\"MOE中的解调器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "模拟数据也可以用数字信号来表示。对于声音数据来说，完成将模拟数据转换为数字信号的设施为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274616,
                "Body": "{\"A\":\"IEE802.11\",\"B\":\"IEE802.11a\",\"C\":\"IEE802.11b\",\"D\":\"IEE802.11b+\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "若要求组建一个带宽能达到54Mbps的无线局域网时，选用的无线设备应支持的无线局域网标准是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274563,
                "Body": "{\"A\":\"传送原始比特流\",\"B\":\"建立数据链路连接\",\"C\":\"实现路由选择\",\"D\":\"提供端到端的服务\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "OSI参考模型中物理层的主要作用是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274574,
                "Body": "{\"A\":\"IS主机\",\"B\":\"通信网络的交换节点\",\"C\":\"ICD、W服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP拨号方式是通过电话拨号将自己的计算机连接到（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274627,
                "Body": "{\"A\":\"在整个因特网上是唯一的\",\"B\":\"在一个国家是唯一的\",\"C\":\"在用户所在邮件服务器中是唯一的\",\"D\":\"在同一网络标识的网上是唯一的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "用户E-mail地址中的用户名（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274696,
                "Body": "{\"A\":\"IP，ICMP，ARP，UDP\",\"B\":\"TCP，ICMP，UDP，ARP\",\"C\":\"IP，ICMP，ARP，RARP\",\"D\":\"UDP，IP，ICMP，RARP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>TCP／IP的互连层含有四个重要的协议，分别为（　）。</p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274570,
                "Body": "{\"A\":\"按需分配\",\"B\":\"平均分配\",\"C\":\"根据业务种类按比例分配\",\"D\":\"一种业务对应一个固定的时间片\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ATM网络的各种业务在信道上时间片的分配原则是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]