var topic5_1_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic5_1_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 274522,
                "Body": "{\"A\":\"1倍\",\"B\":\"2倍\",\"C\":\"3倍\",\"D\":\"4倍\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "CSMA／CD的代价是用于检测冲突所花费的时间。对于基带总线而言，最坏情况下用于检测一个冲突的时间等于任意两个站之间最大传播时延的（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275381,
                "Body": "{\"A\":\"Internet    \",\"B\":\"无线局域网    \",\"C\":\"ARA网    \",\"D\":\"多媒体网络\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "被称为计算机网络技术发展里程碑的网络是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275312,
                "Body": "{\"A\":\"主机 \",\"B\":\"键盘\",\"C\":\"TC/P \",\"D\":\"OSI\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在网络管理中,必须实现代理模块的设备是",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275408,
                "Body": "{\"A\":\"频分多址DA    \",\"B\":\"时分多址DA    \",\"C\":\"码分多址DA    \",\"D\":\"波分多址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在蜂窝移动通信系统中，主要采用的接入方法不包括",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274472,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275240,
                "Body": "{\"A\":\"\\tRAE       \",\"B\":\"\\tEnet       \",\"C\":\"\\tSNT      \",\"D\":\"\\tthernet\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网（Internet）的起源可追溯到它的前身",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275302,
                "Body": "{\"A\":\"ARP\",\"B\":\"RARP\",\"C\":\"ICMP\",\"D\":\"FTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在TCP/IP环境下，网络层有一组协议将IP地址转换为相应物理网络地址，这组协议即是",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275148,
                "Body": "{\"A\":\"数据链路层\",\"B\":\"网络层\",\"C\":\"传输层\",\"D\":\"应用层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "路由器是一种重要的网络互连设备，它所实现的网络互连层次属于<br><br>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274881,
                "Body": "{\"A\":\"LAA\",\"B\":\"LAB\",\"C\":\"LAC\",\"D\":\"LAD\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继采用的链路接人规程为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274766,
                "Body": "{\"A\":\"从512bit/s到1bit/s\",\"B\":\"从144bit/s到8bit/s\",\"C\":\"从128bit/s到2bit/s\",\"D\":\"从64bit/s到52bit/s\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "xDSL技术的最大特点是使用电信部门已经铺设的双绞线作为传输线路提供宽带传输速率，其速度范围是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274875,
                "Body": "{\"A\":\"级别1\",\"B\":\"级别2\",\"C\":\"级别3\",\"D\":\"级别4\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "传输层的功能按级别划分，OSl定义了五种协议级别，其中能够提供差错检测，恢复即多路复用功能的级别是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275244,
                "Body": "{\"A\":\"奇偶校验码    \",\"B\":\"海明编码    \",\"C\":\"循环冗余码    \",\"D\":\"PC编码\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "计算机网络和数据通信中使用最广泛的检错码是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274478,
                "Body": "{\"A\":\"被管代理\",\"B\":\"网络管理器\",\"C\":\"网络管理协议\",\"D\":\"管理信息库\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络管理系统中驻留在被管对象上配合网络管理的处理实体称为（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274860,
                "Body": "{\"A\":\"转发器\",\"B\":\"路由器\",\"C\":\"网关\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对传输层和传输层以上的协议进行转换的设备称为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274483,
                "Body": "{\"A\":\"图形图像压缩文件\",\"B\":\"二进制文件\",\"C\":\"文本文件\",\"D\":\"HTL文本文件\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "点击浏览器上的网页地址，从Web服务器下传的是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275255,
                "Body": "{\"A\":\"电话\",\"B\":\"卫星\",\"C\":\"光缆线\",\"D\":\"网络连接器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列不属于通信链路介质的是 （　　）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274870,
                "Body": "{\"A\":\"远程通信网络\",\"B\":\"消息通信网络\",\"C\":\"事务管理网络\",\"D\":\"开放式标准化网络\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "计算机网络的发展和演变，可总体概括为四个阶段，它们是面向终端的计算机网络、计算机——计算机网络、因特网的广泛应用与高速网络技术的发展、（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274477,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下不属于光纤用户网的特点是（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274718,
                "Body": "{\"A\":\"帧\",\"B\":\"位\",\"C\":\"分组\",\"D\":\"报文\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据链路层的协议数据单元称作（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275298,
                "Body": "{\"A\":\"字节计数法                    \",\"B\":\"比特填充的首尾标志法  \",\"C\":\"违法编码法                    \",\"D\":\"字符填充的首尾定界符法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网IEEE802标准中采用的帧同步方法是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274696,
                "Body": "{\"A\":\"IP，ICMP，ARP，UDP\",\"B\":\"TCP，ICMP，UDP，ARP\",\"C\":\"IP，ICMP，ARP，RARP\",\"D\":\"UDP，IP，ICMP，RARP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>TCP／IP的互连层含有四个重要的协议，分别为（　）。</p>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274704,
                "Body": "{\"A\":\"128bps\",\"B\":\"144bps\",\"C\":\"256bps\",\"D\":\"512bps\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISDN提供的是2B+D的数据通道，其速率最高可达到（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274568,
                "Body": "{\"A\":\"1层\",\"B\":\"1-2层\",\"C\":\"1-3层\",\"D\":\"1-4层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "广域网技术主要对应OSI参考模型底层的（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274616,
                "Body": "{\"A\":\"IEE802.11\",\"B\":\"IEE802.11a\",\"C\":\"IEE802.11b\",\"D\":\"IEE802.11b+\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "若要求组建一个带宽能达到54Mbps的无线局域网时，选用的无线设备应支持的无线局域网标准是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274617,
                "Body": "{\"A\":\"包\",\"B\":\"信元\",\"C\":\"分组\",\"D\":\"帧\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网的链路上无差错的传输比特流称为（　）",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274574,
                "Body": "{\"A\":\"IS主机\",\"B\":\"通信网络的交换节点\",\"C\":\"ICD、W服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP拨号方式是通过电话拨号将自己的计算机连接到（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274577,
                "Body": "{\"A\":\"邮件服务器\",\"B\":\"域名系统(N)\",\"C\":\"统一资源定位器(R)\",\"D\":\"代理服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "E-mail地址格式为：用户名@主机域名，传送邮件时必须将主机域名转换成IP地址，实现该项转换工作的是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274701,
                "Body": "{\"A\":\"曼彻斯特编码\",\"B\":\"4B/5B\",\"C\":\"8B/10B\",\"D\":\"64B/66B\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>10GBase-R万兆以太网采用的编码方式是（　）。</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274621,
                "Body": "{\"A\":\"拨号MODEM\",\"B\":\"ISDN(2B+D)\",\"C\":\"ADSL\",\"D\":\"光纤以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>在下列个人用户接入广域网技术中，传输速率最高的是（　）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274567,
                "Body": "{\"A\":\"65米\",\"B\":\"300米\",\"C\":\"1公里\",\"D\":\"40公里\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "万兆以太网物理层的1310纳米WWDM LAN接口支持的传输距离是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274708,
                "Body": "{\"A\":\"被管代理\",\"B\":\"网络管理器\",\"C\":\"网络管理协议\",\"D\":\"管理信息库\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络管理系统中驻留在被管对象上配合网络管理的处理实体称为（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274612,
                "Body": "{\"A\":\"IP\",\"B\":\"ARP\",\"C\":\"TCP\",\"D\":\"DNS\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>下列协议中运行在应用层的协议是（　）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274563,
                "Body": "{\"A\":\"传送原始比特流\",\"B\":\"建立数据链路连接\",\"C\":\"实现路由选择\",\"D\":\"提供端到端的服务\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "OSI参考模型中物理层的主要作用是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274570,
                "Body": "{\"A\":\"按需分配\",\"B\":\"平均分配\",\"C\":\"根据业务种类按比例分配\",\"D\":\"一种业务对应一个固定的时间片\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ATM网络的各种业务在信道上时间片的分配原则是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274625,
                "Body": "{\"A\":\"255.255.255.0\",\"B\":\"255.255.255.192\",\"C\":\"255.255.255.248\",\"D\":\"255.255.255.240\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "某部门申请了一个C类IP地址，若要分成32个子网，其掩码应为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274627,
                "Body": "{\"A\":\"在整个因特网上是唯一的\",\"B\":\"在一个国家是唯一的\",\"C\":\"在用户所在邮件服务器中是唯一的\",\"D\":\"在同一网络标识的网上是唯一的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "用户E-mail地址中的用户名（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274702,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274707,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下说法中，不属于光纤用户网的特点是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274713,
                "Body": "{\"A\":\"图形图像压缩文件\",\"B\":\"二进制文件\",\"C\":\"文本文件\",\"D\":\"HTL文本文件\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "点击浏览器上的网页地址，从Web服务器下传的是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274561,
                "Body": "{\"A\":\"每一层实现一种相对独立的功能\",\"B\":\"每一层都知道下面一层是如何实现的\",\"C\":\"每一层的功能相对简单且易于实现和维护\",\"D\":\"每一层不必知道下面一层是如何实现的\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列哪一项错误地描述了网络体系结构中分层的特点（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597647,
                "Body": "{\n  \"A\": \"广域网\",\n  \"B\": \"城域网\",\n  \"C\": \"局域网\",\n  \"D\": \"因特网\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "按照通信距离和作用范围，计算机网络分为",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597641,
                "Body": "{\n  \"A\": \"主机通过交换机接入到网络\",\n  \"B\": \"交换机连接交换以延展网络的范围\",\n  \"C\": \"交换机连交换机增加接口的数量\",\n  \"D\": \"多台交换机虚拟成逻辑交换机以增强性能\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面列举的网络连接技术中，能够通过普通以太网接口完成的是",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]