var topic5_2_02141 = [
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 1,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "topic5_2_02141单选题",
            "Num": 2,
            "TopicCount": 40,
            "OrderID": 1,
            "TitleLong": "本题共40小题，每小题2分，共80分，在每小题给出的几个选项中，只有一项是符合题目要求的。"
        },
        "Question": [
            {
                "ID": 274837,
                "Body": "{\"A\":\"30%\",\"B\":\"70%\",\"C\":\"80%\",\"D\":\"20%\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "采用异步传输方式，若数据位为7位，1位校验位，1位停止位，则其通信效率为（　）。",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274717,
                "Body": "{\"A\":\"一种计算机网络的实现\",\"B\":\"执行计算机数据处理的软件模块\",\"C\":\"由S定义的一个标准\",\"D\":\"计算机网络各层次结构模型及其协议的集合\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "网络体系结构可以定义为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275239,
                "Body": "{\"A\":\"\\t“存储——转发”式\",\"B\":\"\\t广播式\",\"C\":\"\\t电路交换式\",\"D\":\"\\t分散控制\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网LAN所采用的传输方式为",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275380,
                "Body": "{\"A\":\"CMIS\",\"B\":\"SNMP       \",\"C\":\"CMIP           \",\"D\":\"SMTP\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "基于TCP／IP协议簇的网络管理标准协议是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275400,
                "Body": "{\"A\":\"分担负荷\",\"B\":\"硬件资源共享\",\"C\":\"软件资源共享\",\"D\":\"用户间信息交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "通过计算机网络发布新闻消息活动，属于 （　　）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275170,
                "Body": "{\"A\":\"中继器\",\"B\":\"交换机\",\"C\":\"防火墙\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "为增强Intranet的安全性，在被保护的Intranet与Internet之间竖起一道安全屏障称为（）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275281,
                "Body": "{\"A\":\"模拟传输\",\"B\":\"数字传输\",\"C\":\"模拟—数字混合传输\",\"D\":\"以上均不对\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在局域网中，由于距离近以及数字电路器件价格的下降，所以更具优越性的传输技术是",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274730,
                "Body": "{\"A\":\"邮件服务器地址\",\"B\":\"字符形式的网页地址\",\"C\":\"字符形式的P地址\",\"D\":\"Web服务器地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "Internet上的域名是（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274733,
                "Body": "{\"A\":\"在Web服务器进行\",\"B\":\"在代理服务器上进行\",\"C\":\"在浏览器上进行\",\"D\":\"在ISP上进行\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>点击浏览器上的网页地址，该网页的HTML文件的解释执行（　）。</p>",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275310,
                "Body": "{\"A\":\"路由划分    \",\"B\":\"按交换端口号划分    \",\"C\":\"按MAC地址划分    \",\"D\":\"按第三层协议划分\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列所述划分虚拟局域网的常用方法中错误的",
                "Answer": "A",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275240,
                "Body": "{\"A\":\"\\tRAE       \",\"B\":\"\\tEnet       \",\"C\":\"\\tSNT      \",\"D\":\"\\tthernet\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "因特网（Internet）的起源可追溯到它的前身",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274825,
                "Body": "{\"A\":\"链路层和网络层\",\"B\":\"物理层和网络层\",\"C\":\"网络层和传输层\",\"D\":\"物理层和链路层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术使用链路层实现复用和转接，所以帧中继网络的中间结点中只有（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274525,
                "Body": "{\"A\":\"物理层和链路层\",\"B\":\"物理层和网络层\",\"C\":\"链路层和网络层\",\"D\":\"网络层和传输层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继技术首先是淡化了交换设备上的层次概念，将数据链路层和网络层进行了融合，所以帧中继中只有 （　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275148,
                "Body": "{\"A\":\"数据链路层\",\"B\":\"网络层\",\"C\":\"传输层\",\"D\":\"应用层\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "路由器是一种重要的网络互连设备，它所实现的网络互连层次属于<br><br>",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275255,
                "Body": "{\"A\":\"电话\",\"B\":\"卫星\",\"C\":\"光缆线\",\"D\":\"网络连接器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "下列不属于通信链路介质的是 （　　）",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275298,
                "Body": "{\"A\":\"字节计数法                    \",\"B\":\"比特填充的首尾标志法  \",\"C\":\"违法编码法                    \",\"D\":\"字符填充的首尾定界符法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "局域网IEEE802标准中采用的帧同步方法是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275143,
                "Body": "{\"A\":\"环形拓扑\",\"B\":\"树型结构\",\"C\":\"网形拓扑\",\"D\":\"总线拓扑\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在广域网得到了广泛应用、节点之间有许多条路径相连，这样的网络拓扑结构是<br><br>",
                "Answer": "C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 275292,
                "Body": "{\"A\":\"\\tSN方式\",\"B\":\"\\t仿真终端方式\",\"C\":\"\\t局域网连接方式\",\"D\":\"\\t广域网连接方式\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在Internet中，ISP的接入方式有帧中继方式、专线（DDN）方式及",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274724,
                "Body": "{\"A\":\"电路交换+分组交换\",\"B\":\"分组交换\",\"C\":\"报文交换\",\"D\":\"电路交换\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "综合业务数字网（N-ISDN）采用的交换技术是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275381,
                "Body": "{\"A\":\"Internet    \",\"B\":\"无线局域网    \",\"C\":\"ARA网    \",\"D\":\"多媒体网络\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "被称为计算机网络技术发展里程碑的网络是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275394,
                "Body": "{\"A\":\"消息泄漏 \",\"B\":\"假冒\",\"C\":\"拒绝服务 \",\"D\":\"修改报文流\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "SNMPv3中哪种威胁是安全体系结构不必防护的?",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274881,
                "Body": "{\"A\":\"LAA\",\"B\":\"LAB\",\"C\":\"LAC\",\"D\":\"LAD\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "帧中继采用的链路接人规程为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274531,
                "Body": "{\"A\":\"故障管理\",\"B\":\"客户管理\",\"C\":\"应用管理\",\"D\":\"运营管理\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ISO建议网络管理的基本功能应包括计费管理、配置管理、性能管理、安全管理和（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274860,
                "Body": "{\"A\":\"转发器\",\"B\":\"路由器\",\"C\":\"网关\",\"D\":\"网桥\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对传输层和传输层以上的协议进行转换的设备称为（　）。",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 275244,
                "Body": "{\"A\":\"奇偶校验码    \",\"B\":\"海明编码    \",\"C\":\"循环冗余码    \",\"D\":\"PC编码\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "计算机网络和数据通信中使用最广泛的检错码是",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274618,
                "Body": "{\"A\":\"网络终端Tl\",\"B\":\"网络终端T2\",\"C\":\"网络终端Tl+T2\",\"D\":\"调制解调器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "对于家庭和小型机构在用户设备和ISDN交换设备之间需要安装的设备是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274614,
                "Body": "{\"A\":\"信号传播时延\",\"B\":\"数据传输时延\",\"C\":\"冲突检测时间\",\"D\":\"数据接收时延\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "数据帧从一个站点开始发送，到该数据帧发送完毕所需的时间称为（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274707,
                "Body": "{\"A\":\"传输带宽高\",\"B\":\"传输速度快\",\"C\":\"传输距离远\",\"D\":\"抗干扰能力差\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下说法中，不属于光纤用户网的特点是（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274711,
                "Body": "{\"A\":\"E-mail地址\",\"B\":\"IP地址\",\"C\":\"域名地址\",\"D\":\"统一资源定位器（R）\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "WWW上的每一个网页包括主页都有一个独立的地址，这些地址由32位二进制表示则称为（　）。",
                "Answer": "D",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274611,
                "Body": "{\"A\":\"分配IP地址\",\"B\":\"提供端到端的面向连接的可靠数据传输\",\"C\":\"确定数据传输路径\",\"D\":\"提高传输速度\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "TCP协议的主要功能是（　）",
                "Answer": "B",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274576,
                "Body": "{\"A\":\"用户-mail地址在整个因特网是唯一的\",\"B\":\"用户-mail地址在用户所在邮件服务器中是唯一的\",\"C\":\"用户-mail地址在一个国家是唯一的\",\"D\":\"用户-mail地址可以不唯一\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "以下关于用户E-mail地址唯一性的叙述正确的是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274621,
                "Body": "{\"A\":\"拨号MODEM\",\"B\":\"ISDN(2B+D)\",\"C\":\"ADSL\",\"D\":\"光纤以太网\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>在下列个人用户接入广域网技术中，传输速率最高的是（　）</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274624,
                "Body": "{\"A\":\"A类地址\",\"B\":\"B类地址\",\"C\":\"C类地址\",\"D\":\"广播地址\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "IP地址112.1.4.13属于（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274613,
                "Body": "{\"A\":\"字节计数法\",\"B\":\"使用字符填充的首尾定界符法\",\"C\":\"使用比特填充的首尾标志法\",\"D\":\"违法编码法\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "HDLC规程采用的帧同步方法为（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274562,
                "Body": "{\"A\":\"将P地址解析为物理地址\",\"B\":\"将物理地址解析为P地址\",\"C\":\"将主机域名解析为P地址\",\"D\":\"将P地址解析为主机域名\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "ARP协议的主要功能是（　）",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274573,
                "Body": "{\"A\":\"FTC\",\"B\":\"FTZ\",\"C\":\"FTO\",\"D\":\"FTF\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "光纤到办公室的用户网光纤化方案是（　）",
                "Answer": "C",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274702,
                "Body": "{\"A\":\"30\",\"B\":\"50\",\"C\":\"100\",\"D\":\"256\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "在使用无线AP组建无线局域网时，通常建议在网络中使用的客户机总数不超过（　）。",
                "Answer": "A",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274701,
                "Body": "{\"A\":\"曼彻斯特编码\",\"B\":\"4B/5B\",\"C\":\"8B/10B\",\"D\":\"64B/66B\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "<p>10GBase-R万兆以太网采用的编码方式是（　）。</p>",
                "Answer": "D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 274610,
                "Body": "{\"A\":\"包\",\"B\":\"比特\",\"C\":\"帧\",\"D\":\"数据块\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "物理层传输的数据单位是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            },
            {
                "ID": 274577,
                "Body": "{\"A\":\"邮件服务器\",\"B\":\"域名系统(N)\",\"C\":\"统一资源定位器(R)\",\"D\":\"代理服务器\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 1,
                "QuestionData_ID": 0,
                "Title": "E-mail地址格式为：用户名@主机域名，传送邮件时必须将主机域名转换成IP地址，实现该项转换工作的是（　）",
                "Answer": "B",
                "Mark": "",
                "Judge": -2
            }
        ]
    },
    {
        "TypeInfo": {
            "Plan_ID": 215,
            "System_Station_ID": 96,
            "QuestionType_ID": 2,
            "BusType": 1,
            "Curriculum_ID": 5198,
            "Title": "多选题",
            "Num": 2,
            "TopicCount": 10,
            "OrderID": 2,
            "TitleLong": "本题共10小题，每小题2分，共20分。"
        },
        "Question": [
            {
                "ID": 1597645,
                "Body": "{\n  \"A\": \"证券交易系统\",\n  \"B\": \"信息处理系统\",\n  \"C\": \"远程医疗\",\n  \"D\": \"电子图书\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "下面()属于网络应用。",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597640,
                "Body": "{\n  \"A\": \"相同的数据格式\",\n  \"B\": \"形同的物理层实现技术\",\n  \"C\": \"相同的组网方法\",\n  \"D\": \"相同的介质访问控制方法\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "千兆以太网和百兆以太网的共同特点是",
                "Answer": "A,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597644,
                "Body": "{\n  \"A\": \"标示无线设备所属的WLAN\",\n  \"B\": \"包含32个字符\",\n  \"C\": \"负责确定信号强度\",\n  \"D\": \"同一WLAN中的所有无线设备必须具有相同的SSID\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "效劳集(SSID)是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597637,
                "Body": "{\n  \"A\": \"双绞线\",\n  \"B\": \"同轴电缆\",\n  \"C\": \"光缆\",\n  \"D\": \"无线介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下传输介质中，可以在局域网中使用的是",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597642,
                "Body": "{\n  \"A\": \"Console端口\",\n  \"B\": \"AUX端口\",\n  \"C\": \"onsole端口\",\n  \"D\": \"RJ45端口\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "在路由器上可以出现的端口是",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597648,
                "Body": "{\n  \"A\": \"主机\",\n  \"B\": \"共享的外部设备\",\n  \"C\": \"网络设备\",\n  \"D\": \"传输介质\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "网络组件可分为",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597638,
                "Body": "{\n  \"A\": \"集\",\n  \"B\": \"路由器\",\n  \"C\": \"网桥\",\n  \"D\": \"中继器\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "以下属于物理层设备的是",
                "Answer": "A,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597643,
                "Body": "{\"A\":\"100BASE-T交换机\",\"B\":\"100BASE-T网卡\",\"C\":\"路由器\",\"D\":\"双绞线或光缆\"}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "<p>要组建一个快速以太网，需要的根本硬件设备与材料包括</p>",
                "Answer": "A,B,D",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597639,
                "Body": "{\n  \"A\": \"局域网\",\n  \"B\": \"城域网\",\n  \"C\": \"广域网\",\n  \"D\": \"无线网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "Internet中包含的网络类型包括",
                "Answer": "A,B,C",
                "Mark": null,
                "Judge": -2
            },
            {
                "ID": 1597646,
                "Body": "{\n  \"A\": \"计算机网络\",\n  \"B\": \"电视网络\",\n  \"C\": \"有线网络\",\n  \"D\": \"移动网络\"\n}",
                "FileList": null,
                "MyAnswer": null,
                "QuestionType_ID": 2,
                "QuestionData_ID": 0,
                "Title": "新型的多功能融合信息网络包括",
                "Answer": "A,B,C,D",
                "Mark": null,
                "Judge": -2
            }
        ]
    }
]